import type { Locale } from "@nailsoft/domain-types";

const en: Record<string, string> = {
  signIn: "Sign in", email: "Email", password: "Password", selectWorkspace: "Select workspace", verify: "Verify", recoveryCode: "Use recovery code", enrollMfa: "Set up verification", signOut: "Sign out", retry: "Retry", loading: "Loading", unavailable: "Staff Mobile is not available for this workspace.", missingStaff: "Staff profile is not linked to this account.", forbidden: "This assigned work is not available to this account.", offline: "Internet connection required. This action was not queued.", changed: "This item changed since you opened it. Reload before deciding again.", home: "Today", schedule: "Schedule", queue: "Guests", more: "More", myWork: "My work", noRecords: "No records are available.", noShift: "No shift is scheduled.", noAssignedWork: "No assigned work is available.", currentService: "Current service", nextAppointment: "Next appointment", timeClock: "Time clock", profile: "Profile", branch: "Branch", workspace: "Workspace", draftSaved: "Draft saved locally; it is not synced.", mediaDeferred: "Photo attachments are not available in this release.", noStoredValue: "Stored-value browsing is deferred for privacy.", sessionSecurity: "Session security", mfa: "Multi-factor authentication", customerNote: "Customer note", none: "None", serverTime: "Server time", clockedIn: "Clocked in", notClockedIn: "Not clocked in", start: "Start", pause: "Pause", resume: "Resume", complete: "Complete", refresh: "Refresh", open: "Open", retrySafely: "Command failed safely. Retry when connected.", versionConflict: "This record changed since you opened it. Reload before deciding again.", locale: "Language", assignedScope: "Only assigned work is shown.", noPermission: "Permission denied.", guestScope: "Assigned guests", recovery: "Recovery tasks", earnings: "Earnings", materials: "Materials", leave: "Leave and timesheets", attendance: "Attendance", logout: "Sign out", workspaceChoice: "Choose a workspace", sessionExpired: "Your session expired. Sign in again.", code: "Verification code", recoveryCodes: "Recovery codes (shown once)", secretDeferred: "Secure media upload is deferred.",
};
const vi: Record<string, string> = {
  signIn: "Đăng nhập", email: "Email", password: "Mật khẩu", selectWorkspace: "Chọn không gian", verify: "Xác minh", recoveryCode: "Dùng mã khôi phục", enrollMfa: "Thiết lập xác minh", signOut: "Đăng xuất", retry: "Thử lại", loading: "Đang tải", unavailable: "Staff Mobile không khả dụng cho không gian này.", missingStaff: "Tài khoản chưa được liên kết với hồ sơ nhân viên.", forbidden: "Công việc được phân công không khả dụng cho tài khoản này.", offline: "Cần kết nối mạng. Thao tác không được xếp hàng.", changed: "Bản ghi đã thay đổi. Hãy tải lại trước khi quyết định.", home: "Hôm nay", schedule: "Lịch", queue: "Khách được giao", more: "Thêm", myWork: "Công việc của tôi", noRecords: "Chưa có dữ liệu.", noShift: "Chưa có ca làm.", noAssignedWork: "Chưa có công việc được giao.", currentService: "Dịch vụ hiện tại", nextAppointment: "Lịch hẹn tiếp theo", timeClock: "Chấm công", profile: "Hồ sơ", branch: "Chi nhánh", workspace: "Không gian", draftSaved: "Bản nháp đã lưu cục bộ, chưa đồng bộ.", mediaDeferred: "Đính kèm ảnh chưa khả dụng trong bản phát hành này.", noStoredValue: "Duyệt stored-value được trì hoãn vì quyền riêng tư.", sessionSecurity: "Bảo mật phiên", mfa: "Xác thực đa yếu tố", customerNote: "Ghi chú khách", none: "Không có", serverTime: "Giờ máy chủ", clockedIn: "Đã vào ca", notClockedIn: "Chưa vào ca", start: "Bắt đầu", pause: "Tạm dừng", resume: "Tiếp tục", complete: "Hoàn tất", refresh: "Làm mới", open: "Mở", retrySafely: "Thao tác thất bại an toàn. Hãy thử lại khi có mạng.", versionConflict: "Bản ghi đã thay đổi. Hãy tải lại trước khi quyết định.", locale: "Ngôn ngữ", assignedScope: "Chỉ hiển thị công việc được phân công.", noPermission: "Không có quyền.", guestScope: "Khách được giao", recovery: "Công việc khôi phục", earnings: "Thu nhập", materials: "Vật tư", leave: "Nghỉ phép và bảng công", attendance: "Chấm công", logout: "Đăng xuất", workspaceChoice: "Chọn không gian", sessionExpired: "Phiên đã hết hạn. Hãy đăng nhập lại.", code: "Mã xác minh", recoveryCodes: "Mã khôi phục (chỉ hiển thị một lần)", secretDeferred: "Tải ảnh bảo mật được trì hoãn.",
};

export function staffText(locale: Locale | string | undefined, key: string) {
  const dictionary = locale === "vi-VN" ? vi : en;
  return dictionary[key] ?? en[key] ?? key;
}
