/* eslint-disable @typescript-eslint/no-explicit-any */
import { Link, useLocalSearchParams } from "expo-router";
import { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, Button, SafeAreaView, ScrollView, Text, TextInput, View } from "react-native";
import { apiFetch } from "../lib/session";

const branch="20000000-0000-4000-8000-000000000001",service="50000000-0000-4000-8000-000000000001";
const titles: Record<string, string> = { profile: "My profile", branches: "My branches", skills: "My skills", shifts: "My upcoming shifts", leave: "My leave requests", createLeave: "Create leave request", leaveDetail: "Leave request detail", invitation: "Invitation activation", sessions: "My sessions", language: "Language", workspace: "Workspace selection", mfa: "MFA challenge",myCalendar:"My calendar",myBusy:"My busy blocks",myAvailability:"My availability summary" };
export default function StaffScreen() {
  const params = useLocalSearchParams<{ screen: string; id?: string }>(); const screen = params.screen; const [state, setState] = useState<"loading" | "ready" | "empty" | "error" | "forbidden">("loading"); const [data, setData] = useState<any[]>([]); const [reason, setReason] = useState(""); const [message, setMessage] = useState("");
  const load = useCallback(async () => { let path: string | null = null; if (screen === "profile" || screen === "branches" || screen === "skills" || screen === "createLeave") path = "/v1/staff/me"; else if (screen === "shifts") path = "/v1/shifts"; else if (screen === "leave") path = "/v1/leave-requests"; else if (screen === "leaveDetail" && params.id) path = `/v1/leave-requests/${params.id}`;else if(screen==="myCalendar")path=`/v1/calendar/events?branchId=${branch}&from=2026-08-10T00:00:00%2B07:00&to=2026-08-17T00:00:00%2B07:00`;else if(screen==="myBusy")path=`/v1/availability-blocks?branchId=${branch}&from=2026-08-01T00:00:00%2B07:00&to=2026-09-01T00:00:00%2B07:00`;else if(screen==="myAvailability")path=`/v1/availability?branchId=${branch}&serviceId=${service}&dateFrom=2026-08-10&dateTo=2026-08-10`; if (!path) { setState("empty"); return; } setState("loading"); try { const response = await apiFetch(path); if (response.status === 401 || response.status === 403) { setState("forbidden"); return; } const body = await response.json(); if (!response.ok) throw new Error(body.error?.message ?? "Unable to load"); const raw=body.data;let value = Array.isArray(raw) ? raw : raw?.events??raw?.days??[raw]; const me = body.data?.id; if (me && (screen === "branches" || screen === "skills")) { const related = await apiFetch(`/v1/staff/${me}/${screen}`); const relatedBody = await related.json(); if (!related.ok) throw new Error(relatedBody.error?.message ?? "Unable to load"); value = Array.isArray(relatedBody.data) ? relatedBody.data : [relatedBody.data]; } setData(value.filter(Boolean)); setState(value.filter(Boolean).length ? "ready" : "empty"); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to load"); setState("error"); } }, [screen, params.id]);
  useEffect(() => { void load(); }, [load]);
  async function createLeave() { const body = { staffId: data[0]?.id, branchId: data[0]?.branchId, leaveType: "PERSONAL", startAt: new Date().toISOString(), endAt: new Date(Date.now() + 3600000).toISOString(), reason }; const response = await apiFetch("/v1/leave-requests", { method: "POST", headers: { "content-type": "application/json", "idempotency-key": `leave-${Date.now()}` }, body: JSON.stringify(body) }); setMessage(response.ok ? "Leave request created." : "Leave request could not be created."); }
  return <SafeAreaView><ScrollView contentContainerStyle={{ padding: 24, gap: 16 }}><Text style={{ color: "#6D28D9", fontWeight: "700" }}>STAFF · SPRINT 2</Text><Text style={{ fontSize: 30, fontWeight: "700" }}>{titles[screen] ?? "Workspace"}</Text>{state === "loading" && <ActivityIndicator accessibilityLabel="Loading" />}{state === "forbidden" && <Text accessibilityRole="alert">Permission denied for this workspace.</Text>}{state === "error" && <View><Text accessibilityRole="alert">{message}</Text><Button title="Retry" onPress={() => void load()} /></View>}{state === "empty" && <View><Text>No records are available.</Text><Button title="Refresh" onPress={() => void load()} /></View>}{state === "ready" && <View style={{ gap: 12 }}>{data.map((item, index) => <View key={item.id ?? index} style={{ padding: 16, backgroundColor: "#F3EEFF", borderRadius: 12 }}><Text style={{ fontWeight: "700" }}>{item.displayName ?? item.code ?? item.name?.["vi-VN"] ?? item.status ?? item.id}</Text><Text>{item.startAt ? `${item.startAt} – ${item.endAt}` : item.status ?? "Active"}</Text>{screen === "leave" && item.id && <Link href={`/leaveDetail?id=${item.id}` as never}>Open detail</Link>}</View>)}</View>}{screen === "createLeave" && <View style={{ gap: 10 }}><TextInput placeholder="Reason" value={reason} onChangeText={setReason} style={{ borderWidth: 1, padding: 12 }} /><Button title="Create leave request" onPress={() => void createLeave()} /></View>}<Link href="/">Back to home</Link></ScrollView></SafeAreaView>;
}
