export const backendModuleBoundaries = [
  "identity",
  "organization",
  "staff",
  "service-catalog",
  "availability",
  "booking",
  "queue",
  "customer",
  "service-execution",
  "pos",
  "payment",
  "commission",
  "inventory",
  "voucher",
  "loyalty",
  "membership",
  "service-package",
  "benefits",
  "gift-card",
  "customer-credit",
  "stored-value",
  "marketing",
  "notification",
  "customer-engagement",
  "review",
  "service-recovery",
  "reporting",
  "approval",
  "audit",
  "subscription",
  "integration",
] as const;
export type BackendModuleBoundary = (typeof backendModuleBoundaries)[number];
