/* eslint-disable @typescript-eslint/no-explicit-any, @typescript-eslint/no-unused-vars */
import { Body, Controller, Get, Headers, Param, Post, Query, Req, UseGuards } from "@nestjs/common";
import { ApiBearerAuth, ApiTags } from "@nestjs/swagger";
import type { AuthenticatedRequest } from "../identity/auth.types.js";
import { AuthGuard } from "../identity/auth.guard.js";
import { PermissionGuard } from "../identity/permission.guard.js";
import { RequirePermission } from "../identity/permission.decorator.js";
import { AssetsService } from "./assets.service.js";

const key=(v?:string)=>v??""; const rid=(r:AuthenticatedRequest)=>r.raw.requestId??"unknown"; const ok=(data:unknown,r:AuthenticatedRequest)=>({success:true,data,meta:{requestId:rid(r),timestamp:new Date().toISOString()}});
@ApiBearerAuth() @ApiTags("assets") @UseGuards(AuthGuard,PermissionGuard) @Controller("assets")
export class AssetsController {
  constructor(private readonly s:AssetsService) {}
  @Get("configuration/readiness") @RequirePermission("asset.configuration.manage") readiness(@Req() r:AuthenticatedRequest){return this.s.readiness(r.auth).then(x=>ok(x,r));}
  @Post("configuration/activate") @RequirePermission("asset.configuration.manage") activate(@Body() b:any,@Headers("idempotency-key") k:string,@Req() r:AuthenticatedRequest){return this.s.activateConfiguration(r.auth,b,key(k),rid(r)).then(x=>ok(x,r));}
  @Post("configuration/disable") @RequirePermission("asset.configuration.manage") disable(@Body() b:any,@Headers("idempotency-key") k:string,@Req() r:AuthenticatedRequest){return this.s.disableConfiguration(r.auth,b,key(k),rid(r)).then(x=>ok(x,r));}
  @Get("categories") @RequirePermission("asset.category.read") categories(@Req() r:AuthenticatedRequest){return this.s.listCategories(r.auth).then(x=>ok(x,r));}
  @Post("categories") @RequirePermission("asset.category.manage") createCategory(@Body() b:any,@Headers("idempotency-key") k:string,@Req() r:AuthenticatedRequest){return this.s.createCategory(r.auth,b,key(k),rid(r)).then(x=>ok(x,r));}
  @Get("categories/:id") @RequirePermission("asset.category.read") category(@Param("id") id:string,@Req() r:AuthenticatedRequest){return this.s.getCategory(r.auth,id).then(x=>ok(x,r));}
  @Post("categories/:id/update") @RequirePermission("asset.category.manage") updateCategory(@Param("id") id:string,@Body() b:any,@Headers("idempotency-key") k:string,@Req() r:AuthenticatedRequest){return this.s.updateCategory(r.auth,id,b,key(k),rid(r)).then(x=>ok(x,r));}
  @Post("categories/:id/activate") @RequirePermission("asset.category.manage") activateCategory(@Param("id") id:string,@Body() b:any,@Headers("idempotency-key") k:string,@Req() r:AuthenticatedRequest){return this.s.categoryStatus(r.auth,id,"ACTIVE",b,key(k),rid(r)).then(x=>ok(x,r));}
  @Post("categories/:id/retire") @RequirePermission("asset.category.manage") retireCategory(@Param("id") id:string,@Body() b:any,@Headers("idempotency-key") k:string,@Req() r:AuthenticatedRequest){return this.s.categoryStatus(r.auth,id,"RETIRED",b,key(k),rid(r)).then(x=>ok(x,r));}
  @Get("depreciation-policies") @RequirePermission("asset.policy.read") policies(@Req() r:AuthenticatedRequest){return this.s.listPolicies(r.auth).then(x=>ok(x,r));}
  @Post("depreciation-policies") @RequirePermission("asset.policy.manage") createPolicy(@Body() b:any,@Headers("idempotency-key") k:string,@Req() r:AuthenticatedRequest){return this.s.createPolicy(r.auth,b,key(k),rid(r)).then(x=>ok(x,r));}
  @Post("depreciation-policies/:id/activate") @RequirePermission("asset.policy.manage") activatePolicy(@Param("id") id:string,@Body() b:any,@Headers("idempotency-key") k:string,@Req() r:AuthenticatedRequest){return this.s.activatePolicy(r.auth,id,b,key(k),rid(r)).then(x=>ok(x,r));}

  @Get("candidates") @RequirePermission("asset.candidate.read") candidates(@Req() r:AuthenticatedRequest){return this.s.listCandidates(r.auth).then(x=>ok(x,r));}
  @Post("candidates") @RequirePermission("asset.candidate.create") createCandidate(@Body() b:any,@Headers("idempotency-key") k:string,@Req() r:AuthenticatedRequest){return this.s.createCandidate(r.auth,b,key(k),rid(r)).then(x=>ok(x,r));}
  @Get("candidates/:id") @RequirePermission("asset.candidate.read") candidate(@Param("id") id:string,@Req() r:AuthenticatedRequest){return this.s.getCandidate(r.auth,id).then(x=>ok(x,r));}
  @Post("candidates/:id/update") @RequirePermission("asset.candidate.create") updateCandidate(@Param("id") id:string,@Body() b:any,@Headers("idempotency-key") k:string,@Req() r:AuthenticatedRequest){return this.s.candidateStatus(r.auth,id,"PENDING_REVIEW",b,key(k),rid(r)).then(x=>ok(x,r));}
  @Post("candidates/:id/submit-review") @RequirePermission("asset.candidate.classify") submitCandidate(@Param("id") id:string,@Body() b:any,@Headers("idempotency-key") k:string,@Req() r:AuthenticatedRequest){return this.s.candidateStatus(r.auth,id,"PENDING_REVIEW",b,key(k),rid(r)).then(x=>ok(x,r));}
  @Post("candidates/:id/classify-expense") @RequirePermission("asset.candidate.classify") classifyExpense(@Param("id") id:string,@Body() b:any,@Headers("idempotency-key") k:string,@Req() r:AuthenticatedRequest){return this.s.candidateStatus(r.auth,id,"CLASSIFIED_EXPENSE",b,key(k),rid(r)).then(x=>ok(x,r));}
  @Post("candidates/:id/classify-inventory") @RequirePermission("asset.candidate.classify") classifyInventory(@Param("id") id:string,@Body() b:any,@Headers("idempotency-key") k:string,@Req() r:AuthenticatedRequest){return this.s.candidateStatus(r.auth,id,"CLASSIFIED_INVENTORY",b,key(k),rid(r)).then(x=>ok(x,r));}
  @Post("candidates/:id/request-capitalization") @RequirePermission("asset.candidate.classify") requestCandidateCap(@Param("id") id:string,@Body() b:any,@Headers("idempotency-key") k:string,@Req() r:AuthenticatedRequest){return this.s.candidateStatus(r.auth,id,"PENDING_CAPITALIZATION",b,key(k),rid(r)).then(x=>ok(x,r));}
  @Post("candidates/:id/approve-capitalization") @RequirePermission("asset.candidate.approve") approveCandidateCap(@Param("id") id:string,@Body() b:any,@Headers("idempotency-key") k:string,@Req() r:AuthenticatedRequest){return this.s.candidateStatus(r.auth,id,"APPROVED_FOR_CAPITALIZATION",b,key(k),rid(r)).then(x=>ok(x,r));}
  @Post("candidates/:id/reject") @RequirePermission("asset.candidate.classify") rejectCandidate(@Param("id") id:string,@Body() b:any,@Headers("idempotency-key") k:string,@Req() r:AuthenticatedRequest){return this.s.candidateStatus(r.auth,id,"REJECTED",b,key(k),rid(r)).then(x=>ok(x,r));}

  @Get("") @RequirePermission("asset.register.read") assets(@Req() r:AuthenticatedRequest){return this.s.listAssets(r.auth).then(x=>ok(x,r));}
  @Post("") @RequirePermission("asset.register.create") createAsset(@Body() b:any,@Headers("idempotency-key") k:string,@Req() r:AuthenticatedRequest){return this.s.createAsset(r.auth,b,key(k),rid(r)).then(x=>ok(x,r));}
  @Get("capitalization-requests") @RequirePermission("asset.capitalization.read") caps(@Req() r:AuthenticatedRequest){return this.s.listCapitalizations(r.auth).then(x=>ok(x,r));}
  @Post("capitalization-requests") @RequirePermission("asset.capitalization.create") createCap(@Body() b:any,@Headers("idempotency-key") k:string,@Req() r:AuthenticatedRequest){return this.s.createCapitalization(r.auth,b,key(k),rid(r)).then(x=>ok(x,r));}
  @Get("capitalization-requests/:id") @RequirePermission("asset.capitalization.read") cap(@Param("id") id:string,@Req() r:AuthenticatedRequest){return this.s.getCapitalization(r.auth,id).then(x=>ok(x,r));}
  @Post("capitalization-requests/:id/submit") @RequirePermission("asset.capitalization.create") submitCap(@Param("id") id:string,@Body() b:any,@Headers("idempotency-key") k:string,@Req() r:AuthenticatedRequest){return this.s.capitalizationStatus(r.auth,id,"PENDING_APPROVAL",b,key(k),rid(r)).then(x=>ok(x,r));}
  @Post("capitalization-requests/:id/approve") @RequirePermission("asset.capitalization.approve") approveCap(@Param("id") id:string,@Body() b:any,@Headers("idempotency-key") k:string,@Req() r:AuthenticatedRequest){return this.s.capitalizationStatus(r.auth,id,"APPROVED",b,key(k),rid(r)).then(x=>ok(x,r));}
  @Post("capitalization-requests/:id/process") @RequirePermission("asset.capitalization.process") processCap(@Param("id") id:string,@Body() b:any,@Headers("idempotency-key") k:string,@Req() r:AuthenticatedRequest){return this.s.capitalizationStatus(r.auth,id,"CAPITALIZED",b,key(k),rid(r)).then(x=>ok(x,r));}
  @Post("capitalization-requests/:id/reject") @RequirePermission("asset.capitalization.approve") rejectCap(@Param("id") id:string,@Body() b:any,@Headers("idempotency-key") k:string,@Req() r:AuthenticatedRequest){return this.s.capitalizationStatus(r.auth,id,"REJECTED",b,key(k),rid(r)).then(x=>ok(x,r));}

  @Get("depreciation-runs") @RequirePermission("asset.depreciation.read") runs(@Req() r:AuthenticatedRequest){return this.s.listDepreciationRuns(r.auth).then(x=>ok(x,r));}
  @Post("depreciation-runs") @RequirePermission("asset.depreciation.create") createRun(@Body() b:any,@Headers("idempotency-key") k:string,@Req() r:AuthenticatedRequest){return this.s.createDepreciationRun(r.auth,b,key(k),rid(r)).then(x=>ok(x,r));}
  @Get("depreciation-runs/:id") @RequirePermission("asset.depreciation.read") run(@Param("id") id:string,@Req() r:AuthenticatedRequest){return this.s.getDepreciationRun(r.auth,id).then(x=>ok(x,r));}
  @Post("depreciation-runs/:id/calculate") @RequirePermission("asset.depreciation.create") calculateRun(@Param("id") id:string,@Body() b:any,@Headers("idempotency-key") k:string,@Req() r:AuthenticatedRequest){return this.s.calculateDepreciation(r.auth,id,b,key(k),rid(r)).then(x=>ok(x,r));}
  @Post("depreciation-runs/:id/submit") @RequirePermission("asset.depreciation.create") submitRun(@Param("id") id:string,@Body() b:any,@Headers("idempotency-key") k:string,@Req() r:AuthenticatedRequest){return this.s.depreciationStatus(r.auth,id,"PENDING_APPROVAL",b,key(k),rid(r)).then(x=>ok(x,r));}
  @Post("depreciation-runs/:id/approve") @RequirePermission("asset.depreciation.approve") approveRun(@Param("id") id:string,@Body() b:any,@Headers("idempotency-key") k:string,@Req() r:AuthenticatedRequest){return this.s.depreciationStatus(r.auth,id,"APPROVED",b,key(k),rid(r)).then(x=>ok(x,r));}
  @Post("depreciation-runs/:id/post") @RequirePermission("asset.depreciation.post") postRun(@Param("id") id:string,@Body() b:any,@Headers("idempotency-key") k:string,@Req() r:AuthenticatedRequest){return this.s.depreciationStatus(r.auth,id,"POSTED",b,key(k),rid(r)).then(x=>ok(x,r));}
  @Get("depreciation-schedules") @RequirePermission("asset.depreciation.read") schedules(@Req() r:AuthenticatedRequest){return this.s.depreciationSchedules(r.auth,{}).then(x=>ok(x,r));}

  @Get("maintenance-plans") @RequirePermission("asset.maintenance.read") plans(@Req() r:AuthenticatedRequest){return this.s.listMaintenancePlans(r.auth).then(x=>ok(x,r));}
  @Post("maintenance-plans") @RequirePermission("asset.maintenance.create") createPlan(@Body() b:any,@Headers("idempotency-key") k:string,@Req() r:AuthenticatedRequest){return this.s.createMaintenancePlan(r.auth,b,key(k),rid(r)).then(x=>ok(x,r));}
  @Post("maintenance-plans/:id/activate") @RequirePermission("asset.maintenance.create") activatePlan(@Param("id") id:string,@Body() b:any,@Headers("idempotency-key") k:string,@Req() r:AuthenticatedRequest){return this.s.maintenancePlanStatus(r.auth,id,"ACTIVE",b,key(k),rid(r)).then(x=>ok(x,r));}
  @Post("maintenance-plans/:id/pause") @RequirePermission("asset.maintenance.create") pausePlan(@Param("id") id:string,@Body() b:any,@Headers("idempotency-key") k:string,@Req() r:AuthenticatedRequest){return this.s.maintenancePlanStatus(r.auth,id,"PAUSED",b,key(k),rid(r)).then(x=>ok(x,r));}
  @Post("maintenance-plans/:id/retire") @RequirePermission("asset.maintenance.cancel") retirePlan(@Param("id") id:string,@Body() b:any,@Headers("idempotency-key") k:string,@Req() r:AuthenticatedRequest){return this.s.maintenancePlanStatus(r.auth,id,"RETIRED",b,key(k),rid(r)).then(x=>ok(x,r));}
  @Get("maintenance-work-orders") @RequirePermission("asset.maintenance.read") workOrders(@Req() r:AuthenticatedRequest){return this.s.listWorkOrders(r.auth).then(x=>ok(x,r));}
  @Post("maintenance-work-orders") @RequirePermission("asset.maintenance.create") createWorkOrder(@Body() b:any,@Headers("idempotency-key") k:string,@Req() r:AuthenticatedRequest){return this.s.createWorkOrder(r.auth,b,key(k),rid(r)).then(x=>ok(x,r));}
  @Get("maintenance-work-orders/:id") @RequirePermission("asset.maintenance.read") workOrder(@Param("id") id:string,@Req() r:AuthenticatedRequest){return this.s.listWorkOrders(r.auth).then(x=>ok(x.find((w:any)=>w.id===id),r));}
  @Post("maintenance-work-orders/:id/schedule") @RequirePermission("asset.maintenance.create") scheduleWorkOrder(@Param("id") id:string,@Body() b:any,@Headers("idempotency-key") k:string,@Req() r:AuthenticatedRequest){return this.s.workOrderStatus(r.auth,id,"SCHEDULED",b,key(k),rid(r)).then(x=>ok(x,r));}
  @Post("maintenance-work-orders/:id/assign") @RequirePermission("asset.maintenance.assign") assignWorkOrder(@Param("id") id:string,@Body() b:any,@Headers("idempotency-key") k:string,@Req() r:AuthenticatedRequest){return this.s.workOrderStatus(r.auth,id,"ASSIGNED",b,key(k),rid(r)).then(x=>ok(x,r));}
  @Post("maintenance-work-orders/:id/start") @RequirePermission("asset.maintenance.execute") startWorkOrder(@Param("id") id:string,@Body() b:any,@Headers("idempotency-key") k:string,@Req() r:AuthenticatedRequest){return this.s.workOrderStatus(r.auth,id,"IN_PROGRESS",b,key(k),rid(r)).then(x=>ok(x,r));}
  @Post("maintenance-work-orders/:id/wait-parts") @RequirePermission("asset.maintenance.execute") waitParts(@Param("id") id:string,@Body() b:any,@Headers("idempotency-key") k:string,@Req() r:AuthenticatedRequest){return this.s.workOrderStatus(r.auth,id,"WAITING_PARTS",b,key(k),rid(r)).then(x=>ok(x,r));}
  @Post("maintenance-work-orders/:id/wait-vendor") @RequirePermission("asset.maintenance.execute") waitVendor(@Param("id") id:string,@Body() b:any,@Headers("idempotency-key") k:string,@Req() r:AuthenticatedRequest){return this.s.workOrderStatus(r.auth,id,"WAITING_VENDOR",b,key(k),rid(r)).then(x=>ok(x,r));}
  @Post("maintenance-work-orders/:id/complete") @RequirePermission("asset.maintenance.execute") completeWorkOrder(@Param("id") id:string,@Body() b:any,@Headers("idempotency-key") k:string,@Req() r:AuthenticatedRequest){return this.s.workOrderStatus(r.auth,id,"COMPLETED",b,key(k),rid(r)).then(x=>ok(x,r));}
  @Post("maintenance-work-orders/:id/verify") @RequirePermission("asset.maintenance.verify") verifyWorkOrder(@Param("id") id:string,@Body() b:any,@Headers("idempotency-key") k:string,@Req() r:AuthenticatedRequest){return this.s.workOrderStatus(r.auth,id,"VERIFIED",b,key(k),rid(r)).then(x=>ok(x,r));}
  @Post("maintenance-work-orders/:id/reopen") @RequirePermission("asset.maintenance.execute") reopenWorkOrder(@Param("id") id:string,@Body() b:any,@Headers("idempotency-key") k:string,@Req() r:AuthenticatedRequest){return this.s.workOrderStatus(r.auth,id,"REOPENED",b,key(k),rid(r)).then(x=>ok(x,r));}
  @Post("maintenance-work-orders/:id/cancel") @RequirePermission("asset.maintenance.cancel") cancelWorkOrder(@Param("id") id:string,@Body() b:any,@Headers("idempotency-key") k:string,@Req() r:AuthenticatedRequest){return this.s.workOrderStatus(r.auth,id,"CANCELLED",b,key(k),rid(r)).then(x=>ok(x,r));}
  @Get("warranties") @RequirePermission("asset.warranty.read") warranties(@Req() r:AuthenticatedRequest){return this.s.listWarranties(r.auth).then(x=>ok(x,r));}
  @Post(":assetId/warranties") @RequirePermission("asset.warranty.manage") createWarranty(@Param("assetId") id:string,@Body() b:any,@Headers("idempotency-key") k:string,@Req() r:AuthenticatedRequest){return this.s.createWarranty(r.auth,id,b,key(k),rid(r)).then(x=>ok(x,r));}

  @Get("transfers") @RequirePermission("asset.transfer.read") transfers(@Req() r:AuthenticatedRequest){return this.s.listTransfers(r.auth).then(x=>ok(x,r));}
  @Post("transfers") @RequirePermission("asset.transfer.create") createTransfer(@Body() b:any,@Headers("idempotency-key") k:string,@Req() r:AuthenticatedRequest){return this.s.createTransfer(r.auth,b,key(k),rid(r)).then(x=>ok(x,r));}
  @Post("transfers/:id/submit") @RequirePermission("asset.transfer.create") submitTransfer(@Param("id") id:string,@Body() b:any,@Headers("idempotency-key") k:string,@Req() r:AuthenticatedRequest){return this.s.transferStatus(r.auth,id,"PENDING_APPROVAL",b,key(k),rid(r)).then(x=>ok(x,r));}
  @Post("transfers/:id/approve") @RequirePermission("asset.transfer.approve") approveTransfer(@Param("id") id:string,@Body() b:any,@Headers("idempotency-key") k:string,@Req() r:AuthenticatedRequest){return this.s.transferStatus(r.auth,id,"APPROVED",b,key(k),rid(r)).then(x=>ok(x,r));}
  @Post("transfers/:id/dispatch") @RequirePermission("asset.transfer.dispatch") dispatchTransfer(@Param("id") id:string,@Body() b:any,@Headers("idempotency-key") k:string,@Req() r:AuthenticatedRequest){return this.s.transferStatus(r.auth,id,"DISPATCHED",b,key(k),rid(r)).then(x=>ok(x,r));}
  @Post("transfers/:id/receive") @RequirePermission("asset.transfer.receive") receiveTransfer(@Param("id") id:string,@Body() b:any,@Headers("idempotency-key") k:string,@Req() r:AuthenticatedRequest){return this.s.transferStatus(r.auth,id,"RECEIVED",b,key(k),rid(r)).then(x=>ok(x,r));}
  @Post("transfers/:id/reject") @RequirePermission("asset.transfer.approve") rejectTransfer(@Param("id") id:string,@Body() b:any,@Headers("idempotency-key") k:string,@Req() r:AuthenticatedRequest){return this.s.transferStatus(r.auth,id,"REJECTED",b,key(k),rid(r)).then(x=>ok(x,r));}
  @Post("transfers/:id/cancel") @RequirePermission("asset.transfer.create") cancelTransfer(@Param("id") id:string,@Body() b:any,@Headers("idempotency-key") k:string,@Req() r:AuthenticatedRequest){return this.s.transferStatus(r.auth,id,"CANCELLED",b,key(k),rid(r)).then(x=>ok(x,r));}
  @Get("count-sessions") @RequirePermission("asset.count.read") counts(@Req() r:AuthenticatedRequest){return this.s.listCounts(r.auth).then(x=>ok(x,r));}
  @Post("count-sessions") @RequirePermission("asset.count.create") createCount(@Body() b:any,@Headers("idempotency-key") k:string,@Req() r:AuthenticatedRequest){return this.s.createCount(r.auth,b,key(k),rid(r)).then(x=>ok(x,r));}
  @Post("count-sessions/:id/open") @RequirePermission("asset.count.create") openCount(@Param("id") id:string,@Body() b:any,@Headers("idempotency-key") k:string,@Req() r:AuthenticatedRequest){return this.s.countStatus(r.auth,id,"OPEN",b,key(k),rid(r)).then(x=>ok(x,r));}
  @Post("count-sessions/:id/record") @RequirePermission("asset.count.record") recordCount(@Param("id") id:string,@Body() b:any,@Headers("idempotency-key") k:string,@Req() r:AuthenticatedRequest){return this.s.recordCount(r.auth,id,b,key(k),rid(r)).then(x=>ok(x,r));}
  @Post("count-sessions/:id/submit-review") @RequirePermission("asset.count.record") reviewCount(@Param("id") id:string,@Body() b:any,@Headers("idempotency-key") k:string,@Req() r:AuthenticatedRequest){return this.s.countStatus(r.auth,id,"REVIEW",b,key(k),rid(r)).then(x=>ok(x,r));}
  @Post("count-sessions/:id/approve") @RequirePermission("asset.count.approve") approveCount(@Param("id") id:string,@Body() b:any,@Headers("idempotency-key") k:string,@Req() r:AuthenticatedRequest){return this.s.countStatus(r.auth,id,"APPROVED",b,key(k),rid(r)).then(x=>ok(x,r));}
  @Post("count-sessions/:id/close") @RequirePermission("asset.count.approve") closeCount(@Param("id") id:string,@Body() b:any,@Headers("idempotency-key") k:string,@Req() r:AuthenticatedRequest){return this.s.countStatus(r.auth,id,"CLOSED",b,key(k),rid(r)).then(x=>ok(x,r));}
  @Get("inspections") @RequirePermission("asset.inspection.read") inspections(@Req() r:AuthenticatedRequest){return this.s.listInspections(r.auth).then(x=>ok(x,r));}
  @Post("inspections") @RequirePermission("asset.inspection.create") createInspection(@Body() b:any,@Headers("idempotency-key") k:string,@Req() r:AuthenticatedRequest){return this.s.createInspection(r.auth,b,key(k),rid(r)).then(x=>ok(x,r));}
  @Post("inspections/:id/start") @RequirePermission("asset.inspection.execute") startInspection(@Param("id") id:string,@Body() b:any,@Headers("idempotency-key") k:string,@Req() r:AuthenticatedRequest){return this.s.inspectionStatus(r.auth,id,"IN_PROGRESS",b,key(k),rid(r)).then(x=>ok(x,r));}
  @Post("inspections/:id/pass") @RequirePermission("asset.inspection.execute") passInspection(@Param("id") id:string,@Body() b:any,@Headers("idempotency-key") k:string,@Req() r:AuthenticatedRequest){return this.s.inspectionStatus(r.auth,id,"PASSED",b,key(k),rid(r)).then(x=>ok(x,r));}
  @Post("inspections/:id/fail") @RequirePermission("asset.inspection.execute") failInspection(@Param("id") id:string,@Body() b:any,@Headers("idempotency-key") k:string,@Req() r:AuthenticatedRequest){return this.s.inspectionStatus(r.auth,id,"FAILED",b,key(k),rid(r)).then(x=>ok(x,r));}
  @Post("inspections/:id/create-maintenance") @RequirePermission("asset.inspection.approve") maintenanceInspection(@Param("id") id:string,@Body() b:any,@Headers("idempotency-key") k:string,@Req() r:AuthenticatedRequest){return this.s.inspectionStatus(r.auth,id,"REQUIRES_MAINTENANCE",b,key(k),rid(r)).then(x=>ok(x,r));}
  @Get("impairments") @RequirePermission("asset.impairment.read") impairments(@Req() r:AuthenticatedRequest){return this.s.listImpairments(r.auth).then(x=>ok(x,r));}
  @Post("impairments") @RequirePermission("asset.impairment.create") createImpairment(@Body() b:any,@Headers("idempotency-key") k:string,@Req() r:AuthenticatedRequest){return this.s.createImpairment(r.auth,b,key(k),rid(r)).then(x=>ok(x,r));}
  @Post("impairments/:id/submit") @RequirePermission("asset.impairment.create") submitImpairment(@Param("id") id:string,@Body() b:any,@Headers("idempotency-key") k:string,@Req() r:AuthenticatedRequest){return this.s.impairmentStatus(r.auth,id,"PENDING_APPROVAL",b,key(k),rid(r)).then(x=>ok(x,r));}
  @Post("impairments/:id/approve") @RequirePermission("asset.impairment.approve") approveImpairment(@Param("id") id:string,@Body() b:any,@Headers("idempotency-key") k:string,@Req() r:AuthenticatedRequest){return this.s.impairmentStatus(r.auth,id,"APPROVED",b,key(k),rid(r)).then(x=>ok(x,r));}
  @Post("impairments/:id/post") @RequirePermission("asset.impairment.post") postImpairment(@Param("id") id:string,@Body() b:any,@Headers("idempotency-key") k:string,@Req() r:AuthenticatedRequest){return this.s.impairmentStatus(r.auth,id,"POSTED",b,key(k),rid(r)).then(x=>ok(x,r));}
  @Get("capital-improvements") @RequirePermission("asset.improvement.read") improvements(@Req() r:AuthenticatedRequest){return this.s.listImprovements(r.auth).then(x=>ok(x,r));}
  @Post("capital-improvements") @RequirePermission("asset.improvement.create") createImprovement(@Body() b:any,@Headers("idempotency-key") k:string,@Req() r:AuthenticatedRequest){return this.s.createImprovement(r.auth,b,key(k),rid(r)).then(x=>ok(x,r));}
  @Post("capital-improvements/:id/submit") @RequirePermission("asset.improvement.create") submitImprovement(@Param("id") id:string,@Body() b:any,@Headers("idempotency-key") k:string,@Req() r:AuthenticatedRequest){return this.s.improvementStatus(r.auth,id,"PENDING_APPROVAL",b,key(k),rid(r)).then(x=>ok(x,r));}
  @Post("capital-improvements/:id/approve") @RequirePermission("asset.improvement.approve") approveImprovement(@Param("id") id:string,@Body() b:any,@Headers("idempotency-key") k:string,@Req() r:AuthenticatedRequest){return this.s.improvementStatus(r.auth,id,"APPROVED",b,key(k),rid(r)).then(x=>ok(x,r));}
  @Post("capital-improvements/:id/capitalize") @RequirePermission("asset.improvement.capitalize") capitalizeImprovement(@Param("id") id:string,@Body() b:any,@Headers("idempotency-key") k:string,@Req() r:AuthenticatedRequest){return this.s.improvementStatus(r.auth,id,"CAPITALIZED",b,key(k),rid(r)).then(x=>ok(x,r));}
  @Get("disposals") @RequirePermission("asset.disposal.read") disposals(@Req() r:AuthenticatedRequest){return this.s.listDisposals(r.auth).then(x=>ok(x,r));}
  @Post("disposals") @RequirePermission("asset.disposal.create") createDisposal(@Body() b:any,@Headers("idempotency-key") k:string,@Req() r:AuthenticatedRequest){return this.s.createDisposal(r.auth,b,key(k),rid(r)).then(x=>ok(x,r));}
  @Post("disposals/:id/submit") @RequirePermission("asset.disposal.create") submitDisposal(@Param("id") id:string,@Body() b:any,@Headers("idempotency-key") k:string,@Req() r:AuthenticatedRequest){return this.s.disposalStatus(r.auth,id,"PENDING_APPROVAL",b,key(k),rid(r)).then(x=>ok(x,r));}
  @Post("disposals/:id/approve") @RequirePermission("asset.disposal.approve") approveDisposal(@Param("id") id:string,@Body() b:any,@Headers("idempotency-key") k:string,@Req() r:AuthenticatedRequest){return this.s.disposalStatus(r.auth,id,"APPROVED",b,key(k),rid(r)).then(x=>ok(x,r));}
  @Post("disposals/:id/complete") @RequirePermission("asset.disposal.complete") completeDisposal(@Param("id") id:string,@Body() b:any,@Headers("idempotency-key") k:string,@Req() r:AuthenticatedRequest){return this.s.disposalStatus(r.auth,id,"COMPLETED",b,key(k),rid(r)).then(x=>ok(x,r));}
  @Post("disposals/:id/cancel") @RequirePermission("asset.disposal.create") cancelDisposal(@Param("id") id:string,@Body() b:any,@Headers("idempotency-key") k:string,@Req() r:AuthenticatedRequest){return this.s.disposalStatus(r.auth,id,"CANCELLED",b,key(k),rid(r)).then(x=>ok(x,r));}
  @Get("opening-imports") @RequirePermission("asset.register.create") imports(@Req() r:AuthenticatedRequest){return this.s.listOpeningImports(r.auth).then(x=>ok(x,r));}
  @Post("opening-imports") @RequirePermission("asset.register.create") createImport(@Body() b:any,@Headers("idempotency-key") k:string,@Req() r:AuthenticatedRequest){return this.s.createOpeningImport(r.auth,b,key(k),rid(r)).then(x=>ok(x,r));}
  @Post("opening-imports/:id/validate") @RequirePermission("asset.register.create") validateImport(@Param("id") id:string,@Body() b:any,@Headers("idempotency-key") k:string,@Req() r:AuthenticatedRequest){return this.s.openingImportStatus(r.auth,id,"VALIDATED",b,key(k),rid(r)).then(x=>ok(x,r));}
  @Post("opening-imports/:id/submit") @RequirePermission("asset.register.create") submitImport(@Param("id") id:string,@Body() b:any,@Headers("idempotency-key") k:string,@Req() r:AuthenticatedRequest){return this.s.openingImportStatus(r.auth,id,"PENDING_APPROVAL",b,key(k),rid(r)).then(x=>ok(x,r));}
  @Post("opening-imports/:id/approve") @RequirePermission("asset.capitalization.approve") approveImport(@Param("id") id:string,@Body() b:any,@Headers("idempotency-key") k:string,@Req() r:AuthenticatedRequest){return this.s.openingImportStatus(r.auth,id,"APPROVED",b,key(k),rid(r)).then(x=>ok(x,r));}
  @Post("opening-imports/:id/process") @RequirePermission("asset.capitalization.process") processImport(@Param("id") id:string,@Body() b:any,@Headers("idempotency-key") k:string,@Req() r:AuthenticatedRequest){return this.s.openingImportStatus(r.auth,id,"PROCESSED",b,key(k),rid(r)).then(x=>ok(x,r));}
  @Get("reports/register") @RequirePermission("asset.report.read") registerReport(@Req() r:AuthenticatedRequest,@Query() q:any){return this.s.report(r.auth,"register",q).then(x=>ok(x,r));}
  @Get("reports/depreciation") @RequirePermission("asset.report.read") depreciationReport(@Req() r:AuthenticatedRequest,@Query() q:any){return this.s.report(r.auth,"depreciation",q).then(x=>ok(x,r));}
  @Get("reports/depreciation-forecast") @RequirePermission("asset.report.read") depreciationForecast(@Req() r:AuthenticatedRequest,@Query() q:any){return this.s.report(r.auth,"depreciation",q).then(x=>ok(x,r));}
  @Get("reports/net-book-value") @RequirePermission("asset.report.read") nbvReport(@Req() r:AuthenticatedRequest,@Query() q:any){return this.s.report(r.auth,"net-book-value",q).then(x=>ok(x,r));}
  @Get("reports/maintenance-due") @RequirePermission("asset.report.read") dueReport(@Req() r:AuthenticatedRequest,@Query() q:any){return this.s.report(r.auth,"maintenance-due",q).then(x=>ok(x,r));}
  @Get("reports/maintenance-cost") @RequirePermission("asset.report.read") maintenanceCost(@Req() r:AuthenticatedRequest,@Query() q:any){return this.s.report(r.auth,"maintenance-due",q).then(x=>ok(x,r));}
  @Get("reports/downtime") @RequirePermission("asset.report.read") downtime(@Req() r:AuthenticatedRequest,@Query() q:any){return this.s.report(r.auth,"maintenance-due",q).then(x=>ok(x,r));}
  @Get("reports/warranty-expiry") @RequirePermission("asset.report.read") warrantyExpiry(@Req() r:AuthenticatedRequest,@Query() q:any){return this.s.report(r.auth,"warranty-expiry",q).then(x=>ok(x,r));}
  @Get("reports/transfer-history") @RequirePermission("asset.report.read") transferReport(@Req() r:AuthenticatedRequest,@Query() q:any){return this.s.listTransfers(r.auth).then(x=>ok(x,r));}
  @Get("reports/count-discrepancies") @RequirePermission("asset.report.read") countReport(@Req() r:AuthenticatedRequest){return this.s.listCounts(r.auth).then(x=>ok(x,r));}
  @Get("reports/impairment") @RequirePermission("asset.report.read") impairmentReport(@Req() r:AuthenticatedRequest){return this.s.report(r.auth,"impairment",{}).then(x=>ok(x,r));}
  @Get("reports/disposal") @RequirePermission("asset.report.read") disposalReport(@Req() r:AuthenticatedRequest){return this.s.report(r.auth,"disposal",{}).then(x=>ok(x,r));}
  @Get("reports/capex") @RequirePermission("asset.report.read") capexReport(@Req() r:AuthenticatedRequest){return this.s.report(r.auth,"capex",{}).then(x=>ok(x,r));}
  @Get("reports/gl-reconciliation") @RequirePermission("asset.report.read") glReport(@Req() r:AuthenticatedRequest){return this.s.report(r.auth,"register",{}).then(x=>ok(x,r));}
  @Get("reports/procurement-reconciliation") @RequirePermission("asset.report.read") procurementReport(@Req() r:AuthenticatedRequest){return this.s.report(r.auth,"register",{}).then(x=>ok(x,r));}
  @Post("exports") @RequirePermission("asset.export") createExport(@Body() b:any,@Headers("idempotency-key") k:string,@Req() r:AuthenticatedRequest){return this.s.createExport(r.auth,b,key(k),rid(r)).then(x=>ok(x,r));}
  @Get("exports/:id") @RequirePermission("asset.export") exportJob(@Param("id") id:string,@Req() r:AuthenticatedRequest){return this.s.getExport(r.auth,id).then(x=>ok(x,r));}
  @Get(":assetId") @RequirePermission("asset.register.read") asset(@Param("assetId") id:string,@Req() r:AuthenticatedRequest){return this.s.getAsset(r.auth,id).then(x=>ok(x,r));}
  @Post(":assetId/activate") @RequirePermission("asset.register.manage") activateAsset(@Param("assetId") id:string,@Body() b:any,@Headers("idempotency-key") k:string,@Req() r:AuthenticatedRequest){return this.s.assetStatus(r.auth,id,"ACTIVE",b,key(k),rid(r)).then(x=>ok(x,r));}
  @Post(":assetId/set-idle") @RequirePermission("asset.register.manage") idleAsset(@Param("assetId") id:string,@Body() b:any,@Headers("idempotency-key") k:string,@Req() r:AuthenticatedRequest){return this.s.assetStatus(r.auth,id,"IDLE",b,key(k),rid(r)).then(x=>ok(x,r));}
  @Post(":assetId/request-retirement") @RequirePermission("asset.disposal.create") retireAsset(@Param("assetId") id:string,@Body() b:any,@Headers("idempotency-key") k:string,@Req() r:AuthenticatedRequest){return this.s.assetStatus(r.auth,id,"RETIRED",b,key(k),rid(r)).then(x=>ok(x,r));}
  @Get(":assetId/history") @RequirePermission("asset.register.read") history(@Param("assetId") id:string,@Req() r:AuthenticatedRequest){return this.s.assetHistory(r.auth,id).then(x=>ok(x,r));}
  @Get(":assetId/depreciation") @RequirePermission("asset.depreciation.read") depreciation(@Param("assetId") id:string,@Req() r:AuthenticatedRequest){return this.s.report(r.auth,"depreciation",{assetId:id}).then(x=>ok(x,r));}
  @Get(":assetId/maintenance") @RequirePermission("asset.maintenance.read") maintenance(@Param("assetId") id:string,@Req() r:AuthenticatedRequest){return this.s.listWorkOrders(r.auth).then(x=>ok(x.filter((w:any)=>w.asset_id===id),r));}
  @Get(":assetId/warranty") @RequirePermission("asset.warranty.read") warranty(@Param("assetId") id:string,@Req() r:AuthenticatedRequest){return this.s.listWarranties(r.auth,id).then(x=>ok(x,r));}
}
