/* eslint-disable @typescript-eslint/no-explicit-any, @typescript-eslint/no-unused-vars */
import { BadRequestException, ConflictException, ForbiddenException, Inject, Injectable, NotFoundException } from "@nestjs/common";
import { createHash, randomUUID } from "node:crypto";
import type { PoolClient } from "pg";
import { DatabaseService } from "../../infrastructure/database.service.js";
import type { AccessClaims } from "../identity/auth.types.js";

const fp = (v: unknown) => createHash("sha256").update(JSON.stringify(v ?? {})).digest("hex");
const required = (v: unknown, code: string) => { if (typeof v !== "string" || !v.trim()) throw new BadRequestException({ code: `${code.toUpperCase()}_REQUIRED` }); return v.trim(); };
const money = (v: unknown, code = "AMOUNT") => { try { const n = BigInt(String(v)); if (n < 0n) throw new Error(); return n; } catch { throw new BadRequestException({ code: `${code}_INVALID` }); } };

const transitions: any = {
  candidate: { PENDING_REVIEW: ["DRAFT"], CLASSIFIED_EXPENSE: ["PENDING_REVIEW"], CLASSIFIED_INVENTORY: ["PENDING_REVIEW"], PENDING_CAPITALIZATION: ["PENDING_REVIEW"], APPROVED_FOR_CAPITALIZATION: ["PENDING_CAPITALIZATION"], CAPITALIZED: ["APPROVED_FOR_CAPITALIZATION"], REJECTED: ["PENDING_REVIEW","PENDING_CAPITALIZATION"], CANCELLED: ["DRAFT"] },
  capitalization: { PENDING_APPROVAL: ["DRAFT"], APPROVED: ["PENDING_APPROVAL"], PROCESSING: ["APPROVED"], CAPITALIZED: ["PROCESSING"], REJECTED: ["PENDING_APPROVAL"], CANCELLED: ["DRAFT"] },
  depreciation: { CALCULATING: ["DRAFT"], READY: ["CALCULATING"], PENDING_APPROVAL: ["READY"], APPROVED: ["PENDING_APPROVAL"], POSTING: ["APPROVED"], POSTED: ["POSTING"], REVERSED: ["POSTED"], FAILED: ["CALCULATING","POSTING"] },
  maintenancePlan: { ACTIVE: ["DRAFT","PAUSED"], PAUSED: ["ACTIVE"], RETIRED: ["DRAFT","ACTIVE","PAUSED"] },
  workOrder: { SCHEDULED: ["DRAFT","REOPENED"], ASSIGNED: ["SCHEDULED"], IN_PROGRESS: ["ASSIGNED","SCHEDULED"], WAITING_PARTS: ["IN_PROGRESS"], WAITING_VENDOR: ["IN_PROGRESS"], COMPLETED: ["IN_PROGRESS","WAITING_PARTS","WAITING_VENDOR"], VERIFIED: ["COMPLETED"], REOPENED: ["COMPLETED","VERIFIED"], CANCELLED: ["DRAFT","SCHEDULED","ASSIGNED"] },
  transfer: { PENDING_APPROVAL: ["DRAFT"], APPROVED: ["PENDING_APPROVAL"], DISPATCHED: ["APPROVED"], IN_TRANSIT: ["DISPATCHED"], RECEIVED: ["IN_TRANSIT"], REJECTED: ["PENDING_APPROVAL"], CANCELLED: ["DRAFT","PENDING_APPROVAL"] },
  count: { OPEN: ["DRAFT"], COUNTING: ["OPEN"], REVIEW: ["COUNTING"], APPROVED: ["REVIEW"], CLOSED: ["APPROVED"], CANCELLED: ["DRAFT","OPEN"] },
  inspection: { SCHEDULED: ["DRAFT"], IN_PROGRESS: ["SCHEDULED"], PASSED: ["IN_PROGRESS"], FAILED: ["IN_PROGRESS"], REQUIRES_MAINTENANCE: ["FAILED"] },
  impairment: { PENDING_REVIEW: ["DRAFT"], PENDING_APPROVAL: ["PENDING_REVIEW"], APPROVED: ["PENDING_APPROVAL"], POSTING: ["APPROVED"], POSTED: ["POSTING"], REVERSED: ["POSTED"], REJECTED: ["PENDING_REVIEW"] },
  improvement: { PENDING_APPROVAL: ["DRAFT"], APPROVED: ["PENDING_APPROVAL"], CAPITALIZED: ["APPROVED"] },
  disposal: { PENDING_APPROVAL: ["DRAFT"], APPROVED: ["PENDING_APPROVAL"], PROCESSING: ["APPROVED"], COMPLETED: ["PROCESSING"], CANCELLED: ["DRAFT","PENDING_APPROVAL"] },
  import: { VALIDATED: ["UPLOADED"], PENDING_APPROVAL: ["VALIDATED"], APPROVED: ["PENDING_APPROVAL"], PROCESSING: ["APPROVED"], PROCESSED: ["PROCESSING"], REJECTED: ["VALIDATED"] },
};

@Injectable()
export class AssetsService {
  constructor(@Inject(DatabaseService) private readonly db: DatabaseService) {}
  private guard(auth: AccessClaims) { if (!auth.tenantId) throw new ForbiddenException({ code: "TENANT_SCOPE_REQUIRED" }); }
  private scope(auth: AccessClaims, branchId?: string | null) { this.guard(auth); if (branchId && auth.branchIds.length && !auth.branchIds.includes(branchId) && !auth.roles.includes("SALON_OWNER") && !auth.roles.includes("ACCOUNTANT")) throw new ForbiddenException({ code: "ASSET_BRANCH_SCOPE_DENIED" }); }
  private async audit(c: PoolClient, auth: AccessClaims, action: string, type: string, id: string, before: unknown, after: unknown, requestId: string, reason?: string) { await c.query(`INSERT INTO audit_logs(tenant_id,branch_id,actor_user_id,action,entity_type,entity_id,before_json,after_json,reason,request_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)`, [auth.tenantId, null, auth.userId, action, type, id, before == null ? null : JSON.stringify(before), after == null ? null : JSON.stringify(after), reason ?? null, requestId]); }
  private async event(c: PoolClient, auth: AccessClaims, eventType: string, aggregateType: string, aggregateId: string, payload: unknown, requestId: string) { await c.query(`INSERT INTO outbox_events(tenant_id,event_type,aggregate_type,aggregate_id,payload_json,actor_json,metadata_json) VALUES($1,$2,$3,$4,$5,$6,$7)`, [auth.tenantId,eventType,aggregateType,aggregateId,JSON.stringify(payload ?? {}),JSON.stringify({ type:"USER", id:auth.userId }),JSON.stringify({ requestId, schemaVersion:1 })]); }
  private async idem<T>(c: PoolClient, auth: AccessClaims, operation: string, key: string, input: unknown, work: () => Promise<T>): Promise<T> { if (!key) return work(); const hash = fp(input); const ins = await c.query<any>(`INSERT INTO asset_command_idempotency(tenant_id,operation,idempotency_key,request_fingerprint) VALUES($1,$2,$3,$4) ON CONFLICT DO NOTHING RETURNING id`, [auth.tenantId,operation,key,hash]); if (!ins.rows[0]) { const old = (await c.query<any>(`SELECT * FROM asset_command_idempotency WHERE tenant_id=$1 AND operation=$2 AND idempotency_key=$3 FOR UPDATE`, [auth.tenantId,operation,key])).rows[0]; if (old.request_fingerprint !== hash) throw new ConflictException({ code:"IDEMPOTENCY_KEY_REUSED" }); if (old.response_json) return old.response_json as T; throw new ConflictException({ code:"IDEMPOTENCY_REQUEST_IN_PROGRESS" }); } const result = await work(); await c.query(`UPDATE asset_command_idempotency SET state='COMPLETED',response_json=$4 WHERE tenant_id=$1 AND operation=$2 AND idempotency_key=$3`, [auth.tenantId,operation,key,JSON.stringify(result)]); return result; }
  private async moduleStatus(auth: AccessClaims) { const r = await this.db.query<any>(`SELECT * FROM asset_module_configurations WHERE tenant_id=$1`, [auth.tenantId]); return r.rows[0] ?? { tenant_id: auth.tenantId, status:"DISABLED" }; }
  private async requireActive(auth: AccessClaims) { const x = await this.moduleStatus(auth); if (x.status !== "ACTIVE") throw new ConflictException({ code:"ASSET_MODULE_NOT_CONFIGURED" }); }

  async readiness(auth: AccessClaims) { this.guard(auth); const c = await this.db.query<any>(`SELECT * FROM asset_module_configurations WHERE tenant_id=$1`, [auth.tenantId]); const checks = await this.db.query<any>(`SELECT * FROM asset_configuration_checklists WHERE tenant_id=$1 ORDER BY item_code`, [auth.tenantId]); return { configuration: c.rows[0] ?? { status:"DISABLED" }, checks: checks.rows, ready: checks.rows.length > 0 && checks.rows.every((x: any) => x.status === "READY") }; }
  async activateConfiguration(auth: AccessClaims, input: any, key: string, requestId: string) { this.guard(auth); return this.db.transaction(async c => this.idem(c,auth,"configuration.activate",key,input,async()=>{ const ready = (await c.query<any>(`SELECT count(*) filter(where status<>'READY') pending,count(*) total FROM asset_configuration_checklists WHERE tenant_id=$1`,[auth.tenantId])).rows[0]; if (Number(ready.total)===0 || Number(ready.pending)>0) throw new ConflictException({code:"ASSET_CONFIGURATION_INCOMPLETE"}); const r=await c.query<any>(`INSERT INTO asset_module_configurations(tenant_id,status,cutover_date,updated_by_user_id) VALUES($1,'ACTIVE',$2,$3) ON CONFLICT(tenant_id) DO UPDATE SET status='ACTIVE',cutover_date=EXCLUDED.cutover_date,version=asset_module_configurations.version+1,updated_by_user_id=EXCLUDED.updated_by_user_id,updated_at=now() RETURNING *`,[auth.tenantId,input?.cutoverDate ?? new Date().toISOString().slice(0,10),auth.userId]); await this.audit(c,auth,"asset.configuration_activated","asset_module_configuration",auth.tenantId,null,r.rows[0],requestId); return r.rows[0]; })); }
  async disableConfiguration(auth: AccessClaims, input: any, key: string, requestId: string) { this.guard(auth); return this.db.transaction(async c=>this.idem(c,auth,"configuration.disable",key,input,async()=>{ const r=await c.query<any>(`UPDATE asset_module_configurations SET status='DISABLED',version=version+1,updated_by_user_id=$2,updated_at=now() WHERE tenant_id=$1 RETURNING *`,[auth.tenantId,auth.userId]); return r.rows[0] ?? {tenant_id:auth.tenantId,status:"DISABLED"}; })); }

  async listCategories(auth: AccessClaims) { this.guard(auth); return (await this.db.query<any>(`SELECT * FROM asset_categories WHERE tenant_id=$1 ORDER BY code`,[auth.tenantId])).rows; }
  async createCategory(auth: AccessClaims,input:any,key:string,requestId:string) { this.guard(auth); return this.db.transaction(async c=>this.idem(c,auth,"category.create",key,input,async()=>{ const code=required(input?.code,"category_code"); const name=required(input?.name,"category_name"); const r=await c.query<any>(`INSERT INTO asset_categories(tenant_id,parent_id,code,name,description,created_by_user_id) VALUES($1,$2,$3,$4,$5,$6) RETURNING *`,[auth.tenantId,input?.parentId??null,code,name,input?.description??null,auth.userId]); await this.audit(c,auth,"asset.category_created","asset_category",r.rows[0].id,null,r.rows[0],requestId); return r.rows[0]; })); }
  async getCategory(auth: AccessClaims,id:string) { this.guard(auth); const r=await this.db.query<any>(`SELECT * FROM asset_categories WHERE tenant_id=$1 AND id=$2`,[auth.tenantId,id]); if(!r.rows[0]) throw new NotFoundException({code:"ASSET_CATEGORY_NOT_FOUND"}); return r.rows[0]; }
  async updateCategory(auth: AccessClaims,id:string,input:any,key:string,requestId:string) { this.guard(auth); return this.db.transaction(async c=>this.idem(c,auth,"category.update",key,{id,...input},async()=>{ const old=(await c.query<any>(`SELECT * FROM asset_categories WHERE tenant_id=$1 AND id=$2 FOR UPDATE`,[auth.tenantId,id])).rows[0]; if(!old) throw new NotFoundException({code:"ASSET_CATEGORY_NOT_FOUND"}); if(input?.version!=null&&Number(input.version)!==old.version) throw new ConflictException({code:"VERSION_CONFLICT"}); const n=(await c.query<any>(`UPDATE asset_categories SET name=COALESCE($3,name),description=COALESCE($4,description),version=version+1,updated_at=now() WHERE tenant_id=$1 AND id=$2 RETURNING *`,[auth.tenantId,id,input?.name??null,input?.description??null])).rows[0]; await this.audit(c,auth,"asset.category_updated","asset_category",id,old,n,requestId); return n; })); }
  async categoryStatus(auth:AccessClaims,id:string,target:string,input:any,key:string,requestId:string) { return this.db.transaction(async c=>this.idem(c,auth,`category.${target.toLowerCase()}`,key,{id,...input},async()=>{ const old=(await c.query<any>(`SELECT * FROM asset_categories WHERE tenant_id=$1 AND id=$2 FOR UPDATE`,[auth.tenantId,id])).rows[0]; if(!old) throw new NotFoundException({code:"ASSET_CATEGORY_NOT_FOUND"}); if(input?.version!=null&&Number(input.version)!==old.version) throw new ConflictException({code:"VERSION_CONFLICT"}); const n=(await c.query<any>(`UPDATE asset_categories SET active=$3,version=version+1,updated_at=now() WHERE tenant_id=$1 AND id=$2 RETURNING *`,[auth.tenantId,id,target==='ACTIVE'])).rows[0]; await this.audit(c,auth,"asset.category_status_changed","asset_category",id,old,n,requestId,input?.reason); return n; })); }
  async listPolicies(auth:AccessClaims) { this.guard(auth); return (await this.db.query<any>(`SELECT * FROM asset_depreciation_policies WHERE tenant_id=$1 ORDER BY effective_from DESC,version_no DESC`,[auth.tenantId])).rows; }
  async createPolicy(auth:AccessClaims,input:any,key:string,requestId:string) { this.guard(auth); return this.db.transaction(async c=>this.idem(c,auth,"policy.create",key,input,async()=>{ const method=required(input?.method,"depreciation_method").toUpperCase(); const life=Number(input?.usefulLifePeriods); if(!Number.isInteger(life)||life<=0) throw new BadRequestException({code:"USEFUL_LIFE_INVALID"}); const data={...input,method,usefulLifePeriods:life}; const r=await c.query<any>(`INSERT INTO asset_depreciation_policies(tenant_id,category_id,version_no,state,method,convention,useful_life_periods,residual_value_minor,rate_numerator,rate_denominator,expected_units,effective_from,effective_to,fingerprint,created_by_user_id) VALUES($1,$2,COALESCE($3,1),'DRAFT',$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14) RETURNING *`,[auth.tenantId,input?.categoryId??null,input?.versionNo,method,input?.convention??"FULL_MONTH",life,money(input?.residualValueMinor??0).toString(),input?.rateNumerator??null,input?.rateDenominator??null,input?.expectedUnits??null,input?.effectiveFrom??new Date().toISOString().slice(0,10),input?.effectiveTo??null,fp(data),auth.userId]); return r.rows[0]; })); }
  async activatePolicy(auth:AccessClaims,id:string,input:any,key:string,requestId:string) { return this.db.transaction(async c=>this.idem(c,auth,"policy.activate",key,{id,...input},async()=>{ const old=(await c.query<any>(`SELECT * FROM asset_depreciation_policies WHERE tenant_id=$1 AND id=$2 FOR UPDATE`,[auth.tenantId,id])).rows[0]; if(!old) throw new NotFoundException({code:"ASSET_POLICY_NOT_FOUND"}); await c.query(`UPDATE asset_depreciation_policies SET state='SUPERSEDED' WHERE tenant_id=$1 AND category_id IS NOT DISTINCT FROM $2 AND state='ACTIVE'`,[auth.tenantId,old.category_id]); const n=(await c.query<any>(`UPDATE asset_depreciation_policies SET state='ACTIVE' WHERE tenant_id=$1 AND id=$2 RETURNING *`,[auth.tenantId,id])).rows[0]; await this.audit(c,auth,"asset.policy_activated","asset_depreciation_policy",id,old,n,requestId); return n; })); }

  async listCandidates(auth:AccessClaims) { this.guard(auth); this.scope(auth); return (await this.db.query<any>(`SELECT * FROM asset_candidates WHERE tenant_id=$1 AND ($2::uuid[] IS NULL OR branch_id=ANY($2::uuid[])) ORDER BY created_at DESC`,[auth.tenantId,auth.branchIds.length?auth.branchIds:null])).rows; }
  async getCandidate(auth:AccessClaims,id:string) { this.guard(auth); const r=await this.db.query<any>(`SELECT * FROM asset_candidates WHERE tenant_id=$1 AND id=$2`,[auth.tenantId,id]); if(!r.rows[0]) throw new NotFoundException({code:"ASSET_CANDIDATE_NOT_FOUND"}); this.scope(auth,r.rows[0].branch_id); return r.rows[0]; }
  async createCandidate(auth:AccessClaims,input:any,key:string,requestId:string) { this.guard(auth); this.scope(auth,input?.branchId); return this.db.transaction(async c=>this.idem(c,auth,"candidate.create",key,input,async()=>{ await this.requireActive(auth); const eligible=money(input?.eligibleAmountMinor??input?.amountMinor,"ELIGIBLE_AMOUNT"); const sourceType=required(input?.sourceType,"source_type"); const sourceId=required(input?.sourceId,"source_id"); const generation=Number(input?.generation??1); const dup=await c.query(`SELECT 1 FROM asset_candidate_source_allocations WHERE tenant_id=$1 AND source_type=$2 AND source_id=$3 AND generation=$4`,[auth.tenantId,sourceType,sourceId,generation]); if(dup.rowCount) throw new ConflictException({code:"ASSET_CANDIDATE_SOURCE_DUPLICATE"}); const id=randomUUID(); const n=(await c.query<any>(`INSERT INTO asset_candidates(id,tenant_id,branch_id,candidate_number,status,name,description,currency,eligible_amount_minor,source_fingerprint,source_version,requested_by_user_id) VALUES($1,$2,$3,'AC-'||substr($1::text,1,8),'DRAFT',$4,$5,$6,$7,$8,$9,$10) RETURNING *`,[id,auth.tenantId,input.branchId,input.name??"Asset candidate",input.description??null,required(input.currency??"VND","currency").toUpperCase(),eligible.toString(),input?.sourceFingerprint??fp(input),input?.sourceVersion??1,auth.userId])).rows[0]; await c.query(`INSERT INTO asset_candidate_source_allocations(tenant_id,candidate_id,source_type,source_id,source_line_id,generation,eligible_amount_minor,allocated_amount_minor,fingerprint) VALUES($1,$2,$3,$4,$5,$6,$7,0,$8)`,[auth.tenantId,id,sourceType,sourceId,input?.sourceLineId??null,generation,eligible.toString(),fp(input)]); await this.audit(c,auth,"asset.candidate_created","asset_candidate",id,null,n,requestId); await this.event(c,auth,"asset.candidate_created","asset_candidate",id,{ candidateId:id },requestId); return n; })); }
  async candidateStatus(auth:AccessClaims,id:string,target:string,input:any,key:string,requestId:string) { return this.db.transaction(async c=>this.idem(c,auth,`candidate.${target.toLowerCase()}`,key,{id,...input},async()=>{ const old=(await c.query<any>(`SELECT * FROM asset_candidates WHERE tenant_id=$1 AND id=$2 FOR UPDATE`,[auth.tenantId,id])).rows[0]; if(!old) throw new NotFoundException({code:"ASSET_CANDIDATE_NOT_FOUND"}); this.scope(auth,old.branch_id); if(!transitions.candidate[target]?.includes(old.status)) throw new ConflictException({code:"ASSET_CANDIDATE_STATUS_INVALID"}); if(target==='APPROVED_FOR_CAPITALIZATION'&&old.requested_by_user_id===auth.userId) throw new ForbiddenException({code:"ASSET_CANDIDATE_SELF_APPROVAL_DENIED"}); const n=(await c.query<any>(`UPDATE asset_candidates SET status=$3,classification=CASE WHEN $3='CLASSIFIED_EXPENSE' THEN 'EXPENSE' WHEN $3='CLASSIFIED_INVENTORY' THEN 'INVENTORY' WHEN $3='PENDING_CAPITALIZATION' THEN 'FIXED_ASSET' ELSE classification END,approved_by_user_id=CASE WHEN $3='APPROVED_FOR_CAPITALIZATION' THEN $4 ELSE approved_by_user_id END,approved_snapshot_json=CASE WHEN $3='APPROVED_FOR_CAPITALIZATION' THEN to_jsonb(asset_candidates) ELSE approved_snapshot_json END,version=version+1,updated_at=now() WHERE tenant_id=$1 AND id=$2 RETURNING *`,[auth.tenantId,id,target,auth.userId])).rows[0]; await c.query(`INSERT INTO asset_candidate_classification_history(tenant_id,candidate_id,from_classification,to_classification,actor_user_id,reason,version) VALUES($1,$2,$3,$4,$5,$6,$7)`,[auth.tenantId,id,old.classification,n.classification,auth.userId,input?.reason??"state transition",n.version]); await this.audit(c,auth,"asset.candidate_classified","asset_candidate",id,old,n,requestId,input?.reason); return n; })); }

  async listAssets(auth:AccessClaims) { this.guard(auth); return (await this.db.query<any>(`SELECT * FROM assets WHERE tenant_id=$1 AND ($2::uuid[] IS NULL OR branch_id=ANY($2::uuid[])) ORDER BY asset_code`,[auth.tenantId,auth.branchIds.length?auth.branchIds:null])).rows; }
  async getAsset(auth:AccessClaims,id:string) { this.guard(auth); const r=await this.db.query<any>(`SELECT * FROM assets WHERE tenant_id=$1 AND id=$2`,[auth.tenantId,id]); if(!r.rows[0]) throw new NotFoundException({code:"ASSET_NOT_FOUND"}); this.scope(auth,r.rows[0].branch_id); return r.rows[0]; }
  async createAsset(auth:AccessClaims,input:any,key:string,requestId:string) { this.guard(auth); this.scope(auth,input?.branchId); return this.db.transaction(async c=>this.idem(c,auth,"asset.create",key,input,async()=>{ await this.requireActive(auth); const gross=money(input?.grossCarryingAmountMinor,"GROSS_CARRYING_AMOUNT"); const residual=money(input?.residualValueMinor??0,"RESIDUAL_VALUE"); if(residual>gross) throw new ConflictException({code:"ASSET_CONFIGURATION_INCOMPLETE"}); const code=input?.assetCode??`FA-${randomUUID().slice(0,8).toUpperCase()}`; const r=await c.query<any>(`INSERT INTO assets(tenant_id,branch_id,category_id,policy_id,asset_code,name,description,brand,model,serial_number,status,room_location,custodian_user_id,acquisition_date,in_service_date,capitalization_date,currency,gross_carrying_amount_minor,residual_value_minor,useful_life_periods,depreciation_method,depreciation_convention,approved_snapshot_json,created_by_user_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,'DRAFT',$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,$23) RETURNING *`,[auth.tenantId,input.branchId,required(input.categoryId,"category_id"),input.policyId??null,code,required(input.name,"asset_name"),input.description??null,input.brand??null,input.model??null,input.serialNumber??null,input.location??null,input.custodianUserId??null,input.acquisitionDate??null,input.inServiceDate??null,input.capitalizationDate??null,required(input.currency??"VND","currency").toUpperCase(),gross.toString(),residual.toString(),input.usefulLifePeriods??null,input.depreciationMethod??null,input.depreciationConvention??null,JSON.stringify(input),auth.userId]); await this.audit(c,auth,"asset.created","asset",r.rows[0].id,null,r.rows[0],requestId); return r.rows[0]; })); }
  async assetStatus(auth:AccessClaims,id:string,target:string,input:any,key:string,requestId:string) { const allowed:Record<string,string[]>={PENDING_CAPITALIZATION:["DRAFT"],ACTIVE:["PENDING_CAPITALIZATION"],IDLE:["ACTIVE","IN_MAINTENANCE","IN_TRANSIT"],IN_MAINTENANCE:["ACTIVE","IDLE"],IN_TRANSIT:["ACTIVE","IDLE"],RETIRED:["ACTIVE","IDLE","IMPAIRED"],CANCELLED:["DRAFT","PENDING_CAPITALIZATION"]}; return this.db.transaction(async c=>this.idem(c,auth,`asset.${target.toLowerCase()}`,key,{id,...input},async()=>{ const old=(await c.query<any>(`SELECT * FROM assets WHERE tenant_id=$1 AND id=$2 FOR UPDATE`,[auth.tenantId,id])).rows[0]; if(!old) throw new NotFoundException({code:"ASSET_NOT_FOUND"}); this.scope(auth,old.branch_id); if(!allowed[target]?.includes(old.status)) throw new ConflictException({code:"ASSET_STATUS_INVALID"}); const n=(await c.query<any>(`UPDATE assets SET status=$3,version=version+1,in_service_date=CASE WHEN $3='ACTIVE' THEN COALESCE(in_service_date,current_date) ELSE in_service_date END,updated_at=now() WHERE tenant_id=$1 AND id=$2 RETURNING *`,[auth.tenantId,id,target])).rows[0]; await c.query(`INSERT INTO asset_status_history(tenant_id,asset_id,from_status,to_status,actor_user_id,reason,request_id) VALUES($1,$2,$3,$4,$5,$6,$7)`,[auth.tenantId,id,old.status,target,auth.userId,input?.reason??null,requestId]); await this.audit(c,auth,"asset.status_changed","asset",id,old,n,requestId,input?.reason); return n; })); }
  async assetHistory(auth:AccessClaims,id:string) { await this.getAsset(auth,id); return (await this.db.query<any>(`SELECT * FROM asset_status_history WHERE tenant_id=$1 AND asset_id=$2 ORDER BY created_at`,[auth.tenantId,id])).rows; }

  async createCapitalization(auth:AccessClaims,input:any,key:string,requestId:string) { this.guard(auth); this.scope(auth,input?.branchId); return this.db.transaction(async c=>this.idem(c,auth,"capitalization.create",key,input,async()=>{ await this.requireActive(auth); const amount=money(input?.grossAmountMinor,"CAPITALIZATION_AMOUNT"); const r=await c.query<any>(`INSERT INTO asset_capitalization_requests(tenant_id,branch_id,status,currency,gross_amount_minor,in_service_date,location,custodian_user_id,policy_snapshot_json,source_fingerprint,requested_by_user_id) VALUES($1,$2,'DRAFT',$3,$4,$5,$6,$7,$8,$9,$10) RETURNING *`,[auth.tenantId,input.branchId,required(input.currency??"VND","currency").toUpperCase(),amount.toString(),input.inServiceDate??new Date().toISOString().slice(0,10),input.location??null,input.custodianUserId??null,JSON.stringify(input.policySnapshot??{}),input.sourceFingerprint??fp(input),auth.userId]); for(const l of input.lines??[]) await c.query(`INSERT INTO asset_capitalization_request_lines(tenant_id,request_id,candidate_id,amount_minor) VALUES($1,$2,$3,$4)`,[auth.tenantId,r.rows[0].id,l.candidateId,l.amountMinor]); await this.audit(c,auth,"asset.capitalization_requested","asset_capitalization_request",r.rows[0].id,null,r.rows[0],requestId); return r.rows[0]; })); }
  async listCapitalizations(auth:AccessClaims) { this.guard(auth); return (await this.db.query<any>(`SELECT * FROM asset_capitalization_requests WHERE tenant_id=$1 ORDER BY created_at DESC`,[auth.tenantId])).rows; }
  async getCapitalization(auth:AccessClaims,id:string) { this.guard(auth); const r=await this.db.query<any>(`SELECT * FROM asset_capitalization_requests WHERE tenant_id=$1 AND id=$2`,[auth.tenantId,id]); if(!r.rows[0]) throw new NotFoundException({code:"CAPITALIZATION_REQUEST_NOT_FOUND"}); this.scope(auth,r.rows[0].branch_id); return {...r.rows[0],lines:(await this.db.query<any>(`SELECT * FROM asset_capitalization_request_lines WHERE tenant_id=$1 AND request_id=$2`,[auth.tenantId,id])).rows}; }
  async capitalizationStatus(auth:AccessClaims,id:string,target:string,input:any,key:string,requestId:string) { return this.db.transaction(async c=>this.idem(c,auth,`capitalization.${target.toLowerCase()}`,key,{id,...input},async()=>{ const old=(await c.query<any>(`SELECT * FROM asset_capitalization_requests WHERE tenant_id=$1 AND id=$2 FOR UPDATE`,[auth.tenantId,id])).rows[0]; if(!old) throw new NotFoundException({code:"CAPITALIZATION_REQUEST_NOT_FOUND"}); this.scope(auth,old.branch_id); if(!transitions.capitalization[target]?.includes(old.status)) throw new ConflictException({code:"CAPITALIZATION_STATUS_INVALID"}); if(target==='APPROVED'&&old.requested_by_user_id===auth.userId) throw new ForbiddenException({code:"CAPITALIZATION_SELF_APPROVAL_DENIED"}); if(target==='CAPITALIZED') { const lines=(await c.query<any>(`SELECT * FROM asset_capitalization_request_lines WHERE tenant_id=$1 AND request_id=$2 FOR UPDATE`,[auth.tenantId,id])).rows; if(!lines.length) throw new ConflictException({code:"CAPITALIZATION_AMOUNT_EXCEEDED"}); for(const l of lines){ const cand=(await c.query<any>(`SELECT * FROM asset_candidates WHERE tenant_id=$1 AND id=$2 FOR UPDATE`,[auth.tenantId,l.candidate_id])).rows[0]; if(!cand||cand.status!=='APPROVED_FOR_CAPITALIZATION'||BigInt(l.amount_minor)>BigInt(cand.eligible_amount_minor)-BigInt(cand.allocated_amount_minor)) throw new ConflictException({code:"CAPITALIZATION_AMOUNT_EXCEEDED"}); const asset=await this.createAssetWithin(c,auth,{branchId:old.branch_id,categoryId:input.categoryId??input.category_id,name:input.name??cand.name??"Capitalized asset",currency:old.currency,grossCarryingAmountMinor:l.amount_minor,inServiceDate:old.in_service_date,policyId:input.policyId,assetCode:input.assetCode},requestId); await c.query(`UPDATE asset_candidates SET allocated_amount_minor=allocated_amount_minor+$3,status='CAPITALIZED',version=version+1 WHERE tenant_id=$1 AND id=$2`,[auth.tenantId,cand.id,l.amount_minor]); await c.query(`INSERT INTO asset_capitalization_history(tenant_id,request_id,asset_id,from_status,to_status,actor_user_id,source_fingerprint,request_id_text) VALUES($1,$2,$3,$4,$5,$6,$7,$8)`,[auth.tenantId,id,asset.id,old.status,target,auth.userId,old.source_fingerprint,requestId]); } }
      const n=(await c.query<any>(`UPDATE asset_capitalization_requests SET status=$3,approved_by_user_id=CASE WHEN $3='APPROVED' THEN $4 ELSE approved_by_user_id END,version=version+1,updated_at=now() WHERE tenant_id=$1 AND id=$2 RETURNING *`,[auth.tenantId,id,target,auth.userId])).rows[0]; await this.audit(c,auth,`asset.capitalization_${target.toLowerCase()}`,"asset_capitalization_request",id,old,n,requestId,input?.reason); return n; })); }
  private async createAssetWithin(c:PoolClient,auth:AccessClaims,input:any,requestId:string) { const r=await c.query<any>(`INSERT INTO assets(tenant_id,branch_id,category_id,policy_id,asset_code,name,status,in_service_date,capitalization_date,currency,gross_carrying_amount_minor,residual_value_minor,useful_life_periods,depreciation_method,depreciation_convention,approved_snapshot_json,created_by_user_id) VALUES($1,$2,$3,$4,COALESCE($5,'FA-'||substr(gen_random_uuid()::text,1,8)),$6,'ACTIVE',$7,current_date,$8,$9,0,$10,$11,$12,$13,$14) RETURNING *`,[auth.tenantId,input.branchId,input.categoryId,input.policyId??null,input.assetCode??null,input.name,input.inServiceDate, input.currency,input.grossCarryingAmountMinor,input.usefulLifePeriods??null,input.depreciationMethod??"STRAIGHT_LINE",input.depreciationConvention??"FULL_MONTH",JSON.stringify(input),auth.userId]); return r.rows[0]; }

  async listDepreciationRuns(auth:AccessClaims) { this.guard(auth); return (await this.db.query<any>(`SELECT * FROM asset_depreciation_runs WHERE tenant_id=$1 ORDER BY cutoff_date DESC`,[auth.tenantId])).rows; }
  async getDepreciationRun(auth:AccessClaims,id:string) { this.guard(auth); const r=await this.db.query<any>(`SELECT * FROM asset_depreciation_runs WHERE tenant_id=$1 AND id=$2`,[auth.tenantId,id]); if(!r.rows[0]) throw new NotFoundException({code:"DEPRECIATION_RUN_NOT_FOUND"}); return {...r.rows[0],lines:(await this.db.query<any>(`SELECT * FROM asset_depreciation_run_lines WHERE tenant_id=$1 AND run_id=$2`,[auth.tenantId,id])).rows}; }
  async createDepreciationRun(auth:AccessClaims,input:any,key:string,requestId:string) { this.guard(auth); return this.db.transaction(async c=>this.idem(c,auth,"depreciation.create",key,input,async()=>{ await this.requireActive(auth); const r=await c.query<any>(`INSERT INTO asset_depreciation_runs(tenant_id,book_id,period_id,cutoff_date,fingerprint,requested_by_user_id) VALUES($1,$2,$3,$4,$5,$6) RETURNING *`,[auth.tenantId,required(input.bookId,"book_id"),required(input.periodId,"period_id"),input.cutoffDate??new Date().toISOString().slice(0,10),fp(input),auth.userId]); return r.rows[0]; })); }
  async calculateDepreciation(auth:AccessClaims,id:string,input:any,key:string,requestId:string) { return this.db.transaction(async c=>this.idem(c,auth,"depreciation.calculate",key,{id,...input},async()=>{ const run=(await c.query<any>(`SELECT * FROM asset_depreciation_runs WHERE tenant_id=$1 AND id=$2 FOR UPDATE`,[auth.tenantId,id])).rows[0]; if(!run) throw new NotFoundException({code:"DEPRECIATION_RUN_NOT_FOUND"}); if(!transitions.depreciation.CALCULATING.includes(run.status)) throw new ConflictException({code:"DEPRECIATION_RUN_STATUS_INVALID"}); const assets=(await c.query<any>(`SELECT * FROM assets WHERE tenant_id=$1 AND status IN('ACTIVE','IN_MAINTENANCE','IDLE','IMPAIRED') AND in_service_date IS NOT NULL AND in_service_date <= $2 AND (disposal_date IS NULL OR disposal_date > $2) FOR UPDATE`,[auth.tenantId,run.cutoff_date])).rows; let total=0n; for(const a of assets){ const base=BigInt(a.gross_carrying_amount_minor)-BigInt(a.residual_value_minor); const remaining=base-BigInt(a.accumulated_depreciation_minor); if(remaining<=0n) continue; const life=BigInt(a.useful_life_periods??12); const amount=remaining<base/life?remaining:base/life; if(amount<=0n) continue; total+=amount; await c.query(`INSERT INTO asset_depreciation_run_lines(tenant_id,run_id,asset_id,opening_gross_minor,opening_accumulated_minor,period_amount_minor,closing_accumulated_minor,closing_nbv_minor,method,policy_version,remainder_minor,status,source_fingerprint) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,0,'READY',$11) ON CONFLICT(tenant_id,run_id,asset_id) DO UPDATE SET period_amount_minor=EXCLUDED.period_amount_minor,closing_accumulated_minor=EXCLUDED.closing_accumulated_minor,closing_nbv_minor=EXCLUDED.closing_nbv_minor`,[auth.tenantId,id,a.id,a.gross_carrying_amount_minor,a.accumulated_depreciation_minor,amount.toString(),(BigInt(a.accumulated_depreciation_minor)+amount).toString(),(BigInt(a.gross_carrying_amount_minor)-BigInt(a.accumulated_depreciation_minor)-amount).toString(),a.depreciation_method??"STRAIGHT_LINE",a.policy_id??null,fp({run:id,asset:a.id,amount:amount.toString()})]); }
      const n=(await c.query<any>(`UPDATE asset_depreciation_runs SET status='READY',candidate_count=$3,total_amount_minor=$4,version=version+1,updated_at=now() WHERE tenant_id=$1 AND id=$2 RETURNING *`,[auth.tenantId,id,assets.length,total.toString()])).rows[0]; await this.audit(c,auth,"asset.depreciation_calculated","asset_depreciation_run",id,run,n,requestId); return n; })); }
  async depreciationStatus(auth:AccessClaims,id:string,target:string,input:any,key:string,requestId:string) { return this.db.transaction(async c=>this.idem(c,auth,`depreciation.${target.toLowerCase()}`,key,{id,...input},async()=>{ const old=(await c.query<any>(`SELECT * FROM asset_depreciation_runs WHERE tenant_id=$1 AND id=$2 FOR UPDATE`,[auth.tenantId,id])).rows[0]; if(!old) throw new NotFoundException({code:"DEPRECIATION_RUN_NOT_FOUND"}); if(!transitions.depreciation[target]?.includes(old.status)) throw new ConflictException({code:"DEPRECIATION_RUN_STATUS_INVALID"}); if(target==='APPROVED'&&old.requested_by_user_id===auth.userId) throw new ForbiddenException({code:"DEPRECIATION_SELF_APPROVAL_DENIED"}); if(target==='POSTED'){ const lines=(await c.query<any>(`SELECT * FROM asset_depreciation_run_lines WHERE tenant_id=$1 AND run_id=$2 FOR UPDATE`,[auth.tenantId,id])).rows; for(const line of lines){ const a=(await c.query<any>(`SELECT * FROM assets WHERE tenant_id=$1 AND id=$2 FOR UPDATE`,[auth.tenantId,line.asset_id])).rows[0]; const next=BigInt(a.accumulated_depreciation_minor)+BigInt(line.period_amount_minor); const cap=BigInt(a.gross_carrying_amount_minor)-BigInt(a.residual_value_minor); if(next>cap) throw new ConflictException({code:"DEPRECIATION_EXCEEDS_BASE"}); await c.query(`UPDATE assets SET accumulated_depreciation_minor=$3,version=version+1,updated_at=now() WHERE tenant_id=$1 AND id=$2`,[auth.tenantId,a.id,next.toString()]); await c.query(`INSERT INTO asset_depreciation_schedules(tenant_id,asset_id,period_start,period_end,amount_minor,cumulative_minor,fingerprint,posted_run_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8) ON CONFLICT(tenant_id,asset_id,period_start) DO NOTHING`,[auth.tenantId,a.id,old.cutoff_date,old.cutoff_date,line.period_amount_minor,next.toString(),line.source_fingerprint,id]); } await c.query(`INSERT INTO asset_depreciation_posting_history(tenant_id,run_id,state,fingerprint) VALUES($1,$2,'POSTED',$3) ON CONFLICT DO NOTHING`,[auth.tenantId,id,old.fingerprint]); }
      const n=(await c.query<any>(`UPDATE asset_depreciation_runs SET status=$3,approved_by_user_id=CASE WHEN $3='APPROVED' THEN $4 ELSE approved_by_user_id END,posted_by_user_id=CASE WHEN $3='POSTED' THEN $4 ELSE posted_by_user_id END,updated_at=now(),version=version+1 WHERE tenant_id=$1 AND id=$2 RETURNING *`,[auth.tenantId,id,target,auth.userId])).rows[0]; await this.audit(c,auth,`asset.depreciation_${target.toLowerCase()}`,"asset_depreciation_run",id,old,n,requestId,input?.reason); return n; })); }
  async depreciationSchedules(auth:AccessClaims,input:any) { this.guard(auth); const q=await this.db.query<any>(`SELECT s.*,a.asset_code,a.name FROM asset_depreciation_schedules s JOIN assets a ON a.tenant_id=s.tenant_id AND a.id=s.asset_id WHERE s.tenant_id=$1 ORDER BY s.period_start,a.asset_code`,[auth.tenantId]); return q.rows; }

  async listMaintenancePlans(auth:AccessClaims) { this.guard(auth); return (await this.db.query<any>(`SELECT * FROM asset_maintenance_plans WHERE tenant_id=$1 ORDER BY created_at DESC`,[auth.tenantId])).rows; }
  async createMaintenancePlan(auth:AccessClaims,input:any,key:string,requestId:string) { this.guard(auth); this.scope(auth,input?.branchId); return this.db.transaction(async c=>this.idem(c,auth,"maintenance_plan.create",key,input,async()=>{ const r=await c.query<any>(`INSERT INTO asset_maintenance_plans(tenant_id,branch_id,asset_id,category_id,maintenance_type,trigger_basis,interval_days,interval_usage,checklist_json,assigned_team,lead_time_days,estimated_downtime_minutes,estimated_cost_minor,created_by_user_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14) RETURNING *`,[auth.tenantId,input.branchId??null,input.assetId??null,input.categoryId??null,required(input.maintenanceType??"PREVENTIVE","maintenance_type"),input.triggerBasis??"CALENDAR",input.intervalDays??null,input.intervalUsage??null,JSON.stringify(input.checklist??[]),input.assignedTeam??null,input.leadTimeDays??0,input.estimatedDowntimeMinutes??0,money(input.estimatedCostMinor??0).toString(),auth.userId]); await this.audit(c,auth,"asset.maintenance_plan_created","asset_maintenance_plan",r.rows[0].id,null,r.rows[0],requestId); return r.rows[0]; })); }
  async maintenancePlanStatus(auth:AccessClaims,id:string,target:string,input:any,key:string,requestId:string) { return this.db.transaction(async c=>this.idem(c,auth,`maintenance_plan.${target.toLowerCase()}`,key,{id,...input},async()=>{ const old=(await c.query<any>(`SELECT * FROM asset_maintenance_plans WHERE tenant_id=$1 AND id=$2 FOR UPDATE`,[auth.tenantId,id])).rows[0]; if(!old) throw new NotFoundException({code:"MAINTENANCE_PLAN_NOT_FOUND"}); this.scope(auth,old.branch_id); if(!transitions.maintenancePlan[target]?.includes(old.status)) throw new ConflictException({code:"MAINTENANCE_STATUS_INVALID"}); const n=(await c.query<any>(`UPDATE asset_maintenance_plans SET status=$3,version=version+1 WHERE tenant_id=$1 AND id=$2 RETURNING *`,[auth.tenantId,id,target])).rows[0]; return n; })); }
  async listWorkOrders(auth:AccessClaims) {
    this.guard(auth);
    const ownAssigned = auth.roles.includes("NAIL_TECHNICIAN") && !auth.roles.includes("SALON_OWNER");
    if (ownAssigned && !auth.userId) throw new ForbiddenException({ code: "STAFF_SCOPE_REQUIRED", message: "Assigned staff scope is required" });
    const assignmentClause = ownAssigned ? " AND assigned_user_id=$3" : "";
    const params = ownAssigned
      ? [auth.tenantId, auth.branchIds.length ? auth.branchIds : null, auth.userId]
      : [auth.tenantId, auth.branchIds.length ? auth.branchIds : null];
    return (await this.db.query<any>(`SELECT * FROM asset_maintenance_work_orders WHERE tenant_id=$1 AND ($2::uuid[] IS NULL OR branch_id=ANY($2::uuid[]))${assignmentClause} ORDER BY scheduled_start_at NULLS LAST,created_at DESC`, params)).rows;
  }
  async createWorkOrder(auth:AccessClaims,input:any,key:string,requestId:string) { this.guard(auth); this.scope(auth,input?.branchId); return this.db.transaction(async c=>this.idem(c,auth,"work_order.create",key,input,async()=>{ const r=await c.query<any>(`INSERT INTO asset_maintenance_work_orders(tenant_id,branch_id,asset_id,plan_id,work_type,priority,problem,scheduled_start_at,scheduled_end_at,assigned_user_id,vendor_id,created_by_user_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) RETURNING *`,[auth.tenantId,input.branchId,required(input.assetId,"asset_id"),input.planId??null,input.workType??"PREVENTIVE",input.priority??"NORMAL",input.problem??null,input.scheduledStartAt??null,input.scheduledEndAt??null,input.assignedUserId??null,input.vendorId??null,auth.userId]); await this.audit(c,auth,"asset.maintenance_work_order_created","asset_maintenance_work_order",r.rows[0].id,null,r.rows[0],requestId); return r.rows[0]; })); }
  async workOrderStatus(auth:AccessClaims,id:string,target:string,input:any,key:string,requestId:string) { return this.db.transaction(async c=>this.idem(c,auth,`work_order.${target.toLowerCase()}`,key,{id,...input},async()=>{ const old=(await c.query<any>(`SELECT * FROM asset_maintenance_work_orders WHERE tenant_id=$1 AND id=$2 FOR UPDATE`,[auth.tenantId,id])).rows[0]; if(!old) throw new NotFoundException({code:"MAINTENANCE_WORK_ORDER_NOT_FOUND"}); this.scope(auth,old.branch_id); if(!transitions.workOrder[target]?.includes(old.status)) throw new ConflictException({code:"MAINTENANCE_STATUS_INVALID"}); if(target==='VERIFIED'&&old.assigned_user_id===auth.userId) throw new ForbiddenException({code:"MAINTENANCE_SELF_VERIFICATION_DENIED"}); const n=(await c.query<any>(`UPDATE asset_maintenance_work_orders SET status=$3,verified_by_user_id=CASE WHEN $3='VERIFIED' THEN $4 ELSE verified_by_user_id END,completion_notes=COALESCE($5,completion_notes),version=version+1,updated_at=now() WHERE tenant_id=$1 AND id=$2 RETURNING *`,[auth.tenantId,id,target,auth.userId,input?.completionNotes??null])).rows[0]; if(target==='IN_PROGRESS') await c.query(`UPDATE assets SET status='IN_MAINTENANCE',version=version+1 WHERE tenant_id=$1 AND id=$2 AND status IN('ACTIVE','IDLE')`,[auth.tenantId,old.asset_id]); if(target==='VERIFIED') await c.query(`UPDATE assets SET status='ACTIVE',version=version+1 WHERE tenant_id=$1 AND id=$2 AND status='IN_MAINTENANCE'`,[auth.tenantId,old.asset_id]); await c.query(`INSERT INTO asset_maintenance_history(tenant_id,work_order_id,from_status,to_status,actor_user_id,reason) VALUES($1,$2,$3,$4,$5,$6)`,[auth.tenantId,id,old.status,target,auth.userId,input?.reason??null]); return n; })); }

  async listTransfers(auth:AccessClaims) {
    this.guard(auth);
    const ownAssigned = auth.roles.includes("NAIL_TECHNICIAN") && !auth.roles.includes("SALON_OWNER");
    if (ownAssigned && !auth.userId) throw new ForbiddenException({ code: "STAFF_SCOPE_REQUIRED", message: "Assigned staff scope is required" });
    const branchClause = auth.branchIds.length ? "(source_branch_id=ANY($2::uuid[]) OR destination_branch_id=ANY($2::uuid[]))" : "TRUE";
    const assignmentParam = auth.branchIds.length ? "$3" : "$2";
    const assignmentClause = ownAssigned ? ` AND destination_custodian_user_id=${assignmentParam}` : "";
    const params = ownAssigned
      ? (auth.branchIds.length ? [auth.tenantId, auth.branchIds, auth.userId] : [auth.tenantId, auth.userId])
      : (auth.branchIds.length ? [auth.tenantId, auth.branchIds] : [auth.tenantId]);
    return (await this.db.query<any>(`SELECT * FROM asset_transfers WHERE tenant_id=$1 AND ${branchClause}${assignmentClause} ORDER BY created_at DESC`, params)).rows;
  }
  async createTransfer(auth:AccessClaims,input:any,key:string,requestId:string) { this.guard(auth); this.scope(auth,input?.sourceBranchId); return this.db.transaction(async c=>this.idem(c,auth,"transfer.create",key,input,async()=>{ const asset=(await c.query<any>(`SELECT * FROM assets WHERE tenant_id=$1 AND id=$2 FOR UPDATE`,[auth.tenantId,input.assetId])).rows[0]; if(!asset) throw new NotFoundException({code:"ASSET_NOT_FOUND"}); this.scope(auth,asset.branch_id); if(asset.branch_id!==input.sourceBranchId) throw new ForbiddenException({code:"ASSET_TRANSFER_SOURCE_SCOPE_DENIED"}); const active=await c.query(`SELECT 1 FROM asset_transfers WHERE tenant_id=$1 AND asset_id=$2 AND status IN('PENDING_APPROVAL','APPROVED','DISPATCHED','IN_TRANSIT')`,[auth.tenantId,input.assetId]); if(active.rowCount) throw new ConflictException({code:"ASSET_TRANSFER_ALREADY_ACTIVE"}); const r=await c.query<any>(`INSERT INTO asset_transfers(tenant_id,asset_id,source_branch_id,destination_branch_id,source_location,destination_location,destination_custodian_user_id,requested_by_user_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *`,[auth.tenantId,input.assetId,input.sourceBranchId,input.destinationBranchId,input.sourceLocation??asset.room_location??null,input.destinationLocation??null,input.destinationCustodianUserId??null,auth.userId]); await this.audit(c,auth,"asset.transfer_requested","asset_transfer",r.rows[0].id,null,r.rows[0],requestId); return r.rows[0]; })); }
  async transferStatus(auth:AccessClaims,id:string,target:string,input:any,key:string,requestId:string) { return this.db.transaction(async c=>this.idem(c,auth,`transfer.${target.toLowerCase()}`,key,{id,...input},async()=>{ const old=(await c.query<any>(`SELECT * FROM asset_transfers WHERE tenant_id=$1 AND id=$2 FOR UPDATE`,[auth.tenantId,id])).rows[0]; if(!old) throw new NotFoundException({code:"ASSET_TRANSFER_NOT_FOUND"}); if(!transitions.transfer[target]?.includes(old.status)) throw new ConflictException({code:"ASSET_TRANSFER_STATUS_INVALID"}); if(target==='APPROVED'&&old.requested_by_user_id===auth.userId) throw new ForbiddenException({code:"ASSET_TRANSFER_SOURCE_SCOPE_DENIED"}); if(target==='RECEIVED') this.scope(auth,old.destination_branch_id); const n=(await c.query<any>(`UPDATE asset_transfers SET status=$3,approved_by_user_id=CASE WHEN $3='APPROVED' THEN $4 ELSE approved_by_user_id END,dispatched_by_user_id=CASE WHEN $3='DISPATCHED' THEN $4 ELSE dispatched_by_user_id END,received_by_user_id=CASE WHEN $3='RECEIVED' THEN $4 ELSE received_by_user_id END,version=version+1 WHERE tenant_id=$1 AND id=$2 RETURNING *`,[auth.tenantId,id,target,auth.userId])).rows[0]; if(target==='DISPATCHED'||target==='IN_TRANSIT') await c.query(`UPDATE assets SET status='IN_TRANSIT',version=version+1 WHERE tenant_id=$1 AND id=$2`,[auth.tenantId,old.asset_id]); if(target==='RECEIVED') await c.query(`UPDATE assets SET status='ACTIVE',branch_id=$3,room_location=$4,custodian_user_id=COALESCE($5,custodian_user_id),version=version+1 WHERE tenant_id=$1 AND id=$2`,[auth.tenantId,old.asset_id,old.destination_branch_id,old.destination_location,old.destination_custodian_user_id]); await c.query(`INSERT INTO asset_transfer_history(tenant_id,transfer_id,from_status,to_status,actor_user_id,reason) VALUES($1,$2,$3,$4,$5,$6)`,[auth.tenantId,id,old.status,target,auth.userId,input?.reason??null]); return n; })); }
  async listCounts(auth:AccessClaims) { this.guard(auth); return (await this.db.query<any>(`SELECT * FROM asset_count_sessions WHERE tenant_id=$1 AND ($2::uuid[] IS NULL OR branch_id=ANY($2::uuid[])) ORDER BY created_at DESC`,[auth.tenantId,auth.branchIds.length?auth.branchIds:null])).rows; }
  async createCount(auth:AccessClaims,input:any,key:string,requestId:string) { this.guard(auth); this.scope(auth,input.branchId); return this.db.transaction(async c=>this.idem(c,auth,"count.create",key,input,async()=>{ const expected=(await c.query<any>(`SELECT id,asset_code,status,branch_id FROM assets WHERE tenant_id=$1 AND branch_id=$2 AND status NOT IN('CANCELLED') ORDER BY asset_code`,[auth.tenantId,input.branchId])).rows; const r=await c.query<any>(`INSERT INTO asset_count_sessions(tenant_id,branch_id,expected_snapshot_json,created_by_user_id) VALUES($1,$2,$3,$4) RETURNING *`,[auth.tenantId,input.branchId,JSON.stringify(expected),auth.userId]); for(const a of expected) await c.query(`INSERT INTO asset_count_lines(tenant_id,session_id,asset_id) VALUES($1,$2,$3)`,[auth.tenantId,r.rows[0].id,a.id]); await this.audit(c,auth,"asset.count_opened","asset_count_session",r.rows[0].id,null,r.rows[0],requestId); return r.rows[0]; })); }
  async countStatus(auth:AccessClaims,id:string,target:string,input:any,key:string,requestId:string) { return this.db.transaction(async c=>this.idem(c,auth,`count.${target.toLowerCase()}`,key,{id,...input},async()=>{ const old=(await c.query<any>(`SELECT * FROM asset_count_sessions WHERE tenant_id=$1 AND id=$2 FOR UPDATE`,[auth.tenantId,id])).rows[0]; if(!old) throw new NotFoundException({code:"ASSET_COUNT_SESSION_NOT_FOUND"}); this.scope(auth,old.branch_id); if(!transitions.count[target]?.includes(old.status)) throw new ConflictException({code:"ASSET_COUNT_STATUS_INVALID"}); const n=(await c.query<any>(`UPDATE asset_count_sessions SET status=$3,opened_at=CASE WHEN $3='OPEN' THEN now() ELSE opened_at END,approved_by_user_id=CASE WHEN $3='APPROVED' THEN $4 ELSE approved_by_user_id END,version=version+1 WHERE tenant_id=$1 AND id=$2 RETURNING *`,[auth.tenantId,id,target,auth.userId])).rows[0]; return n; })); }
  async recordCount(auth:AccessClaims,id:string,input:any,key:string,requestId:string) { return this.db.transaction(async c=>this.idem(c,auth,"count.record",key,{id,...input},async()=>{ const session=(await c.query<any>(`SELECT * FROM asset_count_sessions WHERE tenant_id=$1 AND id=$2 FOR UPDATE`,[auth.tenantId,id])).rows[0]; if(!session) throw new NotFoundException({code:"ASSET_COUNT_SESSION_NOT_FOUND"}); this.scope(auth,session.branch_id); if(!['OPEN','COUNTING'].includes(session.status)) throw new ConflictException({code:"ASSET_COUNT_STATUS_INVALID"}); const line=(await c.query<any>(`UPDATE asset_count_lines SET line_status=$4,found_location=$5,condition=$6,evidence_json=$7,recorded_by_user_id=$8,recorded_at=now() WHERE tenant_id=$1 AND session_id=$2 AND id=$3 RETURNING *`,[auth.tenantId,id,input.lineId,input.lineStatus??"FOUND",input.foundLocation??null,input.condition??null,JSON.stringify(input.evidence??{}),auth.userId])).rows[0]; if(!line) throw new NotFoundException({code:"ASSET_COUNT_SESSION_NOT_FOUND"}); return line; })); }
  async listInspections(auth:AccessClaims) {
    this.guard(auth);
    const ownAssigned = auth.roles.includes("NAIL_TECHNICIAN") && !auth.roles.includes("SALON_OWNER");
    if (ownAssigned && !auth.userId) throw new ForbiddenException({ code: "STAFF_SCOPE_REQUIRED", message: "Assigned staff scope is required" });
    const branchClause = auth.branchIds.length ? " AND branch_id=ANY($2::uuid[])" : "";
    const assignmentClause = ownAssigned ? ` AND assigned_user_id=${auth.branchIds.length ? "$3" : "$2"}` : "";
    const params = ownAssigned
      ? (auth.branchIds.length ? [auth.tenantId, auth.branchIds, auth.userId] : [auth.tenantId, auth.userId])
      : (auth.branchIds.length ? [auth.tenantId, auth.branchIds] : [auth.tenantId]);
    return (await this.db.query<any>(`SELECT * FROM asset_inspections WHERE tenant_id=$1${branchClause}${assignmentClause} ORDER BY scheduled_at NULLS LAST`, params)).rows;
  }
  async createInspection(auth:AccessClaims,input:any,key:string,requestId:string) { this.guard(auth); this.scope(auth,input.branchId); return this.db.transaction(async c=>this.idem(c,auth,"inspection.create",key,input,async()=>{ const r=await c.query<any>(`INSERT INTO asset_inspections(tenant_id,branch_id,asset_id,scheduled_at,assigned_user_id,created_by_user_id) VALUES($1,$2,$3,$4,$5,$6) RETURNING *`,[auth.tenantId,input.branchId,input.assetId,input.scheduledAt??null,input.assignedUserId??null,auth.userId]); return r.rows[0]; })); }
  async inspectionStatus(auth:AccessClaims,id:string,target:string,input:any,key:string,requestId:string) { return this.db.transaction(async c=>this.idem(c,auth,`inspection.${target.toLowerCase()}`,key,{id,...input},async()=>{ const old=(await c.query<any>(`SELECT * FROM asset_inspections WHERE tenant_id=$1 AND id=$2 FOR UPDATE`,[auth.tenantId,id])).rows[0]; if(!old) throw new NotFoundException({code:"ASSET_INSPECTION_NOT_FOUND"}); this.scope(auth,old.branch_id); if(!transitions.inspection[target]?.includes(old.status)) throw new ConflictException({code:"ASSET_INSPECTION_STATUS_INVALID"}); const n=(await c.query<any>(`UPDATE asset_inspections SET status=$3,completed_at=CASE WHEN $3 IN('PASSED','FAILED','REQUIRES_MAINTENANCE') THEN now() ELSE completed_at END,version=version+1 WHERE tenant_id=$1 AND id=$2 RETURNING *`,[auth.tenantId,id,target])).rows[0]; await c.query(`INSERT INTO asset_inspection_results(tenant_id,inspection_id,checklist_json,evidence_json,result) VALUES($1,$2,$3,$4,$5)`,[auth.tenantId,id,JSON.stringify(input?.checklist??[]),JSON.stringify(input?.evidence??{}),target]); return n; })); }

  async listImpairments(auth:AccessClaims) { this.guard(auth); return (await this.db.query<any>(`SELECT * FROM asset_impairment_requests WHERE tenant_id=$1 ORDER BY created_at DESC`,[auth.tenantId])).rows; }
  async createImpairment(auth:AccessClaims,input:any,key:string,requestId:string) { this.guard(auth); return this.db.transaction(async c=>this.idem(c,auth,"impairment.create",key,input,async()=>{ const a=(await c.query<any>(`SELECT * FROM assets WHERE tenant_id=$1 AND id=$2 FOR UPDATE`,[auth.tenantId,input.assetId])).rows[0]; if(!a) throw new NotFoundException({code:"ASSET_NOT_FOUND"}); this.scope(auth,a.branch_id); const amount=money(input.amountMinor,"IMPAIRMENT_AMOUNT"); const nbv=BigInt(a.gross_carrying_amount_minor)-BigInt(a.accumulated_depreciation_minor)-BigInt(a.accumulated_impairment_minor); if(amount>nbv) throw new ConflictException({code:"ASSET_IMPAIRMENT_EXCEEDS_NBV"}); const r=await c.query<any>(`INSERT INTO asset_impairment_requests(tenant_id,branch_id,asset_id,amount_minor,recoverable_amount_minor,minimum_carrying_minor,evidence_json,requested_by_user_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *`,[auth.tenantId,a.branch_id,input.assetId,amount.toString(),input.recoverableAmountMinor??0,input.minimumCarryingMinor??0,JSON.stringify(input.evidence??{}),auth.userId]); return r.rows[0]; })); }
  async impairmentStatus(auth:AccessClaims,id:string,target:string,input:any,key:string,requestId:string) { return this.db.transaction(async c=>this.idem(c,auth,`impairment.${target.toLowerCase()}`,key,{id,...input},async()=>{ const old=(await c.query<any>(`SELECT * FROM asset_impairment_requests WHERE tenant_id=$1 AND id=$2 FOR UPDATE`,[auth.tenantId,id])).rows[0]; if(!old) throw new NotFoundException({code:"ASSET_IMPAIRMENT_NOT_FOUND"}); this.scope(auth,old.branch_id); if(!transitions.impairment[target]?.includes(old.status)) throw new ConflictException({code:"ASSET_IMPAIRMENT_STATUS_INVALID"}); if(target==='APPROVED'&&old.requested_by_user_id===auth.userId) throw new ForbiddenException({code:"ASSET_IMPAIRMENT_SELF_APPROVAL_DENIED"}); if(target==='POSTED'){ await c.query(`UPDATE assets SET accumulated_impairment_minor=accumulated_impairment_minor+$3,status='IMPAIRED',version=version+1 WHERE tenant_id=$1 AND id=$2`,[auth.tenantId,old.asset_id,old.amount_minor]); } const n=(await c.query<any>(`UPDATE asset_impairment_requests SET status=$3,approved_by_user_id=CASE WHEN $3='APPROVED' THEN $4 ELSE approved_by_user_id END,version=version+1 WHERE tenant_id=$1 AND id=$2 RETURNING *`,[auth.tenantId,id,target,auth.userId])).rows[0]; await c.query(`INSERT INTO asset_impairment_history(tenant_id,impairment_id,from_status,to_status,actor_user_id,reason) VALUES($1,$2,$3,$4,$5,$6)`,[auth.tenantId,id,old.status,target,auth.userId,input?.reason??null]); return n; })); }
  async listImprovements(auth:AccessClaims) { this.guard(auth); return (await this.db.query<any>(`SELECT * FROM asset_capital_improvements WHERE tenant_id=$1 ORDER BY created_at DESC`,[auth.tenantId])).rows; }
  async createImprovement(auth:AccessClaims,input:any,key:string,requestId:string) { this.guard(auth); return this.db.transaction(async c=>this.idem(c,auth,"improvement.create",key,input,async()=>{ const a=(await c.query<any>(`SELECT * FROM assets WHERE tenant_id=$1 AND id=$2`,[auth.tenantId,input.assetId])).rows[0]; if(!a) throw new NotFoundException({code:"ASSET_NOT_FOUND"}); this.scope(auth,a.branch_id); const r=await c.query<any>(`INSERT INTO asset_capital_improvements(tenant_id,branch_id,asset_id,work_order_id,amount_minor,useful_life_change,residual_value_change_minor,source_fingerprint,requested_by_user_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *`,[auth.tenantId,a.branch_id,input.assetId,input.workOrderId??null,money(input.amountMinor,"IMPROVEMENT_AMOUNT").toString(),input.usefulLifeChange??null,input.residualValueChangeMinor??null,input.sourceFingerprint??fp(input),auth.userId]); return r.rows[0]; })); }
  async improvementStatus(auth:AccessClaims,id:string,target:string,input:any,key:string,requestId:string) { return this.db.transaction(async c=>this.idem(c,auth,`improvement.${target.toLowerCase()}`,key,{id,...input},async()=>{ const old=(await c.query<any>(`SELECT * FROM asset_capital_improvements WHERE tenant_id=$1 AND id=$2 FOR UPDATE`,[auth.tenantId,id])).rows[0]; if(!old) throw new NotFoundException({code:"ASSET_IMPROVEMENT_NOT_FOUND"}); if(!transitions.improvement[target]?.includes(old.status)) throw new ConflictException({code:"ASSET_IMPROVEMENT_STATUS_INVALID"}); if(target==='APPROVED'&&old.requested_by_user_id===auth.userId) throw new ForbiddenException({code:"ASSET_IMPROVEMENT_AMOUNT_EXCEEDED"}); if(target==='CAPITALIZED') await c.query(`UPDATE assets SET gross_carrying_amount_minor=gross_carrying_amount_minor+$3,version=version+1 WHERE tenant_id=$1 AND id=$2`,[auth.tenantId,old.asset_id,old.amount_minor]); return (await c.query<any>(`UPDATE asset_capital_improvements SET status=$3,approved_by_user_id=CASE WHEN $3='APPROVED' THEN $4 ELSE approved_by_user_id END,version=version+1 WHERE tenant_id=$1 AND id=$2 RETURNING *`,[auth.tenantId,id,target,auth.userId])).rows[0]; })); }
  async listDisposals(auth:AccessClaims) { this.guard(auth); return (await this.db.query<any>(`SELECT * FROM asset_disposals WHERE tenant_id=$1 ORDER BY created_at DESC`,[auth.tenantId])).rows; }
  async createDisposal(auth:AccessClaims,input:any,key:string,requestId:string) { this.guard(auth); return this.db.transaction(async c=>this.idem(c,auth,"disposal.create",key,input,async()=>{ const a=(await c.query<any>(`SELECT * FROM assets WHERE tenant_id=$1 AND id=$2 FOR UPDATE`,[auth.tenantId,input.assetId])).rows[0]; if(!a) throw new NotFoundException({code:"ASSET_NOT_FOUND"}); this.scope(auth,a.branch_id); if(['DISPOSED','RETIRED','CANCELLED'].includes(a.status)) throw new ConflictException({code:"ASSET_DISPOSAL_ALREADY_COMPLETED"}); const rr=(await c.query<any>(`INSERT INTO asset_retirement_requests(tenant_id,asset_id,method,reason,requested_by_user_id) VALUES($1,$2,$3,$4,$5) RETURNING *`,[auth.tenantId,input.assetId,required(input.method,"disposal_method").toUpperCase(),required(input.reason,"reason"),auth.userId])).rows[0]; return (await c.query<any>(`INSERT INTO asset_disposals(tenant_id,retirement_request_id,asset_id,proceeds_minor,disposal_cost_minor,evidence_json,requested_by_user_id) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *`,[auth.tenantId,rr.id,input.assetId,money(input.proceedsMinor??0).toString(),money(input.disposalCostMinor??0).toString(),JSON.stringify(input.evidence??{}),auth.userId])).rows[0]; })); }
  async disposalStatus(auth:AccessClaims,id:string,target:string,input:any,key:string,requestId:string) { return this.db.transaction(async c=>this.idem(c,auth,`disposal.${target.toLowerCase()}`,key,{id,...input},async()=>{ const old=(await c.query<any>(`SELECT d.*,a.branch_id,a.gross_carrying_amount_minor,a.accumulated_depreciation_minor,a.accumulated_impairment_minor FROM asset_disposals d JOIN assets a ON a.tenant_id=d.tenant_id AND a.id=d.asset_id WHERE d.tenant_id=$1 AND d.id=$2 FOR UPDATE`,[auth.tenantId,id])).rows[0]; if(!old) throw new NotFoundException({code:"ASSET_DISPOSAL_NOT_FOUND"}); this.scope(auth,old.branch_id); if(!transitions.disposal[target]?.includes(old.status)) throw new ConflictException({code:"ASSET_DISPOSAL_STATUS_INVALID"}); if(target==='APPROVED'&&old.requested_by_user_id===auth.userId) throw new ForbiddenException({code:"ASSET_DISPOSAL_SELF_APPROVAL_DENIED"}); let gain=old.gain_loss_minor; if(target==='COMPLETED'){ const nbv=BigInt(old.gross_carrying_amount_minor)-BigInt(old.accumulated_depreciation_minor)-BigInt(old.accumulated_impairment_minor); gain=BigInt(old.proceeds_minor)-BigInt(old.disposal_cost_minor)-nbv; await c.query(`UPDATE assets SET status='DISPOSED',disposal_date=current_date,version=version+1 WHERE tenant_id=$1 AND id=$2 AND status NOT IN('DISPOSED','CANCELLED')`,[auth.tenantId,old.asset_id]); } const n=(await c.query<any>(`UPDATE asset_disposals SET status=$3,gain_loss_minor=$4,approved_by_user_id=CASE WHEN $3='APPROVED' THEN $5 ELSE approved_by_user_id END,version=version+1 WHERE tenant_id=$1 AND id=$2 RETURNING *`,[auth.tenantId,id,target,gain?.toString()??null,auth.userId])).rows[0]; await c.query(`UPDATE asset_retirement_requests SET status=$3,approved_by_user_id=CASE WHEN $3='APPROVED' THEN $4 ELSE approved_by_user_id END,version=version+1 WHERE tenant_id=$1 AND id=$2`,[auth.tenantId,old.retirement_request_id,target==='COMPLETED'?'COMPLETED':target,auth.userId]); await c.query(`INSERT INTO asset_disposal_history(tenant_id,disposal_id,from_status,to_status,actor_user_id,reason) VALUES($1,$2,$3,$4,$5,$6)`,[auth.tenantId,id,old.status,target,auth.userId,input?.reason??null]); return n; })); }

  async listWarranties(auth:AccessClaims,assetId?:string) { this.guard(auth); return (await this.db.query<any>(`SELECT * FROM asset_warranties WHERE tenant_id=$1 AND ($2::uuid IS NULL OR asset_id=$2) ORDER BY end_date`,[auth.tenantId,assetId??null])).rows; }
  async createWarranty(auth:AccessClaims,assetId:string,input:any,key:string,requestId:string) { this.guard(auth); await this.getAsset(auth,assetId); return this.db.transaction(async c=>this.idem(c,auth,"warranty.create",key,{assetId,...input},async()=>{ const r=await c.query<any>(`INSERT INTO asset_warranties(tenant_id,asset_id,vendor_id,provider_name,start_date,end_date,coverage_json) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *`,[auth.tenantId,assetId,input.vendorId??null,input.providerName??null,input.startDate,input.endDate,JSON.stringify(input.coverage??{})]); return r.rows[0]; })); }
  async listOpeningImports(auth:AccessClaims) { this.guard(auth); return (await this.db.query<any>(`SELECT * FROM asset_opening_imports WHERE tenant_id=$1 ORDER BY created_at DESC`,[auth.tenantId])).rows; }
  async createOpeningImport(auth:AccessClaims,input:any,key:string,requestId:string) { this.guard(auth); return this.db.transaction(async c=>this.idem(c,auth,"opening_import.create",key,input,async()=>{ const checksum=required(input.checksum,"checksum"); const existing=await c.query(`SELECT 1 FROM asset_opening_imports WHERE tenant_id=$1 AND checksum=$2`,[auth.tenantId,checksum]); if(existing.rowCount) throw new ConflictException({code:"ASSET_OPENING_IMPORT_DUPLICATE"}); const r=await c.query<any>(`INSERT INTO asset_opening_imports(tenant_id,cutover_date,checksum,row_count,requested_by_user_id) VALUES($1,$2,$3,$4,$5) RETURNING *`,[auth.tenantId,input.cutoverDate,checksum,input.rows?.length??0,auth.userId]); for(const [i,row] of (input.rows??[]).entries()) await c.query(`INSERT INTO asset_opening_import_rows(tenant_id,import_id,row_no,asset_code,branch_id,category_id,name,currency,gross_amount_minor,accumulated_depreciation_minor,residual_value_minor,useful_life_periods,in_service_date) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13)`,[auth.tenantId,r.rows[0].id,i+1,row.assetCode,row.branchId,row.categoryId,row.name,row.currency,money(row.grossAmountMinor).toString(),money(row.accumulatedDepreciationMinor??0).toString(),money(row.residualValueMinor??0).toString(),row.usefulLifePeriods,row.inServiceDate??null]); return r.rows[0]; })); }
  async openingImportStatus(auth:AccessClaims,id:string,target:string,input:any,key:string,requestId:string) { return this.db.transaction(async c=>this.idem(c,auth,`opening_import.${target.toLowerCase()}`,key,{id,...input},async()=>{ const old=(await c.query<any>(`SELECT * FROM asset_opening_imports WHERE tenant_id=$1 AND id=$2 FOR UPDATE`,[auth.tenantId,id])).rows[0]; if(!old) throw new NotFoundException({code:"ASSET_OPENING_IMPORT_INVALID"}); if(!transitions.import[target]?.includes(old.status)) throw new ConflictException({code:"ASSET_OPENING_IMPORT_INVALID"}); if(target==='APPROVED'&&old.requested_by_user_id===auth.userId) throw new ForbiddenException({code:"CAPITALIZATION_SELF_APPROVAL_DENIED"}); if(target==='PROCESSED'){ const rows=(await c.query<any>(`SELECT * FROM asset_opening_import_rows WHERE tenant_id=$1 AND import_id=$2 FOR UPDATE`,[auth.tenantId,id])).rows; for(const row of rows){ const a=await this.createAssetWithin(c,auth,{branchId:row.branch_id,categoryId:row.category_id,name:row.name,assetCode:row.asset_code,currency:row.currency,grossCarryingAmountMinor:row.gross_amount_minor,inServiceDate:row.in_service_date,usefulLifePeriods:row.useful_life_periods},requestId); await c.query(`UPDATE assets SET accumulated_depreciation_minor=$3,status='ACTIVE' WHERE tenant_id=$1 AND id=$2`,[auth.tenantId,a.id,row.accumulated_depreciation_minor]); await c.query(`UPDATE asset_opening_import_rows SET validated=true,created_asset_id=$3 WHERE tenant_id=$1 AND id=$2`,[auth.tenantId,row.id,a.id]); } } return (await c.query<any>(`UPDATE asset_opening_imports SET status=$3,approved_by_user_id=CASE WHEN $3='APPROVED' THEN $4 ELSE approved_by_user_id END,version=version+1 WHERE tenant_id=$1 AND id=$2 RETURNING *`,[auth.tenantId,id,target,auth.userId])).rows[0]; })); }

  async report(auth:AccessClaims,kind:string,input:any) { this.guard(auth); const branchFilter=auth.branchIds.length?` AND a.branch_id=ANY($2::uuid[])`:""; const vals:any[]=[auth.tenantId]; if(auth.branchIds.length) vals.push(auth.branchIds); if(kind==='register') return (await this.db.query<any>(`SELECT a.*,c.code category_code,c.name category_name,(a.gross_carrying_amount_minor-a.accumulated_depreciation_minor-a.accumulated_impairment_minor) nbv_minor FROM assets a JOIN asset_categories c ON c.tenant_id=a.tenant_id AND c.id=a.category_id WHERE a.tenant_id=$1${branchFilter} ORDER BY a.asset_code`,vals)).rows; if(kind==='net-book-value') return (await this.db.query<any>(`SELECT COALESCE(sum(gross_carrying_amount_minor),0) gross_minor,COALESCE(sum(accumulated_depreciation_minor),0) accumulated_depreciation_minor,COALESCE(sum(accumulated_impairment_minor),0) impairment_minor,COALESCE(sum(gross_carrying_amount_minor-accumulated_depreciation_minor-accumulated_impairment_minor),0) nbv_minor FROM assets a WHERE a.tenant_id=$1${branchFilter}`,vals)).rows[0]; if(kind==='depreciation') return (await this.db.query<any>(`SELECT * FROM asset_depreciation_schedules WHERE tenant_id=$1 ORDER BY period_start`,[auth.tenantId])).rows; if(kind==='maintenance-due') return (await this.db.query<any>(`SELECT * FROM asset_maintenance_work_orders WHERE tenant_id=$1 AND status NOT IN('COMPLETED','VERIFIED','CANCELLED') ORDER BY scheduled_start_at`,[auth.tenantId])).rows; if(kind==='warranty-expiry') return (await this.db.query<any>(`SELECT * FROM asset_warranties WHERE tenant_id=$1 ORDER BY end_date`,[auth.tenantId])).rows; if(kind==='disposal') return (await this.db.query<any>(`SELECT * FROM asset_disposals WHERE tenant_id=$1 ORDER BY created_at DESC`,[auth.tenantId])).rows; if(kind==='impairment') return (await this.db.query<any>(`SELECT * FROM asset_impairment_requests WHERE tenant_id=$1 ORDER BY created_at DESC`,[auth.tenantId])).rows; if(kind==='capex') return (await this.db.query<any>(`SELECT * FROM asset_capitalization_requests WHERE tenant_id=$1 ORDER BY created_at DESC`,[auth.tenantId])).rows; return (await this.db.query<any>(`SELECT * FROM assets WHERE tenant_id=$1${branchFilter} ORDER BY asset_code`,vals)).rows; }
  async createExport(auth:AccessClaims,input:any,key:string,requestId:string) { this.guard(auth); return this.db.transaction(async c=>this.idem(c,auth,"export.create",key,input,async()=>{ const r=await c.query<any>(`INSERT INTO asset_export_jobs(tenant_id,filter_json,requested_by_user_id) VALUES($1,$2,$3) RETURNING *`,[auth.tenantId,JSON.stringify(input??{}),auth.userId]); return r.rows[0]; })); }
  async getExport(auth:AccessClaims,id:string) { this.guard(auth); const r=await this.db.query<any>(`SELECT * FROM asset_export_jobs WHERE tenant_id=$1 AND id=$2`,[auth.tenantId,id]); if(!r.rows[0]) throw new NotFoundException({code:"ASSET_NOT_FOUND"}); return r.rows[0]; }
}
