"use client";

import CustomerCreate from "./sprint19-wave3/customer-create";
import CustomerDetail from "./sprint19-wave3/customer-detail";
import CustomerDirectory from "./sprint19-wave3/customer-directory";
import BenefitsWallet from "./sprint19-wave3/benefits-wallet";
import CustomerBenefitsPage from "./sprint19-wave3/customer-benefits/customer-benefits-page";
import LoyaltyPrograms, { CustomerLoyalty, LoyaltyAdjustments } from "./sprint19-wave3/loyalty";
import MembershipTiers, { CustomerMembership } from "./sprint19-wave3/membership";
import MembershipHub from "./sprint19-wave3/membership-hub";
import PackageCatalog, { PackageDetail, PackageEntitlementDetail } from "./sprint19-wave3/packages";
import PackageHub from "./sprint19-wave3/package-hub";
import { VoucherCampaignDetail, VoucherCampaigns } from "./sprint19-wave3/vouchers";
import VoucherHub from "./sprint19-wave3/voucher-hub";
import { GiftCardDetail, GiftCardIssuance, GiftCardProducts, GiftCards } from "./sprint19-wave3/gift-cards";
import { CustomerCredit, StoredValueAdjustments } from "./sprint19-wave3/customer-credit";
import { CommunicationMessages, CommunicationRules, CommunicationTemplates } from "./sprint19-wave3/communications";
import { MarketingCampaignDetail, MarketingCampaigns, MarketingSegments } from "./sprint19-wave3/marketing";
import { ReviewRoute } from "./sprint19-wave3/reviews";
import { RecoveryRoute } from "./sprint19-wave3/service-recovery";
import CustomerCareHub from "./sprint19-wave3/customer-care-hub";
import { isWave3CustomerEngagementPath, isWave3CustomerPath, isWave3Path } from "./sprint19-wave3/routes";

export { isWave3CustomerEngagementPath, isWave3CustomerPath, isWave3Path };

export default function Sprint19Wave3CustomerScreen({ pathname }: { pathname: string }) {
  if (pathname === "/admin/benefits" || pathname === "/admin/benefits/") return <CustomerBenefitsPage />;
  const benefitCustomer = pathname.match(/^\/admin\/benefits\/customers\/([^/]+)$/);
  if (benefitCustomer) return <BenefitsWallet customerId={benefitCustomer[1] ?? ""} />;
  if (pathname === "/admin/loyalty/programs") return <LoyaltyPrograms />;
  if (pathname === "/admin/loyalty/adjustments") return <LoyaltyAdjustments />;
  const loyaltyCustomer = pathname.match(/^\/admin\/loyalty\/customers\/([^/]+)$/);
  if (loyaltyCustomer) return <CustomerLoyalty customerId={loyaltyCustomer[1] ?? ""} />;
  if (pathname === "/admin/membership" || pathname === "/admin/membership/") return <MembershipHub />;
  if (pathname === "/admin/membership/tiers") return <MembershipTiers />;
  const membershipCustomer = pathname.match(/^\/admin\/membership\/customers\/([^/]+)$/);
  if (membershipCustomer) return <CustomerMembership customerId={membershipCustomer[1] ?? ""} />;
  if (pathname === "/admin/packages/catalog") return <PackageCatalog />;
  const packageDetail = pathname.match(/^\/admin\/packages\/catalog\/([^/]+)$/);
  if (packageDetail) return <PackageDetail packageId={packageDetail[1] ?? ""} />;
  if (pathname === "/admin/packages/entitlements") return <PackageHub />;
  const entitlementDetail = pathname.match(/^\/admin\/packages\/entitlements\/([^/]+)$/);
  if (entitlementDetail) return <PackageEntitlementDetail entitlementId={entitlementDetail[1] ?? ""} />;
  if (pathname === "/admin/vouchers/campaigns") return <VoucherCampaigns />;
  const voucherCampaign = pathname.match(/^\/admin\/vouchers\/campaigns\/([^/]+)$/);
  if (voucherCampaign) return <VoucherCampaignDetail campaignId={voucherCampaign[1] ?? ""} />;
  if (pathname === "/admin/vouchers/codes") return <VoucherHub />;
  if (pathname === "/admin/gift-cards/products") return <GiftCardProducts />;
  if (pathname === "/admin/gift-cards/issuance") return <GiftCardIssuance />;
  if (pathname === "/admin/gift-cards") return <GiftCards />;
  const giftCard = pathname.match(/^\/admin\/gift-cards\/([^/]+)$/);
  if (giftCard) return <GiftCardDetail giftCardId={giftCard[1] ?? ""} />;
  if (pathname === "/admin/customer-credit") return <CustomerCredit />;
  if (pathname === "/admin/stored-value/adjustments") return <StoredValueAdjustments />;
  if (pathname === "/admin/customer-care") return <CustomerCareHub />;
  if (pathname === "/admin/communications") return <CommunicationMessages />;
  if (pathname === "/admin/communications/templates") return <CommunicationTemplates />;
  if (pathname === "/admin/communications/rules") return <CommunicationRules />;
  if (pathname === "/admin/communications/messages") return <CommunicationMessages />;
  if (pathname === "/admin/communications/suppressions") return <CommunicationMessages suppressions />;
  if (pathname === "/admin/marketing/segments") return <MarketingSegments />;
  if (pathname === "/admin/marketing") return <MarketingCampaigns />;
  if (pathname === "/admin/marketing/campaigns") return <MarketingCampaigns />;
  const campaign = pathname.match(/^\/admin\/marketing\/campaigns\/([^/]+)$/);
  if (campaign) return <MarketingCampaignDetail campaignId={campaign[1] ?? ""} />;
  if (pathname === "/admin/reviews" || pathname === "/admin/review-requests" || /^\/admin\/reviews\/[^/]+$/.test(pathname)) return <ReviewRoute pathname={pathname} />;
  if (pathname === "/admin/service-recovery" || /^\/admin\/service-recovery\/[^/]+$/.test(pathname)) return <RecoveryRoute pathname={pathname} />;
  if (pathname === "/admin/customers/new") return <CustomerCreate />;
  const engagement = pathname.match(/^\/admin\/customers\/([^/]+)\/engagement$/);
  if (engagement && isWave3CustomerEngagementPath(pathname)) return <CustomerCareHub customerId={engagement[1] ?? ""} />;
  const detail = pathname.match(/^\/admin\/customers\/([^/]+)$/);
  if (detail) return <CustomerDetail customerId={detail[1] ?? ""} />;
  return <CustomerDirectory />;
}
