export const locales = ["vi-VN", "en-US"] as const;
export type Locale = (typeof locales)[number];

export const messages = {
  "vi-VN": {
    appName: "Nailsoft",
    loading: "\u0110ang t\u1ea3i...",
    empty: "Ch\u01b0a c\u00f3 d\u1eef li\u1ec7u",
    error: "\u0110\u00e3 x\u1ea3y ra l\u1ed7i",
    retry: "Th\u1eed l\u1ea1i",
    refresh: "L\u00e0m m\u1edbi",
    forbidden: "B\u1ea1n kh\u00f4ng c\u00f3 quy\u1ec1n truy c\u1eadp n\u1ed9i dung n\u00e0y.",
    unavailable: "D\u1ecbch v\u1ee5 hi\u1ec7n kh\u00f4ng kh\u1ea3 d\u1ee5ng.",
    save: "L\u01b0u",
    cancel: "H\u1ee7y",
    close: "\u0110\u00f3ng",
    search: "T\u00ecm ki\u1ebfm",
    notifications: "Th\u00f4ng b\u00e1o",
    workspace: "Kh\u00f4ng gian l\u00e0m vi\u1ec7c",
    branch: "Chi nh\u00e1nh",
    more: "Th\u00eam",
    back: "Quay l\u1ea1i",
    navigation: "\u0110i\u1ec1u h\u01b0\u1edbng",
    skipToContent: "B\u1ecf qua \u0111\u1ebfn n\u1ed9i dung ch\u00ednh",
    status: "Tr\u1ea1ng th\u00e1i",
    profile: "H\u1ed3 s\u01a1",
    signOut: "\u0110\u0103ng xu\u1ea5t",
    menu: "M\u1edf menu",
    dashboard: "T\u1ed5ng quan",
    calendar: "L\u1ecbch h\u1eb9n",
    bookings: "\u0110\u1eb7t l\u1ecbch",
    operations: "V\u1eadn h\u00e0nh",
    pos: "B\u00e1n h\u00e0ng",
    customers: "Kh\u00e1ch h\u00e0ng",
    team: "Nh\u00e2n s\u1ef1",
    inventory: "Kho h\u00e0ng",
    procurement: "Mua h\u00e0ng",
    assets: "T\u00e0i s\u1ea3n",
    finance: "T\u00e0i ch\u00ednh",
    accounting: "K\u1ebf to\u00e1n",
    analytics: "Ph\u00e2n t\u00edch",
    marketing: "Ti\u1ebfp th\u1ecb",
    platform: "N\u1ec1n t\u1ea3ng",
    designSystem: "H\u1ec7 th\u1ed1ng thi\u1ebft k\u1ebf",
    offline: "B\u1ea1n \u0111ang ngo\u1ea1i tuy\u1ebfn. Thao t\u00e1c n\u00e0y c\u1ea7n k\u1ebft n\u1ed1i m\u1ea1ng.",
    stale: "D\u1eef li\u1ec7u c\u00f3 th\u1ec3 ch\u01b0a l\u00e0 m\u1edbi nh\u1ea5t. \u0110ang l\u00e0m m\u1edbi...",
    partial: "M\u1ed9t ph\u1ea7n d\u1eef li\u1ec7u ch\u01b0a t\u1ea3i \u0111\u01b0\u1ee3c.",
    workspaceGroup: "Kh\u00f4ng gian",
    businessGroup: "Nghi\u1ec7p v\u1ee5",
    controlGroup: "Ki\u1ec3m so\u00e1t",
    primaryAction: "Thao t\u00e1c ch\u00ednh",
    saveChanges: "L\u01b0u thay \u0111\u1ed5i",
    review: "Xem l\u1ea1i",
    delete: "X\u00f3a",
    active: "Ho\u1ea1t \u0111\u1ed9ng",
    needsReview: "C\u1ea7n xem l\u1ea1i",
    blocked: "B\u1ecb ch\u1eb7n",
    inProgress: "\u0110ang x\u1eed l\u00fd",
    asyncStates: "Tr\u1ea1ng th\u00e1i b\u1ea5t \u0111\u1ed3ng b\u1ed9",
    chartFallback: "Bi\u1ec3u \u0111\u1ed3 v\u00e0 b\u1ea3ng d\u1eef li\u1ec7u",
    revenueByDay: "Doanh thu theo ng\u00e0y",
    noAppointmentsYet: "Ch\u01b0a c\u00f3 l\u1ecbch h\u1eb9n",
    createBookingOrChangeDate: "T\u1ea1o l\u1ecbch h\u1eb9n ho\u1eb7c \u0111\u1ed5i ng\u00e0y \u0111ang ch\u1ecdn.",
    forms: "Bi\u1ec3u m\u1eabu",
    searchAndFilters: "T\u00ecm ki\u1ebfm v\u00e0 b\u1ed9 l\u1ecdc",
    dataDisplay: "Hi\u1ec3n th\u1ecb d\u1eef li\u1ec7u",
    overlays: "L\u1edbp ph\u1ee7 v\u00e0 th\u00f4ng b\u00e1o",
    progressAndHistory: "Ti\u1ebfn \u0111\u1ed9 v\u00e0 l\u1ecbch s\u1eed",
    chartDescription: "B\u1ea3ng thay th\u1ebf c\u00f3 th\u1ec3 truy c\u1eadp cho d\u1eef li\u1ec7u xu h\u01b0\u1edbng.",
    chooseLanguage: "Ch\u1ecdn ng\u00f4n ng\u1eef",
    loadingState: "\u0110ang t\u1ea3i",
    emptyState: "Tr\u1ed1ng",
    errorState: "L\u1ed7i",
    forbiddenState: "T\u1eeb ch\u1ed1i quy\u1ec1n",
    staleState: "C\u00f3 th\u1ec3 c\u0169",
    offlineState: "Ngo\u1ea1i tuy\u1ebfn",
    partialState: "T\u1ea3i m\u1ed9t ph\u1ea7n",
    sampleCustomer: "Kh\u00e1ch h\u00e0ng m\u1eabu",
    service: "D\u1ecbch v\u1ee5",
    amount: "S\u1ed1 ti\u1ec1n",
    statusLabel: "Tr\u1ea1ng th\u00e1i",
    next: "Ti\u1ebfp",
    previous: "Tr\u01b0\u1edbc",
    openDialog: "M\u1edf h\u1ed9p tho\u1ea1i",
    closeDialog: "\u0110\u00f3ng h\u1ed9p tho\u1ea1i",
  },
  "en-US": {
    appName: "Nailsoft",
    loading: "Loading...",
    empty: "No data yet",
    error: "Something went wrong",
    retry: "Retry",
    refresh: "Refresh",
    forbidden: "You do not have permission to access this content.",
    unavailable: "This service is currently unavailable.",
    save: "Save",
    cancel: "Cancel",
    close: "Close",
    search: "Search",
    notifications: "Notifications",
    workspace: "Workspace",
    branch: "Branch",
    more: "More",
    back: "Back",
    navigation: "Navigation",
    skipToContent: "Skip to main content",
    status: "Status",
    profile: "Profile",
    signOut: "Sign out",
    menu: "Open menu",
    dashboard: "Dashboard",
    calendar: "Calendar",
    bookings: "Bookings",
    operations: "Operations",
    pos: "Point of sale",
    customers: "Customers",
    team: "Team",
    inventory: "Inventory",
    procurement: "Procurement",
    assets: "Assets",
    finance: "Finance",
    accounting: "Accounting",
    analytics: "Analytics",
    marketing: "Marketing",
    platform: "Platform",
    designSystem: "Design system",
    offline: "You are offline. This action requires an internet connection.",
    stale: "This data may be outdated. Refreshing...",
    partial: "Some data could not be loaded.",
    workspaceGroup: "Workspace",
    businessGroup: "Business",
    controlGroup: "Control",
    primaryAction: "Primary action",
    saveChanges: "Save changes",
    review: "Review",
    delete: "Delete",
    active: "Active",
    needsReview: "Needs review",
    blocked: "Blocked",
    inProgress: "In progress",
    asyncStates: "Async states",
    chartFallback: "Chart and table fallback",
    revenueByDay: "Revenue by day",
    noAppointmentsYet: "No appointments yet",
    createBookingOrChangeDate: "Create a booking or change the selected date.",
    forms: "Forms",
    searchAndFilters: "Search and filters",
    dataDisplay: "Data display",
    overlays: "Overlays and feedback",
    progressAndHistory: "Progress and history",
    chartDescription: "An accessible table fallback for trend data.",
    chooseLanguage: "Choose language",
    loadingState: "Loading",
    emptyState: "Empty",
    errorState: "Error",
    forbiddenState: "Forbidden",
    staleState: "Stale",
    offlineState: "Offline",
    partialState: "Partial",
    sampleCustomer: "Sample customer",
    service: "Service",
    amount: "Amount",
    statusLabel: "Status",
    next: "Next",
    previous: "Previous",
    openDialog: "Open dialog",
    closeDialog: "Close dialog",
  },
} as const;

export type MessageKey = keyof (typeof messages)["en-US"];
export const translate = (locale: Locale, key: MessageKey): string => messages[locale][key];

export const formatCurrency = (valueMinor: number | bigint, currency: string, locale: Locale) =>
  new Intl.NumberFormat(locale, { style: "currency", currency, maximumFractionDigits: currency === "VND" ? 0 : 2 }).format(Number(valueMinor) / 100);
export const formatDate = (value: Date | string, locale: Locale, timeZone?: string) =>
  new Intl.DateTimeFormat(locale, { dateStyle: "medium", ...(timeZone ? { timeZone } : {}) }).format(new Date(value));
export const formatDateTime = (value: Date | string, locale: Locale, timeZone?: string) =>
  new Intl.DateTimeFormat(locale, { dateStyle: "medium", timeStyle: "short", ...(timeZone ? { timeZone } : {}) }).format(new Date(value));
export const formatNumber = (value: number, locale: Locale) => new Intl.NumberFormat(locale).format(value);
export const formatPercent = (value: number, locale: Locale) => new Intl.NumberFormat(locale, { style: "percent", maximumFractionDigits: 1 }).format(value);
export const formatDuration = (seconds: number, locale: Locale) => {
  const minutes = Math.max(0, Math.round(seconds / 60));
  const hours = Math.floor(minutes / 60);
  const remainder = minutes % 60;
  if (locale === "vi-VN") return (hours ? String(hours) + " gi\u1edd " : "") + String(remainder) + " ph\u00fat";
  return (hours ? String(hours) + "h " : "") + String(remainder) + "m";
};

/** Detects common UTF-8-as-Windows-1252 corruption before it reaches a UI. */
export const containsMojibake = (value: string) =>
  /(?:\u00c3[\u0080-\u00bf\u0192\u201a\u201e]|\u00c2[\u0080-\u00bf]|\u00c4[\u0080-\u00bf]|\u00c5[\u0080-\u00bf]|\u00e2[\u0080-\u00bf\u20ac\u201a\u201e\u00a2\u00a6]|\u00ef\u00bf\u00bd)/.test(value);
