/* eslint-disable @typescript-eslint/no-explicit-any */
"use client";

import { FormEvent } from "react";
import { BenefitShell, BenefitStatePanel, CustomerBenefitHeader, formatDate, formatInteger, localized, rows, statusLabel, useBenefitMutation, useBenefitResource } from "./benefit-shared";

function TierForm({ onSaved }: { onSaved: () => void }) {
  const mutation = useBenefitMutation();
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const form = new FormData(event.currentTarget);
    const discountPercent = Number(form.get("discountPercent"));
    const result = await mutation.submit("/v1/membership-tiers", { code: String(form.get("code")), name: { "vi-VN": String(form.get("name")), "en-US": String(form.get("name")) }, qualificationType: String(form.get("qualificationType")), qualificationThreshold: Number(form.get("threshold")), benefits: [{ type: "PERCENT_DISCOUNT", value: Math.round(discountPercent * 100) }], priority: Number(form.get("priority") ?? 0), effectiveFrom: new Date(String(form.get("effectiveFrom"))).toISOString() });
    if (result) { event.currentTarget.reset(); onSaved(); }
  }
  return <form className="s19-benefit-form" onSubmit={(event) => void submit(event)}><div className="s19-form-grid"><label className="s19-field"><span>Mã hạng nội bộ</span><input name="code" required /><small>Mã ổn định để hệ thống tham chiếu, không phải tên hiển thị.</small></label><label className="s19-field"><span>Tên hạng</span><input name="name" required /></label><label className="s19-field"><span>Điều kiện đạt hạng</span><select name="qualificationType"><option value="ROLLING_SPEND">Chi tiêu theo chu kỳ</option><option value="LIFETIME_SPEND">Tổng chi tiêu</option><option value="VISIT_COUNT">Số lượt ghé</option><option value="POINTS_EARNED">Điểm đã tích</option><option value="MANUAL">Thủ công</option></select></label><label className="s19-field"><span>Ngưỡng điều kiện</span><input name="threshold" type="number" min="0" required /><small>Đơn vị sẽ theo điều kiện: đồng, lượt ghé hoặc điểm.</small></label><label className="s19-field"><span>Mức giảm (%)</span><input name="discountPercent" type="number" min="0" max="100" step="0.01" required /><small>Nhập theo phần trăm hiển thị; máy chủ lưu theo đơn vị chính sách.</small></label><label className="s19-field"><span>Độ ưu tiên</span><input name="priority" type="number" defaultValue="0" /><small>Số càng cao được xét trước khi hệ thống đánh giá hạng.</small></label><label className="s19-field"><span>Hiệu lực từ</span><input name="effectiveFrom" type="datetime-local" required /></label></div><p className="s19-helper">Máy chủ vẫn là nguồn quyết định điều kiện, thời hạn và chồng lấn chính sách; màn hình chỉ gửi yêu cầu có kiểm tra.</p><button className="s19-button s19-button-primary" disabled={mutation.state === "submitting"}>Tạo hạng</button>{mutation.state === "success" ? <p className="s19-notice s19-notice-success" role="status">{mutation.message}</p> : mutation.state === "error" ? <p className="s19-notice s19-notice-danger" role="alert">{mutation.code ? `${mutation.code}: ` : ""}{mutation.message}</p> : null}</form>;
}

export default function MembershipTiers() {
  const resource = useBenefitResource("/v1/membership-tiers"); const values = rows(resource.data); const mutation = useBenefitMutation();
  async function deactivate(item: any) { const result = await mutation.submit(`/v1/membership-tiers/${item.id}/deactivate`, { version: Number(item.version ?? 1), reason: "Catalog lifecycle change" }); if (result) void resource.load(); }
  return <BenefitShell title="Membership tiers" eyebrow="MEMBERSHIP CATALOG"><section className="s19-card"><div className="s19-card-heading"><div><p className="s19-eyebrow">DANH MỤC HẠNG</p><h2>Điều kiện và quyền lợi từ máy chủ</h2></div></div><BenefitStatePanel resource={resource} label="membership tiers" />{resource.state === "ready" ? <div className="s19-benefit-table-wrap"><table className="s19-benefit-table"><thead><tr><th>Hạng</th><th>Điều kiện</th><th>Quyền lợi</th><th>Hiệu lực</th><th>Trạng thái</th><th>Thao tác</th></tr></thead><tbody>{values.map((item: any) => <tr key={item.id}><td data-label="Hạng"><strong>{localized(item.name, item.code)}</strong><small>{item.code}</small></td><td data-label="Điều kiện">{statusLabel(item.qualificationType ?? item.qualification_type)}<small>Ngưỡng {formatInteger(item.qualificationThreshold ?? item.qualification_threshold)}</small></td><td data-label="Quyền lợi">{rows(item.benefits).map((benefit: any) => `${statusLabel(benefit.type)} ${benefit.value}`).join(", ") || "Chính sách từ máy chủ"}</td><td data-label="Hiệu lực">{formatDate(item.effectiveFrom ?? item.effective_from)}</td><td data-label="Trạng thái"><span className="s19-status s19-status-info">{statusLabel(item.status)}</span></td><td data-label="Thao tác">{String(item.status).toUpperCase() === "ACTIVE" ? <button className="s19-button s19-button-small" type="button" disabled={mutation.state === "submitting"} onClick={() => void deactivate(item)}>Tạm ngừng</button> : <span className="s19-helper">Không có thao tác</span>}</td></tr>)}</tbody></table></div> : null}</section><section className="s19-card"><div className="s19-card-heading"><div><p className="s19-eyebrow">THAY ĐỔI CÓ KIỂM SOÁT</p><h2>Tạo hạng Membership</h2></div></div><TierForm onSaved={() => void resource.load()} /></section></BenefitShell>;
}

export function CustomerMembership({ customerId }: { customerId: string }) {
  const resource = useBenefitResource(`/v1/customers/${encodeURIComponent(customerId)}/membership`); const values = rows(resource.data);
  return <BenefitShell title="Customer membership history" eyebrow="CUSTOMER BENEFITS" backHref={`/admin/benefits/customers/${customerId}`}><CustomerBenefitHeader customerId={customerId} backHref={`/admin/benefits/customers/${customerId}`} /><section className="s19-card"><div className="s19-card-heading"><div><p className="s19-eyebrow">SERVER ASSIGNMENTS</p><h2>Tier history and effective periods</h2></div></div><BenefitStatePanel resource={resource} label="membership assignments" />{resource.state === "ready" ? <div className="s19-benefit-stack">{values.map((item: any) => <article className="s19-benefit-item" key={item.id}><div><strong>{localized(item.tierName ?? item.tier_name ?? item.name ?? item.code, "Membership tier")}</strong><span>{statusLabel(item.status)} · assignment {item.id}</span></div><div><small>From {formatDate(item.effectiveFrom ?? item.effective_from)}</small><small>To {formatDate(item.effectiveTo ?? item.effective_to)}</small></div></article>)}</div> : null}<p className="s19-helper">Tier status and effective dates are read from the membership service; the client does not recalculate eligibility.</p></section></BenefitShell>;
}
