/* eslint-disable @typescript-eslint/no-explicit-any */
"use client";

import { FormEvent } from "react";
import { BenefitShell, BenefitStatePanel, CustomerBenefitHeader, formatDate, formatInteger, localized, rows, statusLabel, useBenefitMutation, useBenefitResource } from "./benefit-shared";

function TierForm({ onSaved }: { onSaved: () => void }) {
  const mutation = useBenefitMutation();
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const form = new FormData(event.currentTarget);
    const result = await mutation.submit("/v1/membership-tiers", { code: String(form.get("code")), name: { "vi-VN": String(form.get("name")), "en-US": String(form.get("name")) }, qualificationType: String(form.get("qualificationType")), qualificationThreshold: Number(form.get("threshold")), benefits: [{ type: "PERCENT_DISCOUNT", value: Number(form.get("discount")) }], priority: Number(form.get("priority") ?? 0), effectiveFrom: new Date(String(form.get("effectiveFrom"))).toISOString() });
    if (result) { event.currentTarget.reset(); onSaved(); }
  }
  return <form className="s19-benefit-form" onSubmit={(event) => void submit(event)}><div className="s19-form-grid"><label className="s19-field"><span>Code</span><input name="code" required /></label><label className="s19-field"><span>Name</span><input name="name" required /></label><label className="s19-field"><span>Qualification</span><select name="qualificationType"><option value="ROLLING_SPEND">Rolling spend</option><option value="VISIT_COUNT">Visit count</option><option value="MANUAL">Manual</option></select></label><label className="s19-field"><span>Threshold</span><input name="threshold" type="number" min="0" required /></label><label className="s19-field"><span>Discount basis points</span><input name="discount" type="number" min="0" max="10000" required /></label><label className="s19-field"><span>Priority</span><input name="priority" type="number" defaultValue="0" /></label><label className="s19-field"><span>Effective from</span><input name="effectiveFrom" type="datetime-local" required /></label></div><button className="s19-button s19-button-primary" disabled={mutation.state === "submitting"}>Create tier</button>{mutation.state === "success" ? <p className="s19-notice s19-notice-success" role="status">{mutation.message}</p> : mutation.state === "error" ? <p className="s19-notice s19-notice-danger" role="alert">{mutation.code ? `${mutation.code}: ` : ""}{mutation.message}</p> : null}</form>;
}

export default function MembershipTiers() {
  const resource = useBenefitResource("/v1/membership-tiers"); const values = rows(resource.data); const mutation = useBenefitMutation();
  async function deactivate(item: any) { const result = await mutation.submit(`/v1/membership-tiers/${item.id}/deactivate`, { version: Number(item.version ?? 1), reason: "Catalog lifecycle change" }); if (result) void resource.load(); }
  return <BenefitShell title="Membership tiers" eyebrow="MEMBERSHIP CATALOG"><section className="s19-card"><div className="s19-card-heading"><div><p className="s19-eyebrow">TIER CATALOG</p><h2>Server-defined qualification and benefits</h2></div></div><BenefitStatePanel resource={resource} label="membership tiers" />{resource.state === "ready" ? <div className="s19-benefit-table-wrap"><table className="s19-benefit-table"><thead><tr><th>Tier</th><th>Qualification</th><th>Benefits</th><th>Effective</th><th>Status</th><th>Action</th></tr></thead><tbody>{values.map((item: any) => <tr key={item.id}><td data-label="Tier"><strong>{localized(item.name, item.code)}</strong><small>{item.code}</small></td><td data-label="Qualification">{statusLabel(item.qualificationType ?? item.qualification_type)}<small>Threshold {formatInteger(item.qualificationThreshold ?? item.qualification_threshold)}</small></td><td data-label="Benefits">{rows(item.benefits).map((benefit: any) => `${statusLabel(benefit.type)} ${benefit.value}`).join(", ") || "Server policy"}</td><td data-label="Effective">{formatDate(item.effectiveFrom ?? item.effective_from)}</td><td data-label="Status"><span className="s19-status s19-status-info">{statusLabel(item.status)}</span></td><td data-label="Action">{String(item.status).toUpperCase() === "ACTIVE" ? <button className="s19-button s19-button-small" type="button" disabled={mutation.state === "submitting"} onClick={() => void deactivate(item)}>Deactivate</button> : <span className="s19-helper">No action</span>}</td></tr>)}</tbody></table></div> : null}</section><section className="s19-card"><div className="s19-card-heading"><div><p className="s19-eyebrow">CONTROLLED CHANGE</p><h2>Create a membership tier</h2></div></div><TierForm onSaved={() => void resource.load()} /></section></BenefitShell>;
}

export function CustomerMembership({ customerId }: { customerId: string }) {
  const resource = useBenefitResource(`/v1/customers/${encodeURIComponent(customerId)}/membership`); const values = rows(resource.data);
  return <BenefitShell title="Customer membership history" eyebrow="CUSTOMER BENEFITS" backHref={`/admin/benefits/customers/${customerId}`}><CustomerBenefitHeader customerId={customerId} backHref={`/admin/benefits/customers/${customerId}`} /><section className="s19-card"><div className="s19-card-heading"><div><p className="s19-eyebrow">SERVER ASSIGNMENTS</p><h2>Tier history and effective periods</h2></div></div><BenefitStatePanel resource={resource} label="membership assignments" />{resource.state === "ready" ? <div className="s19-benefit-stack">{values.map((item: any) => <article className="s19-benefit-item" key={item.id}><div><strong>{localized(item.tierName ?? item.tier_name ?? item.name ?? item.code, "Membership tier")}</strong><span>{statusLabel(item.status)} · assignment {item.id}</span></div><div><small>From {formatDate(item.effectiveFrom ?? item.effective_from)}</small><small>To {formatDate(item.effectiveTo ?? item.effective_to)}</small></div></article>)}</div> : null}<p className="s19-helper">Tier status and effective dates are read from the membership service; the client does not recalculate eligibility.</p></section></BenefitShell>;
}
