/* eslint-disable @typescript-eslint/no-explicit-any */
"use client";

import { FormEvent, useEffect, useState } from "react";
import { BenefitShell, BenefitStatePanel, CustomerBenefitHeader, LedgerTable, formatDate, formatInteger, formatMoney, localized, rows, statusLabel, useBenefitMutation, useBenefitResource, useCustomerLookup } from "./benefit-shared";

function PackageForm({ onSaved }: { onSaved: () => void }) {
  const mutation = useBenefitMutation();
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const form = new FormData(event.currentTarget);
    const result = await mutation.submit("/v1/service-packages", { code: String(form.get("code")), name: { "vi-VN": String(form.get("name")), "en-US": String(form.get("name")) }, description: {}, grantedUnits: Number(form.get("grantedUnits")), unitsPerRedemption: 1, priceMinor: Number(form.get("priceMinor")), currency: "VND", validityDays: Number(form.get("validityDays")), refundPolicy: String(form.get("refundPolicy")), policy: {}, eligibility: [{ serviceId: String(form.get("serviceId")), unitsPerRedemption: 1 }] });
    if (result) { event.currentTarget.reset(); onSaved(); }
  }
  return <form className="s19-benefit-form" onSubmit={(event) => void submit(event)}><div className="s19-form-grid"><label className="s19-field"><span>Code</span><input name="code" required /></label><label className="s19-field"><span>Name</span><input name="name" required /></label><label className="s19-field"><span>Granted units</span><input name="grantedUnits" type="number" min="1" required /></label><label className="s19-field"><span>Price minor</span><input name="priceMinor" type="number" min="0" required /></label><label className="s19-field"><span>Validity days</span><input name="validityDays" type="number" min="1" required /></label><label className="s19-field"><span>Eligible service ID</span><input name="serviceId" required /></label><label className="s19-field"><span>Refund policy</span><select name="refundPolicy"><option value="RESTORE_UNIT">Restore unit</option><option value="DO_NOT_RESTORE">Do not restore</option><option value="MANUAL_REVIEW">Manual review</option></select></label></div><button className="s19-button s19-button-primary" disabled={mutation.state === "submitting"}>Create package</button>{mutation.state === "success" ? <p className="s19-notice s19-notice-success" role="status">{mutation.message}</p> : mutation.state === "error" ? <p className="s19-notice s19-notice-danger" role="alert">{mutation.code ? `${mutation.code}: ` : ""}{mutation.message}</p> : null}</form>;
}

export default function PackageCatalog() {
  const resource = useBenefitResource("/v1/service-packages"); const values = rows(resource.data); const mutation = useBenefitMutation();
  async function lifecycle(item: any) { const active = String(item.status).toUpperCase() === "ACTIVE"; const result = await mutation.submit(`/v1/service-packages/${item.id}/${active ? "deactivate" : "activate"}`, { version: Number(item.version ?? 1), reason: "Catalog lifecycle change" }); if (result) void resource.load(); }
  return <BenefitShell title="Service package catalog" eyebrow="PACKAGE CATALOG"><section className="s19-card"><div className="s19-card-heading"><div><p className="s19-eyebrow">CATALOG</p><h2>Entitlement products</h2></div><a className="s19-button s19-button-secondary" href="/admin/packages/entitlements">Customer entitlements</a></div><BenefitStatePanel resource={resource} label="service packages" />{resource.state === "ready" ? <div className="s19-benefit-table-wrap"><table className="s19-benefit-table"><thead><tr><th>Package</th><th>Units</th><th>Price</th><th>Validity</th><th>Status</th><th>Action</th></tr></thead><tbody>{values.map((item: any) => <tr key={item.id}><td data-label="Package"><a href={`/admin/packages/catalog/${item.id}`}><strong>{localized(item.name, item.code)}</strong></a><small>{item.code}</small></td><td data-label="Units">{formatInteger(item.grantedUnits ?? item.granted_units)}<small>per redemption {formatInteger(item.unitsPerRedemption ?? item.units_per_redemption)}</small></td><td data-label="Price">{formatMoney(item.priceMinor ?? item.price_minor, item.currency ?? "VND")}</td><td data-label="Validity">{formatInteger(item.validityDays ?? item.validity_days)} days</td><td data-label="Status"><span className="s19-status s19-status-info">{statusLabel(item.status)}</span></td><td data-label="Action"><button className="s19-button s19-button-small" type="button" disabled={mutation.state === "submitting"} onClick={() => void lifecycle(item)}>{String(item.status).toUpperCase() === "ACTIVE" ? "Deactivate" : "Activate"}</button></td></tr>)}</tbody></table></div> : null}</section><section className="s19-card"><div className="s19-card-heading"><div><p className="s19-eyebrow">CONTROLLED CHANGE</p><h2>Create a package draft</h2></div></div><p className="s19-helper">Pricing, units and eligibility are submitted to the package service; the browser does not calculate entitlement balances.</p><PackageForm onSaved={() => void resource.load()} /></section></BenefitShell>;
}

export function PackageDetail({ packageId }: { packageId: string }) {
  const resource = useBenefitResource(`/v1/service-packages/${encodeURIComponent(packageId)}`); const item = resource.data ?? {};
  return <BenefitShell title="Package detail" eyebrow="PACKAGE CATALOG" backHref="/admin/packages/catalog"><section className="s19-card"><div className="s19-card-heading"><div><p className="s19-eyebrow">READ MODEL</p><h2>{localized(item.name, item.code ?? "Service package")}</h2></div><span className="s19-status s19-status-info">{statusLabel(item.status)}</span></div><BenefitStatePanel resource={resource} label="package detail" />{resource.state === "ready" ? <dl className="s19-benefit-detail-list"><div><dt>Code</dt><dd>{item.code ?? "-"}</dd></div><div><dt>Granted units</dt><dd>{formatInteger(item.grantedUnits ?? item.granted_units)}</dd></div><div><dt>Units per redemption</dt><dd>{formatInteger(item.unitsPerRedemption ?? item.units_per_redemption)}</dd></div><div><dt>Price</dt><dd>{formatMoney(item.priceMinor ?? item.price_minor, item.currency ?? "VND")}</dd></div><div><dt>Validity</dt><dd>{formatInteger(item.validityDays ?? item.validity_days)} days</dd></div><div><dt>Refund policy</dt><dd>{statusLabel(item.refundPolicy ?? item.refund_policy)}</dd></div><div><dt>Version</dt><dd>{item.version ?? "-"}</dd></div></dl> : null}</section></BenefitShell>;
}

function CustomerPackageLookup() {
  const lookup = useCustomerLookup();
  return <section className="s19-card"><div className="s19-card-heading"><div><p className="s19-eyebrow">CUSTOMER ENTITLEMENTS</p><h2>Find a customer</h2></div></div><form className="s19-benefit-search" onSubmit={(event) => { event.preventDefault(); lookup.search(); }}><label className="s19-field"><span>Customer name, phone or email</span><input value={lookup.query} onChange={(event) => lookup.setQuery(event.target.value)} required /></label><button className="s19-button s19-button-primary">Search</button></form><BenefitStatePanel resource={lookup.resource} label="customers" />{lookup.resource.state === "ready" ? <div className="s19-benefit-customer-results">{lookup.results.length ? lookup.results.map((customer: any) => <a className="s19-benefit-result" href={`/admin/packages/entitlements?customerId=${customer.id}`} key={customer.id}><span><strong>{customer.displayName}</strong><small>{customer.phone ?? customer.email ?? "Contact hidden"}</small></span><span className="s19-status s19-status-info">Open</span></a>) : <p className="s19-helper">No matching customer found.</p>}</div> : null}</section>;
}

export function PackageEntitlements() {
  const [customerId, setCustomerId] = useState("");
  useEffect(() => { setCustomerId(new URLSearchParams(window.location.search).get("customerId") ?? ""); }, []);
  const resource = useBenefitResource(customerId ? `/v1/customers/${encodeURIComponent(customerId)}/packages` : null); const values = rows(resource.data);
  return <BenefitShell title="Customer package entitlements" eyebrow="CUSTOMER BENEFITS"><CustomerPackageLookup />{customerId ? <section className="s19-card"><CustomerBenefitHeader customerId={customerId} backHref="/admin/packages/entitlements" /><BenefitStatePanel resource={resource} label="package entitlements" />{resource.state === "ready" ? <div className="s19-benefit-stack">{values.map((item: any) => <a className="s19-benefit-item" href={`/admin/packages/entitlements/${item.id}`} key={item.id}><div><strong>{localized(item.name ?? item.code ?? item.packageProductId, "Service package")}</strong><span>{statusLabel(item.status)} · {item.code ?? item.packageProductId}</span></div><div><b>{formatInteger(item.availableUnits)} available</b><small>{formatInteger(item.reservedUnits)} reserved · expires {formatDate(item.expiresAt)}</small></div></a>)}</div> : null}</section> : null}</BenefitShell>;
}

export function PackageEntitlementDetail({ entitlementId }: { entitlementId: string }) {
  const resource = useBenefitResource(`/v1/customer-packages/${encodeURIComponent(entitlementId)}`); const ledger = useBenefitResource(`/v1/customer-packages/${encodeURIComponent(entitlementId)}/ledger`); const item = resource.data ?? {};
  return <BenefitShell title="Package entitlement detail" eyebrow="CUSTOMER BENEFITS" backHref="/admin/packages/entitlements"><section className="s19-card"><div className="s19-card-heading"><div><p className="s19-eyebrow">SERVER BALANCE</p><h2>{item.code ?? item.package_code ?? "Entitlement"}</h2></div><span className="s19-status s19-status-info">{statusLabel(item.status)}</span></div><BenefitStatePanel resource={resource} label="package entitlement" />{resource.state === "ready" ? <dl className="s19-benefit-metrics"><div><dt>Available units</dt><dd>{formatInteger(item.availableUnits ?? item.available_units)}</dd></div><div><dt>Reserved units</dt><dd>{formatInteger(item.reservedUnits ?? item.reserved_units)}</dd></div><div><dt>Consumed units</dt><dd>{formatInteger(item.consumedUnits ?? item.consumed_units)}</dd></div><div><dt>Expires</dt><dd>{formatDate(item.expiresAt ?? item.expires_at)}</dd></div></dl> : null}</section><section className="s19-card"><div className="s19-card-heading"><div><p className="s19-eyebrow">APPEND-ONLY</p><h2>Entitlement ledger</h2></div></div><BenefitStatePanel resource={ledger} label="entitlement ledger" />{ledger.state === "ready" ? <LedgerTable entries={rows(ledger.data)} emptyLabel="entitlement ledger entries" /> : null}</section></BenefitShell>;
}
