/* eslint-disable @typescript-eslint/no-explicit-any */
"use client";

import { FormEvent, useEffect, useState } from "react";
import { BenefitShell, BenefitStatePanel, CustomerBenefitHeader, LedgerTable, formatDate, formatInteger, formatMoney, localized, rows, statusLabel, useBenefitMutation, useBenefitResource, useCustomerLookup } from "./benefit-shared";

function PackageForm({ onSaved }: { onSaved: () => void }) {
  const mutation = useBenefitMutation();
  const services = useBenefitResource("/v1/services?status=ACTIVE&page=1&pageSize=50");
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const form = new FormData(event.currentTarget);
    const result = await mutation.submit("/v1/service-packages", { code: String(form.get("code")), name: { "vi-VN": String(form.get("name")), "en-US": String(form.get("name")) }, description: {}, grantedUnits: Number(form.get("grantedUnits")), unitsPerRedemption: 1, priceMinor: Number(form.get("priceMinor")), currency: "VND", validityDays: Number(form.get("validityDays")), refundPolicy: String(form.get("refundPolicy")), policy: {}, eligibility: [{ serviceId: String(form.get("serviceId")), unitsPerRedemption: 1 }] });
    if (result) { event.currentTarget.reset(); onSaved(); }
  }
  const serviceRows = rows(services.data);
  return <form className="s19-benefit-form" onSubmit={(event) => void submit(event)}><div className="s19-form-grid"><label className="s19-field"><span>Mã gói nội bộ</span><input name="code" required /><small>Mã dùng để tra cứu trong nghiệp vụ gói.</small></label><label className="s19-field"><span>Tên gói</span><input name="name" required /></label><label className="s19-field"><span>Số lượt cấp</span><input name="grantedUnits" type="number" min="1" required /></label><label className="s19-field"><span>Giá bán (VND)</span><input name="priceMinor" type="number" min="0" required /><small>Nhập số tiền nguyên; tiền tệ do máy chủ xác định.</small></label><label className="s19-field"><span>Số ngày hiệu lực</span><input name="validityDays" type="number" min="1" required /></label><label className="s19-field"><span>Dịch vụ đủ điều kiện</span><select name="serviceId" required disabled={services.state === "loading" || serviceRows.length === 0}><option value="">{services.state === "loading" ? "Đang tải dịch vụ…" : serviceRows.length ? "Chọn dịch vụ" : "Chưa có dịch vụ khả dụng"}</option>{serviceRows.map((service: any) => <option key={service.id} value={service.id}>{localized(service.name, service.code)}</option>)}</select><small>Chỉ dịch vụ thật từ danh mục hiện hành mới được chọn.</small></label><label className="s19-field"><span>Chính sách hoàn</span><select name="refundPolicy"><option value="RESTORE_UNIT">Khôi phục lượt</option><option value="DO_NOT_RESTORE">Không khôi phục</option><option value="MANUAL_REVIEW">Kiểm tra thủ công</option></select></label></div><button className="s19-button s19-button-primary" disabled={mutation.state === "submitting" || services.state === "loading" || serviceRows.length === 0}>Tạo gói</button>{mutation.state === "success" ? <p className="s19-notice s19-notice-success" role="status">{mutation.message}</p> : mutation.state === "error" ? <p className="s19-notice s19-notice-danger" role="alert">{mutation.code ? `${mutation.code}: ` : ""}{mutation.message}</p> : null}</form>;
}

export default function PackageCatalog() {
  const resource = useBenefitResource("/v1/service-packages"); const values = rows(resource.data); const mutation = useBenefitMutation();
  async function lifecycle(item: any) { const active = String(item.status).toUpperCase() === "ACTIVE"; const result = await mutation.submit(`/v1/service-packages/${item.id}/${active ? "deactivate" : "activate"}`, { version: Number(item.version ?? 1), reason: "Catalog lifecycle change" }); if (result) void resource.load(); }
  return <BenefitShell title="Service package catalog" eyebrow="PACKAGE CATALOG"><section className="s19-card"><div className="s19-card-heading"><div><p className="s19-eyebrow">DANH MỤC</p><h2>Sản phẩm quyền lợi</h2></div><a className="s19-button s19-button-secondary" href="/admin/packages/entitlements">Quyền lợi của khách</a></div><BenefitStatePanel resource={resource} label="service packages" />{resource.state === "ready" ? <div className="s19-benefit-table-wrap"><table className="s19-benefit-table"><thead><tr><th>Gói dịch vụ</th><th>Số lượt</th><th>Giá</th><th>Hiệu lực</th><th>Trạng thái</th><th>Thao tác</th></tr></thead><tbody>{values.map((item: any) => <tr key={item.id}><td data-label="Gói dịch vụ"><a href={`/admin/packages/catalog/${item.id}`}><strong>{localized(item.name, item.code)}</strong></a><small>{item.code}</small></td><td data-label="Số lượt">{formatInteger(item.grantedUnits ?? item.granted_units)}<small>mỗi lần dùng {formatInteger(item.unitsPerRedemption ?? item.units_per_redemption)}</small></td><td data-label="Giá">{formatMoney(item.priceMinor ?? item.price_minor, item.currency ?? "VND")}</td><td data-label="Hiệu lực">{formatInteger(item.validityDays ?? item.validity_days)} ngày</td><td data-label="Trạng thái"><span className="s19-status s19-status-info">{statusLabel(item.status)}</span></td><td data-label="Thao tác"><button className="s19-button s19-button-small" type="button" disabled={mutation.state === "submitting"} onClick={() => void lifecycle(item)}>{String(item.status).toUpperCase() === "ACTIVE" ? "Tạm ngừng" : "Kích hoạt"}</button></td></tr>)}</tbody></table></div> : null}</section><section className="s19-card"><div className="s19-card-heading"><div><p className="s19-eyebrow">THAY ĐỔI CÓ KIỂM SOÁT</p><h2>Tạo bản nháp gói dịch vụ</h2></div></div><p className="s19-helper">Giá, số lượt và điều kiện sử dụng được gửi tới dịch vụ gói; trình duyệt không tự tính số dư quyền lợi.</p><PackageForm onSaved={() => void resource.load()} /></section></BenefitShell>;
}

export function PackageDetail({ packageId }: { packageId: string }) {
  const resource = useBenefitResource(`/v1/service-packages/${encodeURIComponent(packageId)}`); const item = resource.data ?? {};
  return <BenefitShell title="Package detail" eyebrow="PACKAGE CATALOG" backHref="/admin/packages/catalog"><section className="s19-card"><div className="s19-card-heading"><div><p className="s19-eyebrow">READ MODEL</p><h2>{localized(item.name, item.code ?? "Gói dịch vụ")}</h2></div><span className="s19-status s19-status-info">{statusLabel(item.status)}</span></div><BenefitStatePanel resource={resource} label="package detail" />{resource.state === "ready" ? <dl className="s19-benefit-detail-list"><div><dt>Mã gói</dt><dd>{item.code ?? "—"}</dd></div><div><dt>Số lượt cấp</dt><dd>{formatInteger(item.grantedUnits ?? item.granted_units)}</dd></div><div><dt>Số lượt mỗi lần dùng</dt><dd>{formatInteger(item.unitsPerRedemption ?? item.units_per_redemption)}</dd></div><div><dt>Giá</dt><dd>{formatMoney(item.priceMinor ?? item.price_minor, item.currency ?? "VND")}</dd></div><div><dt>Số ngày hiệu lực</dt><dd>{formatInteger(item.validityDays ?? item.validity_days)} ngày</dd></div><div><dt>Chính sách hoàn</dt><dd>{statusLabel(item.refundPolicy ?? item.refund_policy)}</dd></div><div><dt>Phiên bản</dt><dd>{item.version ?? "—"}</dd></div></dl> : null}</section></BenefitShell>;
}

function CustomerPackageLookup() {
  const lookup = useCustomerLookup();
  return <section className="s19-card"><div className="s19-card-heading"><div><p className="s19-eyebrow">QUYỀN LỢI KHÁCH HÀNG</p><h2>Tìm khách hàng</h2></div></div><form className="s19-benefit-search" onSubmit={(event) => { event.preventDefault(); lookup.search(); }}><label className="s19-field"><span>Tên, điện thoại hoặc email</span><input value={lookup.query} onChange={(event) => lookup.setQuery(event.target.value)} required /></label><button className="s19-button s19-button-primary">Tìm kiếm</button></form><BenefitStatePanel resource={lookup.resource} label="customers" />{lookup.resource.state === "ready" ? <div className="s19-benefit-customer-results">{lookup.results.length ? lookup.results.map((customer: any) => <a className="s19-benefit-result" href={`/admin/packages/entitlements?customerId=${customer.id}`} key={customer.id}><span><strong>{customer.displayName}</strong><small>{customer.phone ?? customer.email ?? "Thông tin liên hệ bị giới hạn"}</small></span><span className="s19-status s19-status-info">Mở</span></a>) : <p className="s19-helper">Không tìm thấy khách hàng phù hợp.</p>}</div> : null}</section>;
}

export function PackageEntitlements() {
  const [customerId, setCustomerId] = useState("");
  useEffect(() => { setCustomerId(new URLSearchParams(window.location.search).get("customerId") ?? ""); }, []);
  const resource = useBenefitResource(customerId ? `/v1/customers/${encodeURIComponent(customerId)}/packages` : null); const values = rows(resource.data);
  return <BenefitShell title="Customer package entitlements" eyebrow="CUSTOMER BENEFITS"><CustomerPackageLookup />{customerId ? <section className="s19-card"><CustomerBenefitHeader customerId={customerId} backHref="/admin/packages/entitlements" /><BenefitStatePanel resource={resource} label="package entitlements" />{resource.state === "ready" ? <div className="s19-benefit-stack">{values.map((item: any) => <a className="s19-benefit-item" href={`/admin/packages/entitlements/${item.id}`} key={item.id}><div><strong>{localized(item.name ?? item.code ?? item.packageProductId, "Service package")}</strong><span>{statusLabel(item.status)} · {item.code ?? item.packageProductId}</span></div><div><b>{formatInteger(item.availableUnits)} available</b><small>{formatInteger(item.reservedUnits)} reserved · expires {formatDate(item.expiresAt)}</small></div></a>)}</div> : null}</section> : null}</BenefitShell>;
}

export function PackageEntitlementDetail({ entitlementId }: { entitlementId: string }) {
  const resource = useBenefitResource(`/v1/customer-packages/${encodeURIComponent(entitlementId)}`); const ledger = useBenefitResource(`/v1/customer-packages/${encodeURIComponent(entitlementId)}/ledger`); const item = resource.data ?? {};
  return <BenefitShell title="Package entitlement detail" eyebrow="CUSTOMER BENEFITS" backHref="/admin/packages/entitlements"><section className="s19-card"><div className="s19-card-heading"><div><p className="s19-eyebrow">SERVER BALANCE</p><h2>{item.code ?? item.package_code ?? "Entitlement"}</h2></div><span className="s19-status s19-status-info">{statusLabel(item.status)}</span></div><BenefitStatePanel resource={resource} label="package entitlement" />{resource.state === "ready" ? <dl className="s19-benefit-metrics"><div><dt>Available units</dt><dd>{formatInteger(item.availableUnits ?? item.available_units)}</dd></div><div><dt>Reserved units</dt><dd>{formatInteger(item.reservedUnits ?? item.reserved_units)}</dd></div><div><dt>Consumed units</dt><dd>{formatInteger(item.consumedUnits ?? item.consumed_units)}</dd></div><div><dt>Expires</dt><dd>{formatDate(item.expiresAt ?? item.expires_at)}</dd></div></dl> : null}</section><section className="s19-card"><div className="s19-card-heading"><div><p className="s19-eyebrow">APPEND-ONLY</p><h2>Entitlement ledger</h2></div></div><BenefitStatePanel resource={ledger} label="entitlement ledger" />{ledger.state === "ready" ? <LedgerTable entries={rows(ledger.data)} emptyLabel="entitlement ledger entries" /> : null}</section></BenefitShell>;
}
