import { afterAll,beforeAll,describe,expect,it } from "vitest";
import { createApp } from "../../apps/api/src/main";
const tenant="10000000-0000-4000-8000-000000000001",branch="20000000-0000-4000-8000-000000000001",run=`s9-${Date.now()}`;
let app:Awaited<ReturnType<typeof createApp>>,owner="",managerB="",tech="",platform="";
async function login(email:string,id:string){const r=await app.inject({method:"POST",url:"/v1/auth/login",payload:{tenantSlug:"nailsoft-demo",email,password:"DemoPass123!",deviceId:`${run}-${id}`,deviceName:"Sprint 9 integration",platform:"web"}});expect(r.statusCode,r.body).toBe(200);return r.json().data.accessToken as string;}
const h=(token:string,key=crypto.randomUUID())=>({authorization:`Bearer ${token}`,"x-tenant-id":tenant,"idempotency-key":key});
describe.sequential("Sprint 9 inventory authorization and API safety",()=>{
 beforeAll(async()=>{app=await createApp();await app.init();await app.getHttpAdapter().getInstance().ready();[owner,managerB,tech,platform]=await Promise.all([login("owner@example.test","owner"),login("manager-b@example.test","manager-b"),login("staff5@example.test","tech"),login("platform-e2e@example.test","platform")]);});afterAll(async()=>{if(app)await app.close();});
 it("returns stock without cost while valuation has a separate permission boundary",async()=>{const r=await app.inject({method:"GET",url:`/v1/inventory/stock?branchId=${branch}`,headers:h(owner)});expect(r.statusCode,r.body).toBe(200);expect(r.json().data[0]).not.toHaveProperty("averageUnitCostMinor");const valuation=await app.inject({method:"GET",url:`/v1/inventory/reports/valuation?branchId=${branch}`,headers:h(owner)});expect(valuation.statusCode,valuation.body).toBe(200);expect(valuation.json().data.totalCostMinor).toMatch(/^\d+$/);});
 it("enforces branch scope and platform default denial",async()=>{const cross=await app.inject({method:"GET",url:`/v1/inventory/stock?branchId=${branch}`,headers:h(managerB)});expect(cross.statusCode).toBe(403);const denied=await app.inject({method:"GET",url:"/v1/inventory/items",headers:h(platform)});expect(denied.statusCode).toBe(403);});
 it("allows technician own material view but denies branch stock",async()=>{const own=await app.inject({method:"GET",url:"/v1/staff/me/materials",headers:h(tech)});expect(own.statusCode,own.body).toBe(200);const stock=await app.inject({method:"GET",url:`/v1/inventory/stock?branchId=${branch}`,headers:h(tech)});expect(stock.statusCode).toBe(403);});
 it("keeps blind count expected values redacted during counting",async()=>{const r=await app.inject({method:"GET",url:"/v1/inventory/counts/b9110000-0000-4000-8000-000000000001",headers:h(owner)});expect(r.statusCode,r.body).toBe(200);expect(r.json().data.lines[0]).not.toHaveProperty("expectedQuantity");});
 it("replays a sensitive command and rejects key reuse with changed request",async()=>{const key=`${run}-supplier-key`,payload={code:`SUP-${run}`,name:"Safe supplier",contact:{email:"safe@example.invalid"}};const a=await app.inject({method:"POST",url:"/v1/inventory/suppliers",headers:h(owner,key),payload}),b=await app.inject({method:"POST",url:"/v1/inventory/suppliers",headers:h(owner,key),payload});expect(a.statusCode,a.body).toBe(201);expect(b.statusCode,b.body).toBe(201);expect(b.json().data.id).toBe(a.json().data.id);const changed=await app.inject({method:"POST",url:"/v1/inventory/suppliers",headers:h(owner,key),payload:{...payload,name:"Changed"}});expect(changed.statusCode).toBe(409);});
});
