"use client";

import { useMemo, useState } from "react";
import { AppDialog, Button, Card, ChartFallback, Icon, PageHeader, StatePanel, StatusBadge } from "@nailsoft/ui-web";
import { formatCurrency, formatNumber, translate, type Locale } from "@nailsoft/localization";

const chartValues = [240000000, 310000000, 280000000];

export function GalleryContent() {
  const [locale, setLocale] = useState<Locale>("vi-VN");
  const [query, setQuery] = useState("");
  const [tab, setTab] = useState("overview");
  const resolvedLocale = locale;
  const rows = useMemo(() => chartValues.map((value, index) => ({ label: (["Mon", "Tue", "Wed"][index] ?? `Day ${index + 1}`), value: formatCurrency(value, "VND", resolvedLocale) })), [resolvedLocale]);
  const labels = (key: Parameters<typeof translate>[1]) => translate(resolvedLocale, key);
  const tabs: Array<[string, string]> = [["overview", labels("dashboard")], ["approval", labels("review")], ["audit", labels("statusLabel")]];

  return <main className="ns-gallery" id="gallery-main">
    <PageHeader eyebrow="THƯ VIỆN GIAO DIỆN" title={labels("designSystem")} description="Các thành phần có trạng thái tải, rỗng, lỗi và quyền truy cập rõ ràng." actions={<div className="ns-action-row"><Button><Icon name="plus" />{labels("primaryAction")}</Button><label className="ns-gallery-locale"><span>{labels("chooseLanguage")}</span><select id="gallery-locale" value={locale} onChange={(event) => setLocale(event.target.value as Locale)}><option value="vi-VN">vi-VN</option><option value="en-US">en-US</option></select></label></div>} />
    <div className="ns-gallery-grid">
      <Card><h2>{labels("primaryAction")}</h2><div className="ns-action-row"><Button><Icon name="check" />{labels("saveChanges")}</Button><Button variant="secondary"><Icon name="edit" />{labels("review")}</Button><Button variant="danger"><Icon name="close" />{labels("delete")}</Button><Button variant="quiet">{labels("cancel")}</Button></div><p className="ns-gallery-caption"><Icon name="lock" /> Actions preserve accessible names when icons are added.</p></Card>
      <Card><h2>{labels("status")}</h2><div className="ns-action-row"><StatusBadge tone="success">{labels("active")}</StatusBadge><StatusBadge tone="warning">{labels("needsReview")}</StatusBadge><StatusBadge tone="danger">{labels("blocked")}</StatusBadge><StatusBadge tone="info">{labels("inProgress")}</StatusBadge></div><div className="ns-gallery-progress" role="progressbar" aria-label="Sample completion" aria-valuenow={64} aria-valuemin={0} aria-valuemax={100}><span style={{ width: "64%" }} /></div></Card>
      <Card><h2>{labels("forms")}</h2><form className="ns-gallery-form" onSubmit={(event) => event.preventDefault()}><label htmlFor="gallery-search">{labels("search")}</label><input id="gallery-search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder={labels("sampleCustomer")} /><p className="ns-gallery-caption">{query ? `${labels("search")}: ${query}` : labels("empty")}</p><label htmlFor="gallery-service">{labels("service")}</label><select id="gallery-service" defaultValue="manicure"><option value="manicure">Gel manicure</option><option value="pedicure">Classic pedicure</option></select><Button type="submit">{labels("save")}</Button></form></Card>
      <Card><h2>{labels("searchAndFilters")}</h2><div className="ns-toolbar"><label htmlFor="gallery-filter">{labels("statusLabel")}</label><select id="gallery-filter" defaultValue="all"><option value="all">{labels("statusLabel")}</option><option value="active">{labels("active")}</option><option value="review">{labels("needsReview")}</option></select><Button variant="secondary"><Icon name="filter" />{labels("refresh")}</Button></div><div className="ns-gallery-chip-row"><StatusBadge tone="neutral">{labels("branch")}: Demo</StatusBadge><StatusBadge tone="neutral">{labels("service")}: 3</StatusBadge></div></Card>
      <Card className="ns-gallery-wide"><h2>{labels("dataDisplay")}</h2><div className="ns-table-scroll"><table><caption className="sr-only">{labels("dataDisplay")}</caption><thead><tr><th scope="col">{labels("sampleCustomer")}</th><th scope="col">{labels("service")}</th><th scope="col">{labels("amount")}</th><th scope="col">{labels("statusLabel")}</th></tr></thead><tbody><tr><th scope="row">Mai Nguyen</th><td>Gel manicure</td><td>{formatCurrency(12500000, "VND", resolvedLocale)}</td><td><StatusBadge tone="success">{labels("active")}</StatusBadge></td></tr><tr><th scope="row">Linh Tran</th><td>Classic pedicure</td><td>{formatCurrency(9800000, "VND", resolvedLocale)}</td><td><StatusBadge tone="warning">{labels("needsReview")}</StatusBadge></td></tr></tbody></table></div><div className="ns-pagination"><Button variant="secondary" aria-label={labels("previous")}><Icon name="chevronLeft" />{labels("previous")}</Button><span>1 / 3</span><Button variant="secondary">{labels("next")}<Icon name="chevronRight" /></Button></div></Card>
      <Card><h2>{labels("overlays")}</h2><div className="ns-action-row"><AppDialog title={labels("openDialog")} description={labels("chartDescription")} trigger={<Button variant="secondary"><Icon name="more" />{labels("openDialog")}</Button>}><p>{labels("review")}</p></AppDialog><Button variant="secondary"><Icon name="notification" />{labels("notifications")}</Button></div><div className="ns-gallery-banner" role="status"><strong>{labels("staleState")}:</strong> {labels("stale")}</div></Card>
      <Card><h2>{labels("asyncStates")}</h2><div className="ns-state-stack"><StatePanel state="loading" title={labels("loadingState")} detail={labels("loading")} /><StatePanel state="empty" title={labels("emptyState")} detail={labels("empty")} /><StatePanel state="error" title={labels("errorState")} detail={labels("error")} onRetry={() => undefined} /></div></Card>
      <Card><h2>{labels("asyncStates")} - access</h2><div className="ns-state-stack"><StatePanel state="forbidden" title={labels("forbiddenState")} detail={labels("forbidden")} /><StatePanel state="offline" title={labels("offlineState")} detail={labels("offline")} /><StatePanel state="partial" title={labels("partialState")} detail={labels("partial")} /></div></Card>
      <Card><h2>{labels("progressAndHistory")}</h2><div role="tablist" aria-label="Gallery tabs" className="ns-gallery-tabs">{tabs.map(([value, title]) => <button key={value} type="button" role="tab" aria-selected={tab === value} onClick={() => setTab(value)}>{title}</button>)}</div><ol className="ns-timeline"><li><StatusBadge tone="success">1</StatusBadge><span>{tab === "approval" ? labels("review") : labels("active")}</span></li><li><StatusBadge tone="info">2</StatusBadge><span>{labels("inProgress")}</span></li><li><StatusBadge tone="neutral">3</StatusBadge><span>{labels("emptyState")}</span></li></ol></Card>
      <Card><h2>{labels("chartFallback")}</h2><ChartFallback title={labels("revenueByDay")} description={labels("chartDescription")} rows={rows} /><div className="ns-gallery-chart-states"><ChartFallback title={labels("revenueByDay")} description={labels("chartDescription")} rows={[]} empty /><ChartFallback title={labels("revenueByDay")} description={labels("chartDescription")} rows={[]} loading /></div></Card>
      <Card><h2>{labels("dataDisplay")} - responsive list</h2><ul className="ns-gallery-list"><li><Icon name="calendar" /><span><strong>Today</strong><small>{formatNumber(12, resolvedLocale)} {labels("bookings")}</small></span><StatusBadge tone="success">{labels("active")}</StatusBadge></li><li><Icon name="people" /><span><strong>{labels("team")}</strong><small>{formatNumber(8, resolvedLocale)} {labels("active")}</small></span><StatusBadge tone="info">{labels("inProgress")}</StatusBadge></li></ul></Card>
    </div>
  </main>;
}
