/* eslint-disable @typescript-eslint/no-explicit-any */
import { Link, useLocalSearchParams } from "expo-router";
import { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, Button, SafeAreaView, ScrollView, Text, View } from "react-native";
import { apiFetch } from "../lib/session";

const titles: Record<string, string> = { organization: "Organization summary", branches: "Branch list", branch: "Branch detail", team: "Team list", user: "User detail", sessions: "Active sessions", profile: "Profile", language: "Language", workspace: "Workspace selection", mfa: "MFA challenge", services: "Service summary", service: "Service detail", staff: "Staff list", staffDetail: "Staff detail", shifts: "Shift summary", leave: "Pending leave requests", leaveReview: "Review leave request" };
function endpoint(screen: string, id?: string) { if (screen === "services") return "/v1/services?status=ACTIVE&page=1&pageSize=50"; if (screen === "service") return `/v1/services/${id ?? ""}`; if (screen === "staff") return "/v1/staff?status=ACTIVE"; if (screen === "staffDetail") return `/v1/staff/${id ?? ""}`; if (screen === "shifts") return "/v1/shifts"; if (screen === "leave") return "/v1/leave-requests?status=PENDING"; if (screen === "leaveReview") return `/v1/leave-requests/${id ?? ""}`; return null; }
export default function OwnerScreen() {
  const params = useLocalSearchParams<{ screen: string; id?: string }>(); const screen = params.screen; const [state, setState] = useState<"loading" | "ready" | "empty" | "error" | "forbidden">("loading"); const [data, setData] = useState<any[]>([]); const [message, setMessage] = useState("");
  const load = useCallback(async () => { const path = endpoint(screen, params.id); if (!path) { setState("empty"); return; } setState("loading"); try { const response = await apiFetch(path); if (response.status === 401 || response.status === 403) { setState("forbidden"); return; } const body = await response.json(); if (!response.ok) throw new Error(body.error?.message ?? "Unable to load"); const value = Array.isArray(body.data) ? body.data : [body.data]; setData(value.filter(Boolean)); setState(value.filter(Boolean).length ? "ready" : "empty"); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to load"); setState("error"); } }, [screen, params.id]);
  useEffect(() => { void load(); }, [load]);
  async function review(action: "approve" | "reject") { if (!params.id) return; const response = await apiFetch(`/v1/leave-requests/${params.id}/${action}`, { method: "POST", headers: { "content-type": "application/json", "idempotency-key": `${action}-${params.id}` }, body: JSON.stringify(action === "reject" ? { reviewNote: "Reviewed in Owner Mobile" } : {}) }); setMessage(response.ok ? `Leave ${action}d.` : "The request could not be completed."); await load(); }
  return <SafeAreaView><ScrollView contentContainerStyle={{ padding: 24, gap: 16 }}><Text style={{ color: "#6D28D9", fontWeight: "700" }}>OWNER · SPRINT 2</Text><Text style={{ fontSize: 30, fontWeight: "700" }}>{titles[screen] ?? "Workspace"}</Text>{state === "loading" && <ActivityIndicator accessibilityLabel="Loading" />}{state === "forbidden" && <Text accessibilityRole="alert">Permission denied for this workspace.</Text>}{state === "error" && <View><Text accessibilityRole="alert">{message}</Text><Button title="Retry" onPress={() => void load()} /></View>}{state === "empty" && <View><Text>No records are available.</Text><Button title="Refresh" onPress={() => void load()} /></View>}{state === "ready" && <View style={{ gap: 12 }}>{data.map((item, index) => <View key={item.id ?? index} style={{ padding: 16, backgroundColor: "#F3EEFF", borderRadius: 12 }}><Text style={{ fontWeight: "700" }}>{item.displayName ?? item.code ?? item.name?.["vi-VN"] ?? item.status ?? item.id}</Text><Text>{item.startAt ? `${item.startAt} – ${item.endAt}` : item.status ?? "Active"}</Text>{screen === "leave" && item.id && <Link href={`/leaveReview?id=${item.id}` as never}>Review request</Link>}</View>)}</View>}{screen === "leaveReview" && params.id && <View style={{ flexDirection: "row", gap: 12 }}><Button title="Approve" onPress={() => void review("approve")} /><Button title="Reject" onPress={() => void review("reject")} /></View>}<Link href="/">Back to home</Link></ScrollView></SafeAreaView>;
}
