BEGIN;
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE TABLE IF NOT EXISTS schema_migrations(version text PRIMARY KEY,applied_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE tenants(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),name text NOT NULL,slug text NOT NULL UNIQUE,default_locale text NOT NULL DEFAULT 'vi-VN' CHECK(default_locale IN('vi-VN','en-US')),currency char(3) NOT NULL DEFAULT 'VND',timezone text NOT NULL DEFAULT 'Asia/Ho_Chi_Minh',status text NOT NULL DEFAULT 'ACTIVE',created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE branches(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL REFERENCES tenants(id),name text NOT NULL,code text NOT NULL,timezone text NOT NULL,status text NOT NULL DEFAULT 'ACTIVE',UNIQUE(tenant_id,code),UNIQUE(tenant_id,id));
CREATE TABLE users(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL REFERENCES tenants(id),email text,phone_normalized text,display_name text NOT NULL,status text NOT NULL DEFAULT 'ACTIVE',UNIQUE(tenant_id,id));
CREATE UNIQUE INDEX users_tenant_email_unique ON users(tenant_id,email) WHERE email IS NOT NULL;
CREATE UNIQUE INDEX users_tenant_phone_unique ON users(tenant_id,phone_normalized) WHERE phone_normalized IS NOT NULL;
CREATE TABLE user_roles(tenant_id uuid NOT NULL REFERENCES tenants(id),user_id uuid NOT NULL,branch_id uuid,role text NOT NULL,PRIMARY KEY(tenant_id,user_id,role),FOREIGN KEY(tenant_id,user_id) REFERENCES users(tenant_id,id),FOREIGN KEY(tenant_id,branch_id) REFERENCES branches(tenant_id,id));
CREATE TABLE service_categories(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL REFERENCES tenants(id),name_json jsonb NOT NULL,UNIQUE(tenant_id,id));
CREATE TABLE services(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL REFERENCES tenants(id),category_id uuid,code text NOT NULL,name_json jsonb NOT NULL,duration_minutes int NOT NULL CHECK(duration_minutes>0),base_price_minor bigint NOT NULL CHECK(base_price_minor>=0),UNIQUE(tenant_id,code),UNIQUE(tenant_id,id),FOREIGN KEY(tenant_id,category_id) REFERENCES service_categories(tenant_id,id));
CREATE TABLE customers(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL REFERENCES tenants(id),display_name text NOT NULL,phone_normalized text,UNIQUE(tenant_id,id));
CREATE UNIQUE INDEX customers_tenant_phone_unique ON customers(tenant_id,phone_normalized) WHERE phone_normalized IS NOT NULL;
CREATE TABLE appointments(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL REFERENCES tenants(id),branch_id uuid NOT NULL,customer_id uuid,status text NOT NULL,start_at timestamptz NOT NULL,end_at timestamptz NOT NULL,version int NOT NULL DEFAULT 1,CHECK(end_at>start_at),UNIQUE(tenant_id,id),FOREIGN KEY(tenant_id,branch_id) REFERENCES branches(tenant_id,id),FOREIGN KEY(tenant_id,customer_id) REFERENCES customers(tenant_id,id));
CREATE INDEX appointments_calendar_idx ON appointments(tenant_id,branch_id,start_at,end_at,status);
CREATE TABLE products(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL REFERENCES tenants(id),sku text NOT NULL,name text NOT NULL,kind text NOT NULL,UNIQUE(tenant_id,sku));
CREATE TABLE vouchers(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL REFERENCES tenants(id),code text NOT NULL,kind text NOT NULL,usage_limit int,UNIQUE(tenant_id,code));
CREATE TABLE loyalty_programs(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL REFERENCES tenants(id),name text NOT NULL,status text NOT NULL);
CREATE TABLE commission_rules(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL REFERENCES tenants(id),name text NOT NULL,rule_json jsonb NOT NULL,status text NOT NULL);
CREATE TABLE audit_logs(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL REFERENCES tenants(id),branch_id uuid,actor_user_id uuid,action text NOT NULL,entity_type text NOT NULL,entity_id uuid,before_json jsonb,after_json jsonb,reason text,ip_address inet,device_id text,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE idempotency_keys(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL REFERENCES tenants(id),key text NOT NULL,request_hash text NOT NULL,response_status int,response_body_json jsonb,state text NOT NULL DEFAULT 'PROCESSING',expires_at timestamptz NOT NULL,UNIQUE(tenant_id,key));
CREATE TABLE outbox_events(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL REFERENCES tenants(id),event_type text NOT NULL,aggregate_type text NOT NULL,aggregate_id uuid NOT NULL,payload_json jsonb NOT NULL,status text NOT NULL DEFAULT 'PENDING',attempts int NOT NULL DEFAULT 0,created_at timestamptz NOT NULL DEFAULT now(),published_at timestamptz);
CREATE INDEX outbox_pending_idx ON outbox_events(status,created_at) WHERE status='PENDING';
INSERT INTO schema_migrations(version) VALUES('0001_foundation') ON CONFLICT DO NOTHING;
COMMIT;
