BEGIN;
DROP TRIGGER IF EXISTS availability_block_target_guard ON availability_blocks;
DROP FUNCTION IF EXISTS validate_availability_block_target();
DROP TRIGGER IF EXISTS availability_bump_blocks ON availability_blocks;
DROP TRIGGER IF EXISTS availability_bump_resources ON resources;
DROP TRIGGER IF EXISTS availability_bump_leave ON leave_requests;
DROP TRIGGER IF EXISTS availability_bump_shifts ON shifts;
DROP TRIGGER IF EXISTS availability_bump_staff_skills ON staff_skills;
DROP TRIGGER IF EXISTS availability_bump_staff_assignments ON staff_branch_assignments;
DROP TRIGGER IF EXISTS availability_bump_service_resources ON service_resource_requirements;
DROP TRIGGER IF EXISTS availability_bump_service_skills ON service_skill_requirements;
DROP TRIGGER IF EXISTS availability_bump_service_prices ON service_prices;
DROP TRIGGER IF EXISTS availability_bump_services ON services;
DROP TRIGGER IF EXISTS availability_bump_business_hours ON business_hours;
DROP TRIGGER IF EXISTS availability_bump_branches ON branches;
DROP FUNCTION IF EXISTS bump_tenant_availability_versions();
DELETE FROM role_permissions WHERE permission_code IN ('availability.read','availability.explain','calendar.read_branch','calendar.read_own','availability_block.read','availability_block.create','availability_block.update','availability_block.cancel','resource_maintenance.manage');
DELETE FROM permissions WHERE code IN ('availability.read','availability.explain','calendar.read_branch','calendar.read_own','availability_block.read','availability_block.create','availability_block.update','availability_block.cancel','resource_maintenance.manage');
DROP TABLE availability_blocks;
DROP TABLE availability_versions;
DROP INDEX IF EXISTS business_hours_availability_idx;
DROP INDEX IF EXISTS staff_assignments_availability_idx;
DROP INDEX IF EXISTS staff_skills_availability_idx;
DROP INDEX IF EXISTS shifts_branch_status_time_idx;
DROP INDEX IF EXISTS shifts_staff_status_time_idx;
DROP INDEX IF EXISTS leave_branch_status_time_idx;
DROP INDEX IF EXISTS resources_availability_idx;
DROP INDEX IF EXISTS resources_tenant_branch_id_unique;
DELETE FROM schema_migrations WHERE version='0007_availability_calendar';
COMMIT;
