BEGIN;
DELETE FROM role_permissions WHERE permission_code IN (SELECT code FROM permissions WHERE code LIKE 'walkin.%' OR code LIKE 'service_session.%' OR code IN ('operations.board.read','appointment.arrive','appointment.check_in','appointment.revert_check_in','appointment.checkout_summary'));
DELETE FROM permissions WHERE code LIKE 'walkin.%' OR code LIKE 'service_session.%' OR code IN ('operations.board.read','appointment.arrive','appointment.check_in','appointment.revert_check_in','appointment.checkout_summary');
DROP TRIGGER IF EXISTS segment_operational_version ON service_session_staff_segments;
DROP TRIGGER IF EXISTS session_operational_version ON service_sessions;
DROP TRIGGER IF EXISTS arrival_operational_version ON appointment_arrivals;
DROP TRIGGER IF EXISTS walk_in_operational_version ON walk_in_entries;
DROP FUNCTION IF EXISTS bump_branch_operational_version();
DROP TRIGGER IF EXISTS service_session_segments_append_only ON service_session_staff_segments;
DROP TRIGGER IF EXISTS walk_in_status_history_append_only ON walk_in_status_history;
DROP FUNCTION IF EXISTS sprint5_append_only_guard();
DROP TABLE branch_operational_versions;
DROP TABLE service_session_media;
DROP TABLE service_session_notes;
DROP TABLE service_session_pauses;
DROP TABLE service_session_staff_segments;
DROP TABLE service_sessions;
DROP TABLE walk_in_status_history;
DROP TABLE walk_in_items;
DROP TABLE walk_in_entries;
DROP TABLE walk_in_queue_counters;
DROP TABLE appointment_arrivals;
ALTER TABLE appointment_items DROP CONSTRAINT appointment_items_added_approval_check, DROP CONSTRAINT appointment_items_added_by_fkey, DROP CONSTRAINT appointment_items_parent_fkey, DROP CONSTRAINT appointment_items_approval_method_check, DROP CONSTRAINT appointment_items_source_check, DROP COLUMN customer_approval_method, DROP COLUMN customer_approved_at, DROP COLUMN added_by_user_id, DROP COLUMN added_at, DROP COLUMN parent_item_id, DROP COLUMN item_source;
ALTER TABLE appointments DROP COLUMN checkout_ready;
DELETE FROM schema_migrations WHERE version='0011_walkin_checkin_service_execution';
COMMIT;
