BEGIN;
DELETE FROM role_permissions WHERE role='CASHIER' AND permission_code='branch.read';
DELETE FROM role_permissions WHERE permission_code IN (SELECT code FROM permissions WHERE code LIKE 'pos.%' OR code LIKE 'payment.%' OR code LIKE 'invoice.%' OR code LIKE 'cash_session.%' OR code LIKE 'financial.%');
DELETE FROM permissions WHERE code LIKE 'pos.%' OR code LIKE 'payment.%' OR code LIKE 'invoice.%' OR code LIKE 'cash_session.%' OR code LIKE 'financial.%';
DROP TRIGGER IF EXISTS issued_invoice_immutable ON invoices;
DROP FUNCTION IF EXISTS sprint6_invoice_immutable_guard();
DROP TRIGGER IF EXISTS captured_payment_immutable ON payments;
DROP FUNCTION IF EXISTS sprint6_payment_immutable_guard();
DROP TRIGGER IF EXISTS financial_events_append_only ON financial_events;
DROP TRIGGER IF EXISTS order_history_append_only ON pos_order_status_history;
DROP TRIGGER IF EXISTS invoice_lines_append_only ON invoice_lines;
DROP TRIGGER IF EXISTS payment_allocations_append_only ON payment_allocations;
DROP TRIGGER IF EXISTS payment_attempts_append_only ON payment_attempts;
DROP TRIGGER IF EXISTS tip_allocations_append_only ON pos_tip_allocations;
DROP TRIGGER IF EXISTS pos_discounts_append_only ON pos_discounts;
DROP TRIGGER IF EXISTS pricing_revisions_append_only ON pos_order_pricing_revisions;
DROP TRIGGER IF EXISTS cash_movements_append_only ON cash_movements;
DROP FUNCTION IF EXISTS sprint6_append_only_guard();
DROP TABLE payment_provider_events;
DROP TABLE financial_events;
DROP TABLE pos_order_status_history;
DROP TABLE invoice_deliveries;
DROP TABLE invoice_lines;
DROP TABLE invoices;
DROP TABLE invoice_counters;
DROP TABLE cash_movements;
DROP TABLE payment_allocations;
DROP TABLE payment_attempts;
DROP TABLE payments;
DROP TABLE pos_tip_allocations;
DROP TABLE pos_tips;
DROP TABLE pos_discount_approval_requests;
DROP TABLE pos_order_pricing_revisions;
DROP TABLE pos_discounts;
DROP TABLE pos_order_lines;
DROP TABLE pos_orders;
DROP TABLE tax_profiles;
DROP TABLE cash_sessions;
DROP TABLE cash_drawers;
DROP TABLE pos_register_device_bindings;
DROP TABLE pos_registers;
DELETE FROM schema_migrations WHERE version='0012_pos_invoice_payment_cash_session';
COMMIT;
