BEGIN;
DELETE FROM schema_migrations WHERE version='0020_sprint10_stored_value_correctness_hardening';
DELETE FROM stored_value_reconciliation_exceptions WHERE generation_key LIKE 'sprint10-closure:funding:%';
ALTER TABLE stored_value_adjustment_requests DROP CONSTRAINT IF EXISTS stored_value_adjustment_branch_fk;
ALTER TABLE stored_value_adjustment_requests DROP COLUMN IF EXISTS branch_id;
DROP TRIGGER IF EXISTS stored_value_high_value_append_only ON stored_value_high_value_approvals;
DROP TABLE IF EXISTS stored_value_high_value_approvals;
DROP TABLE IF EXISTS stored_value_velocity_counters;
DROP TABLE IF EXISTS refund_stored_value_line_plans;
DROP TRIGGER IF EXISTS stored_value_refund_line_restore_guard ON stored_value_refund_allocations;
DROP FUNCTION IF EXISTS sprint10_refund_line_restore_guard();
ALTER TABLE stored_value_refund_allocations DROP CONSTRAINT IF EXISTS stored_value_refund_line_fk;
ALTER TABLE stored_value_refund_allocations DROP COLUMN IF EXISTS settlement_line_allocation_id;
DROP TRIGGER IF EXISTS stored_value_settlement_line_guard ON stored_value_settlement_line_allocations;
DROP FUNCTION IF EXISTS sprint10_settlement_line_guard();
DROP TRIGGER IF EXISTS stored_value_settlement_line_append_only ON stored_value_settlement_line_allocations;
DROP TABLE IF EXISTS stored_value_settlement_line_allocations;
DROP TRIGGER IF EXISTS stored_value_funding_allocation_guard ON stored_value_funding_allocations;
DROP FUNCTION IF EXISTS sprint10_funding_allocation_guard();
DROP TRIGGER IF EXISTS stored_value_funding_append_only ON stored_value_funding_allocations;
DROP TABLE IF EXISTS stored_value_funding_allocations;
DROP INDEX IF EXISTS stored_value_ledger_branch_idx;
ALTER TABLE stored_value_ledger_entries DROP CONSTRAINT IF EXISTS stored_value_ledger_branch_fk;
ALTER TABLE stored_value_ledger_entries DROP COLUMN IF EXISTS branch_id;
ALTER TABLE pos_order_stored_value_applications DROP COLUMN IF EXISTS eligibility_snapshot_json;
ALTER TABLE pos_order_stored_value_applications DROP COLUMN IF EXISTS redemption_plan_json;
ALTER TABLE stored_value_reservations DROP CONSTRAINT IF EXISTS stored_value_reservation_branch_fk;
ALTER TABLE stored_value_reservations DROP COLUMN IF EXISTS eligibility_snapshot_json;
ALTER TABLE stored_value_reservations DROP COLUMN IF EXISTS branch_id;
DROP INDEX IF EXISTS gift_cards_branch_scope_idx;
ALTER TABLE gift_cards DROP CONSTRAINT IF EXISTS gift_cards_legal_policy_fk;
ALTER TABLE gift_cards DROP CONSTRAINT IF EXISTS gift_cards_replaces_fk;
ALTER TABLE gift_cards DROP CONSTRAINT IF EXISTS gift_cards_last_activity_branch_fk;
ALTER TABLE gift_cards DROP CONSTRAINT IF EXISTS gift_cards_issuance_branch_fk;
ALTER TABLE gift_cards DROP COLUMN IF EXISTS expiration_mode;
ALTER TABLE gift_cards DROP COLUMN IF EXISTS jurisdiction;
ALTER TABLE gift_cards DROP COLUMN IF EXISTS legal_policy_version;
ALTER TABLE gift_cards DROP COLUMN IF EXISTS legal_policy_id;
ALTER TABLE gift_cards DROP COLUMN IF EXISTS replacement_authorization_json;
ALTER TABLE gift_cards DROP COLUMN IF EXISTS replacement_reason;
ALTER TABLE gift_cards DROP COLUMN IF EXISTS replaces_gift_card_id;
ALTER TABLE gift_cards DROP COLUMN IF EXISTS last_activity_branch_id;
ALTER TABLE gift_cards DROP COLUMN IF EXISTS issuance_branch_id;
ALTER TABLE stored_value_settings DROP COLUMN IF EXISTS reserve_attempt_limit;
ALTER TABLE stored_value_settings DROP COLUMN IF EXISTS daily_reload_limit_minor;
COMMIT;
