BEGIN;
DROP TRIGGER IF EXISTS accounting_bank_match_cap_guard ON accounting_bank_match_allocations;
DROP TRIGGER IF EXISTS accounting_bank_statement_line_append_only ON accounting_bank_statement_lines;
DROP TRIGGER IF EXISTS accounting_statement_line_immutable ON accounting_statement_snapshot_lines;
DROP TRIGGER IF EXISTS accounting_statement_header_immutable ON accounting_statement_snapshots;
DROP TRIGGER IF EXISTS accounting_opening_scope_guard ON accounting_opening_balance_rows;
DROP TRIGGER IF EXISTS accounting_line_scope_guard ON accounting_journal_lines;
DROP TRIGGER IF EXISTS accounting_journal_scope_guard ON accounting_journals;
DROP TRIGGER IF EXISTS accounting_account_scope_guard ON accounting_accounts;
DROP TRIGGER IF EXISTS accounting_period_scope_guard ON accounting_periods;
DROP TRIGGER IF EXISTS accounting_journal_post_validation ON accounting_journals;
DROP TRIGGER IF EXISTS accounting_journal_post_guard ON accounting_journals;
DROP TRIGGER IF EXISTS accounting_posted_line_guard ON accounting_journal_lines;
CREATE TRIGGER accounting_journal_post_guard BEFORE UPDATE ON accounting_journals FOR EACH ROW EXECUTE FUNCTION accounting_journal_post_guard();
CREATE TRIGGER accounting_posted_line_guard BEFORE UPDATE OR DELETE ON accounting_journal_lines FOR EACH ROW EXECUTE FUNCTION accounting_posted_line_guard();
DROP FUNCTION IF EXISTS accounting_bank_match_cap_guard();
DROP FUNCTION IF EXISTS accounting_bank_statement_append_only_guard();
DROP FUNCTION IF EXISTS accounting_snapshot_immutable_guard();
DROP FUNCTION IF EXISTS accounting_opening_scope_guard();
DROP FUNCTION IF EXISTS accounting_line_scope_guard();
DROP FUNCTION IF EXISTS accounting_journal_scope_guard();
DROP FUNCTION IF EXISTS accounting_account_scope_guard();
DROP FUNCTION IF EXISTS accounting_period_scope_guard();
DROP FUNCTION IF EXISTS accounting_journal_post_validation();
DROP FUNCTION IF EXISTS accounting_posted_journal_immutable_guard();
DROP FUNCTION IF EXISTS accounting_posted_line_immutable_guard();
DROP TABLE IF EXISTS accounting_journal_number_sequences,accounting_command_idempotency CASCADE;
ALTER TABLE accounting_posting_candidates DROP COLUMN IF EXISTS lease_owner,DROP COLUMN IF EXISTS lease_expires_at,DROP COLUMN IF EXISTS retry_count,DROP COLUMN IF EXISTS last_error_json;
ALTER TABLE accounting_periods DROP COLUMN IF EXISTS close_requested_by_user_id,DROP COLUMN IF EXISTS close_approved_by_user_id,DROP COLUMN IF EXISTS reopen_requested_by_user_id,DROP COLUMN IF EXISTS reopen_approved_by_user_id;
ALTER TABLE accounting_books DROP COLUMN IF EXISTS journal_number_next;
DELETE FROM schema_migrations WHERE version='0029_sprint14_accounting_correctness_closure';
COMMIT;
