BEGIN;

-- Sprint 15 procurement/AP foundation.  This migration is additive; 0001-0030
-- remain untouched and existing tenants are explicitly disabled by default.
CREATE TABLE procurement_policies(
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenants(id),
  state text NOT NULL DEFAULT 'INCOMPLETE' CHECK(state IN('INCOMPLETE','ACTIVE','RETIRED')),
  procurement_enabled boolean NOT NULL DEFAULT false, allow_non_po_expense boolean NOT NULL DEFAULT false,
  non_po_threshold_minor bigint NOT NULL DEFAULT 0 CHECK(non_po_threshold_minor>=0), receipt_tolerance_numerator bigint NOT NULL DEFAULT 0 CHECK(receipt_tolerance_numerator>=0),
  receipt_tolerance_denominator bigint NOT NULL DEFAULT 1 CHECK(receipt_tolerance_denominator>0), version integer NOT NULL DEFAULT 1,
  created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(tenant_id,id)
);
CREATE TABLE procurement_vendors(
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenants(id), code text NOT NULL,
  legal_name text NOT NULL, display_name text NOT NULL, tax_reference text, currency char(3) NOT NULL,
  status text NOT NULL DEFAULT 'DRAFT' CHECK(status IN('DRAFT','ACTIVE','ON_HOLD','INACTIVE','ARCHIVED')),
  payment_terms_days integer NOT NULL DEFAULT 0 CHECK(payment_terms_days>=0), payment_terms_snapshot jsonb NOT NULL DEFAULT '{}',
  masked_tax_reference text, version integer NOT NULL DEFAULT 1, created_by_user_id uuid REFERENCES users(id),
  updated_by_user_id uuid REFERENCES users(id), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(tenant_id,id), UNIQUE(tenant_id,code)
);
CREATE INDEX procurement_vendors_status_idx ON procurement_vendors(tenant_id,status);
CREATE TABLE procurement_vendor_contacts(
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, vendor_id uuid NOT NULL, name text NOT NULL,
  email text, phone text, role text, is_primary boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(tenant_id,id), FOREIGN KEY(tenant_id,vendor_id) REFERENCES procurement_vendors(tenant_id,id)
);
CREATE TABLE procurement_vendor_payment_methods(
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, vendor_id uuid NOT NULL, method_type text NOT NULL CHECK(method_type IN('BANK','CASH','CARD','OTHER')),
  token_reference text NOT NULL, masked_reference text NOT NULL, currency char(3) NOT NULL, status text NOT NULL DEFAULT 'ACTIVE' CHECK(status IN('ACTIVE','INACTIVE')),
  created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(tenant_id,id), FOREIGN KEY(tenant_id,vendor_id) REFERENCES procurement_vendors(tenant_id,id)
);
CREATE TABLE procurement_vendor_status_history(
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, vendor_id uuid NOT NULL, from_status text, to_status text NOT NULL,
  actor_user_id uuid REFERENCES users(id), reason text, request_id text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(),
  FOREIGN KEY(tenant_id,vendor_id) REFERENCES procurement_vendors(tenant_id,id)
);

CREATE TABLE procurement_purchase_requests(
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, branch_id uuid NOT NULL, requester_user_id uuid NOT NULL,
  request_number text NOT NULL, status text NOT NULL DEFAULT 'DRAFT' CHECK(status IN('DRAFT','SUBMITTED','PARTIALLY_APPROVED','APPROVED','REJECTED','CANCELLED','CONVERTED','CLOSED')),
  currency char(3) NOT NULL, requested_total_minor bigint NOT NULL DEFAULT 0 CHECK(requested_total_minor>=0), approved_total_minor bigint NOT NULL DEFAULT 0 CHECK(approved_total_minor>=0),
  reason text, version integer NOT NULL DEFAULT 1, fingerprint text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(tenant_id,id), UNIQUE(tenant_id,request_number), FOREIGN KEY(tenant_id,branch_id) REFERENCES branches(tenant_id,id), FOREIGN KEY(requester_user_id) REFERENCES users(id)
);
CREATE TABLE procurement_purchase_request_lines(
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, purchase_request_id uuid NOT NULL, line_no integer NOT NULL,
  description text NOT NULL, item_id uuid, quantity numeric(30,6) NOT NULL CHECK(quantity>0), approved_quantity numeric(30,6) NOT NULL DEFAULT 0 CHECK(approved_quantity>=0 AND approved_quantity<=quantity),
  unit_price_minor bigint NOT NULL CHECK(unit_price_minor>=0), amount_minor bigint NOT NULL CHECK(amount_minor>=0), approved_amount_minor bigint NOT NULL DEFAULT 0 CHECK(approved_amount_minor>=0),
  created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(tenant_id,id), UNIQUE(purchase_request_id,line_no), FOREIGN KEY(tenant_id,purchase_request_id) REFERENCES procurement_purchase_requests(tenant_id,id)
);
CREATE TABLE procurement_purchase_request_approvals(
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, purchase_request_id uuid NOT NULL, approver_user_id uuid NOT NULL,
  decision text NOT NULL CHECK(decision IN('APPROVED','PARTIALLY_APPROVED','REJECTED')), approved_amount_minor bigint NOT NULL DEFAULT 0 CHECK(approved_amount_minor>=0),
  evidence_json jsonb NOT NULL DEFAULT '{}', version integer NOT NULL, request_id text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(),
  FOREIGN KEY(tenant_id,purchase_request_id) REFERENCES procurement_purchase_requests(tenant_id,id), FOREIGN KEY(approver_user_id) REFERENCES users(id), UNIQUE(tenant_id,purchase_request_id,approver_user_id,version)
);
CREATE TABLE procurement_purchase_request_history(
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, purchase_request_id uuid NOT NULL, from_status text, to_status text NOT NULL,
  actor_user_id uuid REFERENCES users(id), reason text, request_id text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), FOREIGN KEY(tenant_id,purchase_request_id) REFERENCES procurement_purchase_requests(tenant_id,id)
);

CREATE TABLE procurement_purchase_order_number_sequences(
  tenant_id uuid NOT NULL REFERENCES tenants(id), branch_id uuid NOT NULL, local_year integer NOT NULL, next_value bigint NOT NULL DEFAULT 1 CHECK(next_value>0), PRIMARY KEY(tenant_id,branch_id,local_year), FOREIGN KEY(tenant_id,branch_id) REFERENCES branches(tenant_id,id)
);
CREATE TABLE procurement_purchase_orders(
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, branch_id uuid NOT NULL, vendor_id uuid NOT NULL, purchase_request_id uuid,
  po_number text NOT NULL, currency char(3) NOT NULL, status text NOT NULL DEFAULT 'DRAFT' CHECK(status IN('DRAFT','PENDING_APPROVAL','APPROVED','SENT','ACKNOWLEDGED','PARTIALLY_RECEIVED','RECEIVED','PARTIALLY_BILLED','BILLED','CANCELLED','CLOSED')),
  version integer NOT NULL DEFAULT 1, approved_version integer, subtotal_minor bigint NOT NULL DEFAULT 0 CHECK(subtotal_minor>=0), tax_minor bigint NOT NULL DEFAULT 0 CHECK(tax_minor>=0), total_minor bigint NOT NULL DEFAULT 0 CHECK(total_minor>=0),
  economics_snapshot jsonb NOT NULL DEFAULT '{}', requested_by_user_id uuid REFERENCES users(id), approved_by_user_id uuid REFERENCES users(id), approved_at timestamptz, sent_at timestamptz, fingerprint text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(tenant_id,id), UNIQUE(tenant_id,po_number),
  FOREIGN KEY(tenant_id,branch_id) REFERENCES branches(tenant_id,id), FOREIGN KEY(tenant_id,vendor_id) REFERENCES procurement_vendors(tenant_id,id), FOREIGN KEY(tenant_id,purchase_request_id) REFERENCES procurement_purchase_requests(tenant_id,id),
  CHECK(approved_by_user_id IS NULL OR requested_by_user_id IS NULL OR approved_by_user_id<>requested_by_user_id)
);
ALTER TABLE procurement_purchase_requests ADD COLUMN converted_po_id uuid;
CREATE TABLE procurement_purchase_order_versions(
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, purchase_order_id uuid NOT NULL, version_no integer NOT NULL, state text NOT NULL DEFAULT 'DRAFT',
  currency char(3) NOT NULL, snapshot_json jsonb NOT NULL DEFAULT '{}', fingerprint text NOT NULL, created_by_user_id uuid REFERENCES users(id), created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(tenant_id,id), UNIQUE(purchase_order_id,version_no), FOREIGN KEY(tenant_id,purchase_order_id) REFERENCES procurement_purchase_orders(tenant_id,id)
);
CREATE TABLE procurement_purchase_order_lines(
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, purchase_order_id uuid NOT NULL, order_version_id uuid NOT NULL, line_no integer NOT NULL,
  description text NOT NULL, item_id uuid, ordered_quantity numeric(30,6) NOT NULL CHECK(ordered_quantity>0), received_quantity numeric(30,6) NOT NULL DEFAULT 0 CHECK(received_quantity>=0), billed_quantity numeric(30,6) NOT NULL DEFAULT 0 CHECK(billed_quantity>=0),
  unit_price_minor bigint NOT NULL CHECK(unit_price_minor>=0), amount_minor bigint NOT NULL CHECK(amount_minor>=0), tax_minor bigint NOT NULL DEFAULT 0 CHECK(tax_minor>=0), branch_id uuid NOT NULL,
  UNIQUE(tenant_id,id), UNIQUE(purchase_order_id,order_version_id,line_no), FOREIGN KEY(tenant_id,purchase_order_id) REFERENCES procurement_purchase_orders(tenant_id,id), FOREIGN KEY(tenant_id,order_version_id) REFERENCES procurement_purchase_order_versions(tenant_id,id), FOREIGN KEY(tenant_id,branch_id) REFERENCES branches(tenant_id,id)
);
CREATE TABLE procurement_purchase_order_approvals(
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, purchase_order_id uuid NOT NULL, order_version_id uuid NOT NULL, approver_user_id uuid NOT NULL,
  decision text NOT NULL CHECK(decision IN('APPROVED','REJECTED')), evidence_json jsonb NOT NULL DEFAULT '{}', request_id text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(),
  FOREIGN KEY(tenant_id,purchase_order_id) REFERENCES procurement_purchase_orders(tenant_id,id), FOREIGN KEY(tenant_id,order_version_id) REFERENCES procurement_purchase_order_versions(tenant_id,id), FOREIGN KEY(approver_user_id) REFERENCES users(id), UNIQUE(tenant_id,purchase_order_id,order_version_id,approver_user_id)
);
CREATE TABLE procurement_purchase_order_history(
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, purchase_order_id uuid NOT NULL, from_status text, to_status text NOT NULL, version integer NOT NULL,
  actor_user_id uuid REFERENCES users(id), reason text, request_id text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), FOREIGN KEY(tenant_id,purchase_order_id) REFERENCES procurement_purchase_orders(tenant_id,id)
);
CREATE INDEX procurement_po_vendor_status_idx ON procurement_purchase_orders(tenant_id,vendor_id,status,created_at);

CREATE TABLE procurement_receipts(
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, branch_id uuid NOT NULL, purchase_order_id uuid NOT NULL, order_version_id uuid NOT NULL,
  receipt_number text NOT NULL, status text NOT NULL DEFAULT 'DRAFT' CHECK(status IN('DRAFT','RECEIVED','PARTIALLY_ACCEPTED','ACCEPTED','REJECTED','REVERSED')), version integer NOT NULL DEFAULT 1, received_at timestamptz NOT NULL,
  created_by_user_id uuid REFERENCES users(id), accepted_by_user_id uuid REFERENCES users(id), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(tenant_id,id), UNIQUE(tenant_id,receipt_number),
  FOREIGN KEY(tenant_id,branch_id) REFERENCES branches(tenant_id,id), FOREIGN KEY(tenant_id,purchase_order_id) REFERENCES procurement_purchase_orders(tenant_id,id), FOREIGN KEY(tenant_id,order_version_id) REFERENCES procurement_purchase_order_versions(tenant_id,id)
);
CREATE TABLE procurement_receipt_lines(
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, receipt_id uuid NOT NULL, po_line_id uuid NOT NULL, received_quantity numeric(30,6) NOT NULL CHECK(received_quantity>0), accepted_quantity numeric(30,6) NOT NULL DEFAULT 0 CHECK(accepted_quantity>=0), rejected_quantity numeric(30,6) NOT NULL DEFAULT 0 CHECK(rejected_quantity>=0), quality_disposition text NOT NULL DEFAULT 'ACCEPTED' CHECK(quality_disposition IN('ACCEPTED','REJECTED','DAMAGED','QUARANTINED')), note text,
  UNIQUE(tenant_id,id), FOREIGN KEY(tenant_id,receipt_id) REFERENCES procurement_receipts(tenant_id,id), FOREIGN KEY(tenant_id,po_line_id) REFERENCES procurement_purchase_order_lines(tenant_id,id), CHECK(accepted_quantity+rejected_quantity<=received_quantity)
);
CREATE TABLE procurement_receipt_history(
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, receipt_id uuid NOT NULL, from_status text, to_status text NOT NULL, actor_user_id uuid REFERENCES users(id), reason text, request_id text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), FOREIGN KEY(tenant_id,receipt_id) REFERENCES procurement_receipts(tenant_id,id)
);
CREATE TABLE procurement_receipt_reversals(
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, receipt_id uuid NOT NULL, reason text NOT NULL, compensating_event_key text NOT NULL, created_by_user_id uuid REFERENCES users(id), created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(tenant_id,compensating_event_key), FOREIGN KEY(tenant_id,receipt_id) REFERENCES procurement_receipts(tenant_id,id)
);

CREATE TABLE procurement_vendor_bills(
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, branch_id uuid NOT NULL, vendor_id uuid NOT NULL, purchase_order_id uuid, bill_number text NOT NULL,
  normalized_invoice_number text NOT NULL, invoice_date date NOT NULL, due_date date NOT NULL, currency char(3) NOT NULL, status text NOT NULL DEFAULT 'DRAFT' CHECK(status IN('DRAFT','SUBMITTED','MATCHING','MATCH_EXCEPTION','MATCHED','PENDING_APPROVAL','APPROVED','POSTING','POSTED','PARTIALLY_PAID','PAID','DISPUTED','ON_HOLD','VOID_PENDING','VOIDED','CREDITED')),
  subtotal_minor bigint NOT NULL DEFAULT 0 CHECK(subtotal_minor>=0), tax_minor bigint NOT NULL DEFAULT 0 CHECK(tax_minor>=0), total_minor bigint NOT NULL CHECK(total_minor>=0), paid_minor bigint NOT NULL DEFAULT 0 CHECK(paid_minor>=0), credited_minor bigint NOT NULL DEFAULT 0 CHECK(credited_minor>=0), version integer NOT NULL DEFAULT 1,
  fingerprint text NOT NULL, requested_by_user_id uuid REFERENCES users(id), approved_by_user_id uuid REFERENCES users(id), posted_by_user_id uuid REFERENCES users(id), posted_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(tenant_id,id), UNIQUE(tenant_id,vendor_id,normalized_invoice_number),
  FOREIGN KEY(tenant_id,branch_id) REFERENCES branches(tenant_id,id), FOREIGN KEY(tenant_id,vendor_id) REFERENCES procurement_vendors(tenant_id,id), FOREIGN KEY(tenant_id,purchase_order_id) REFERENCES procurement_purchase_orders(tenant_id,id), CHECK(paid_minor+credited_minor<=total_minor), CHECK(approved_by_user_id IS NULL OR requested_by_user_id IS NULL OR approved_by_user_id<>requested_by_user_id)
);
CREATE TABLE procurement_vendor_bill_lines(
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, vendor_bill_id uuid NOT NULL, line_no integer NOT NULL, po_line_id uuid, receipt_line_id uuid, description text NOT NULL,
  quantity numeric(30,6) NOT NULL CHECK(quantity>0), unit_price_minor bigint NOT NULL CHECK(unit_price_minor>=0), amount_minor bigint NOT NULL CHECK(amount_minor>=0), tax_minor bigint NOT NULL DEFAULT 0 CHECK(tax_minor>=0), eligible_credit_minor bigint NOT NULL DEFAULT 0 CHECK(eligible_credit_minor>=0),
  UNIQUE(tenant_id,id), UNIQUE(vendor_bill_id,line_no), FOREIGN KEY(tenant_id,vendor_bill_id) REFERENCES procurement_vendor_bills(tenant_id,id), FOREIGN KEY(tenant_id,po_line_id) REFERENCES procurement_purchase_order_lines(tenant_id,id), FOREIGN KEY(tenant_id,receipt_line_id) REFERENCES procurement_receipt_lines(tenant_id,id)
);
CREATE TABLE procurement_vendor_bill_approvals(
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, vendor_bill_id uuid NOT NULL, approver_user_id uuid NOT NULL, decision text NOT NULL CHECK(decision IN('APPROVED','REJECTED')), evidence_json jsonb NOT NULL DEFAULT '{}', request_id text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), FOREIGN KEY(tenant_id,vendor_bill_id) REFERENCES procurement_vendor_bills(tenant_id,id), FOREIGN KEY(approver_user_id) REFERENCES users(id)
);
CREATE TABLE procurement_vendor_bill_history(
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, vendor_bill_id uuid NOT NULL, from_status text, to_status text NOT NULL, actor_user_id uuid REFERENCES users(id), reason text, request_id text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), FOREIGN KEY(tenant_id,vendor_bill_id) REFERENCES procurement_vendor_bills(tenant_id,id)
);
CREATE TABLE procurement_bill_match_results(
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, vendor_bill_id uuid NOT NULL, po_version_id uuid, result text NOT NULL CHECK(result IN('MATCHED','WARNING','BLOCKING_EXCEPTION')), fingerprint text NOT NULL, details_json jsonb NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL DEFAULT now(), FOREIGN KEY(tenant_id,vendor_bill_id) REFERENCES procurement_vendor_bills(tenant_id,id), FOREIGN KEY(tenant_id,po_version_id) REFERENCES procurement_purchase_order_versions(tenant_id,id)
);
CREATE TABLE procurement_bill_match_exceptions(
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, vendor_bill_id uuid NOT NULL, code text NOT NULL, severity text NOT NULL CHECK(severity IN('WARNING','BLOCKING')), details_json jsonb NOT NULL DEFAULT '{}', resolved_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(tenant_id,id), FOREIGN KEY(tenant_id,vendor_bill_id) REFERENCES procurement_vendor_bills(tenant_id,id)
);
CREATE TABLE procurement_bill_match_overrides(
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, vendor_bill_id uuid NOT NULL, exception_id uuid, requested_by_user_id uuid NOT NULL, approved_by_user_id uuid, reason text NOT NULL, evidence_json jsonb NOT NULL DEFAULT '{}', state text NOT NULL DEFAULT 'PENDING_APPROVAL' CHECK(state IN('PENDING_APPROVAL','APPROVED','REJECTED')), created_at timestamptz NOT NULL DEFAULT now(), FOREIGN KEY(tenant_id,vendor_bill_id) REFERENCES procurement_vendor_bills(tenant_id,id), FOREIGN KEY(tenant_id,exception_id) REFERENCES procurement_bill_match_exceptions(tenant_id,id), FOREIGN KEY(requested_by_user_id) REFERENCES users(id), FOREIGN KEY(approved_by_user_id) REFERENCES users(id), CHECK(approved_by_user_id IS NULL OR approved_by_user_id<>requested_by_user_id)
);

CREATE TABLE procurement_ap_open_items(
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, vendor_id uuid NOT NULL, vendor_bill_id uuid NOT NULL, branch_id uuid NOT NULL, due_date date NOT NULL, original_minor bigint NOT NULL CHECK(original_minor>=0), paid_minor bigint NOT NULL DEFAULT 0 CHECK(paid_minor>=0), credited_minor bigint NOT NULL DEFAULT 0 CHECK(credited_minor>=0), written_off_minor bigint NOT NULL DEFAULT 0 CHECK(written_off_minor>=0), status text NOT NULL DEFAULT 'OPEN' CHECK(status IN('OPEN','PARTIALLY_PAID','PAID','ON_HOLD','DISPUTED','WRITTEN_OFF','VOIDED')), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(tenant_id,id), UNIQUE(tenant_id,vendor_bill_id), FOREIGN KEY(tenant_id,vendor_id) REFERENCES procurement_vendors(tenant_id,id), FOREIGN KEY(tenant_id,vendor_bill_id) REFERENCES procurement_vendor_bills(tenant_id,id), FOREIGN KEY(tenant_id,branch_id) REFERENCES branches(tenant_id,id), CHECK(paid_minor+credited_minor+written_off_minor<=original_minor)
);
CREATE TABLE procurement_ap_allocations(
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, open_item_id uuid NOT NULL, allocation_type text NOT NULL CHECK(allocation_type IN('PAYMENT','CREDIT_NOTE','PREPAYMENT','WRITE_OFF','RETURN')), source_id uuid NOT NULL, amount_minor bigint NOT NULL CHECK(amount_minor>0), created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(tenant_id,id), UNIQUE(tenant_id,allocation_type,source_id), FOREIGN KEY(tenant_id,open_item_id) REFERENCES procurement_ap_open_items(tenant_id,id)
);
CREATE TABLE procurement_ap_holds(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL,open_item_id uuid NOT NULL,reason text NOT NULL,active boolean NOT NULL DEFAULT true,created_by_user_id uuid REFERENCES users(id),released_by_user_id uuid REFERENCES users(id),created_at timestamptz NOT NULL DEFAULT now(),released_at timestamptz,FOREIGN KEY(tenant_id,open_item_id) REFERENCES procurement_ap_open_items(tenant_id,id));
CREATE TABLE procurement_ap_disputes(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL,open_item_id uuid NOT NULL,reason text NOT NULL,status text NOT NULL DEFAULT 'OPEN' CHECK(status IN('OPEN','RESOLVED','REJECTED')),created_by_user_id uuid REFERENCES users(id),resolved_by_user_id uuid REFERENCES users(id),created_at timestamptz NOT NULL DEFAULT now(),FOREIGN KEY(tenant_id,open_item_id) REFERENCES procurement_ap_open_items(tenant_id,id));
CREATE TABLE procurement_ap_write_off_requests(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL,open_item_id uuid NOT NULL,amount_minor bigint NOT NULL CHECK(amount_minor>0),reason text NOT NULL,status text NOT NULL DEFAULT 'PENDING_APPROVAL' CHECK(status IN('PENDING_APPROVAL','APPROVED','REJECTED')),requested_by_user_id uuid NOT NULL,approved_by_user_id uuid,created_at timestamptz NOT NULL DEFAULT now(),FOREIGN KEY(tenant_id,open_item_id) REFERENCES procurement_ap_open_items(tenant_id,id),FOREIGN KEY(requested_by_user_id) REFERENCES users(id),FOREIGN KEY(approved_by_user_id) REFERENCES users(id),CHECK(approved_by_user_id IS NULL OR approved_by_user_id<>requested_by_user_id));

 CREATE TABLE procurement_payment_proposals(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL,branch_id uuid NOT NULL,vendor_id uuid NOT NULL,proposal_number text NOT NULL,status text NOT NULL DEFAULT 'DRAFT' CHECK(status IN('DRAFT','PENDING_APPROVAL','APPROVED','PROCESSING','PARTIALLY_COMPLETED','COMPLETED','REJECTED','CANCELLED','FAILED')),currency char(3) NOT NULL,total_minor bigint NOT NULL DEFAULT 0 CHECK(total_minor>=0),requested_by_user_id uuid NOT NULL,approved_by_user_id uuid,version integer NOT NULL DEFAULT 1,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(tenant_id,id),UNIQUE(tenant_id,proposal_number),FOREIGN KEY(tenant_id,branch_id) REFERENCES branches(tenant_id,id),FOREIGN KEY(tenant_id,vendor_id) REFERENCES procurement_vendors(tenant_id,id),FOREIGN KEY(requested_by_user_id) REFERENCES users(id),FOREIGN KEY(approved_by_user_id) REFERENCES users(id),CHECK(approved_by_user_id IS NULL OR approved_by_user_id<>requested_by_user_id));
CREATE TABLE procurement_payment_proposal_items(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL,proposal_id uuid NOT NULL,open_item_id uuid NOT NULL,requested_minor bigint NOT NULL CHECK(requested_minor>0),reserved_minor bigint NOT NULL DEFAULT 0 CHECK(reserved_minor>=0),created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(tenant_id,id),UNIQUE(proposal_id,open_item_id),FOREIGN KEY(tenant_id,proposal_id) REFERENCES procurement_payment_proposals(tenant_id,id),FOREIGN KEY(tenant_id,open_item_id) REFERENCES procurement_ap_open_items(tenant_id,id));
CREATE TABLE procurement_payment_reservations(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL,open_item_id uuid NOT NULL,proposal_id uuid NOT NULL,amount_minor bigint NOT NULL CHECK(amount_minor>0),status text NOT NULL DEFAULT 'ACTIVE' CHECK(status IN('ACTIVE','RELEASED','CONSUMED')),created_at timestamptz NOT NULL DEFAULT now(),released_at timestamptz,UNIQUE(tenant_id,proposal_id,open_item_id),FOREIGN KEY(tenant_id,open_item_id) REFERENCES procurement_ap_open_items(tenant_id,id),FOREIGN KEY(tenant_id,proposal_id) REFERENCES procurement_payment_proposals(tenant_id,id));
CREATE TABLE procurement_vendor_payments(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL,branch_id uuid NOT NULL,vendor_id uuid NOT NULL,payment_reference text NOT NULL,status text NOT NULL DEFAULT 'DRAFT' CHECK(status IN('DRAFT','PENDING_APPROVAL','APPROVED','PROCESSING','SUCCEEDED','FAILED','UNKNOWN','MANUAL_REVIEW','REVERSED','CANCELLED')),currency char(3) NOT NULL,amount_minor bigint NOT NULL CHECK(amount_minor>0),requested_by_user_id uuid NOT NULL,approved_by_user_id uuid,provider_key text NOT NULL,allocation_plan_json jsonb NOT NULL DEFAULT '[]',version integer NOT NULL DEFAULT 1,evidence_hash text,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(tenant_id,id),UNIQUE(tenant_id,payment_reference),UNIQUE(tenant_id,provider_key),FOREIGN KEY(tenant_id,branch_id) REFERENCES branches(tenant_id,id),FOREIGN KEY(tenant_id,vendor_id) REFERENCES procurement_vendors(tenant_id,id),FOREIGN KEY(requested_by_user_id) REFERENCES users(id),FOREIGN KEY(approved_by_user_id) REFERENCES users(id),CHECK(approved_by_user_id IS NULL OR approved_by_user_id<>requested_by_user_id));
CREATE TABLE procurement_vendor_payment_allocations(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL,vendor_payment_id uuid NOT NULL,open_item_id uuid NOT NULL,amount_minor bigint NOT NULL CHECK(amount_minor>0),created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(tenant_id,vendor_payment_id,open_item_id),FOREIGN KEY(tenant_id,vendor_payment_id) REFERENCES procurement_vendor_payments(tenant_id,id),FOREIGN KEY(tenant_id,open_item_id) REFERENCES procurement_ap_open_items(tenant_id,id));
CREATE TABLE procurement_vendor_payment_attempts(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL,vendor_payment_id uuid NOT NULL,attempt_no integer NOT NULL,provider_key text NOT NULL,status text NOT NULL,external_reference text,evidence_json jsonb NOT NULL DEFAULT '{}',created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(vendor_payment_id,attempt_no),FOREIGN KEY(tenant_id,vendor_payment_id) REFERENCES procurement_vendor_payments(tenant_id,id));
 CREATE TABLE procurement_vendor_payment_reconciliations(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL,vendor_payment_id uuid NOT NULL,state text NOT NULL DEFAULT 'PENDING' CHECK(state IN('PENDING','RECONCILED','FAILED')),external_reference text,evidence_json jsonb NOT NULL DEFAULT '{}',reconciled_by_user_id uuid,created_at timestamptz NOT NULL DEFAULT now(),FOREIGN KEY(tenant_id,vendor_payment_id) REFERENCES procurement_vendor_payments(tenant_id,id),FOREIGN KEY(reconciled_by_user_id) REFERENCES users(id));

 CREATE TABLE procurement_vendor_credit_notes(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL,branch_id uuid NOT NULL,vendor_id uuid NOT NULL,vendor_bill_id uuid,status text NOT NULL DEFAULT 'DRAFT' CHECK(status IN('DRAFT','SUBMITTED','PENDING_APPROVAL','APPROVED','POSTING','POSTED','APPLIED','VOID')),currency char(3) NOT NULL,total_minor bigint NOT NULL CHECK(total_minor>0),requested_by_user_id uuid NOT NULL,approved_by_user_id uuid,posted_at timestamptz,version integer NOT NULL DEFAULT 1,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(tenant_id,id),FOREIGN KEY(tenant_id,branch_id) REFERENCES branches(tenant_id,id),FOREIGN KEY(tenant_id,vendor_id) REFERENCES procurement_vendors(tenant_id,id),FOREIGN KEY(tenant_id,vendor_bill_id) REFERENCES procurement_vendor_bills(tenant_id,id),FOREIGN KEY(requested_by_user_id) REFERENCES users(id),FOREIGN KEY(approved_by_user_id) REFERENCES users(id),CHECK(approved_by_user_id IS NULL OR approved_by_user_id<>requested_by_user_id));
CREATE TABLE procurement_vendor_credit_note_lines(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL,credit_note_id uuid NOT NULL,bill_line_id uuid NOT NULL,amount_minor bigint NOT NULL CHECK(amount_minor>0),created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(tenant_id,credit_note_id,bill_line_id),FOREIGN KEY(tenant_id,credit_note_id) REFERENCES procurement_vendor_credit_notes(tenant_id,id),FOREIGN KEY(tenant_id,bill_line_id) REFERENCES procurement_vendor_bill_lines(tenant_id,id));
CREATE TABLE procurement_vendor_credit_applications(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL,credit_note_id uuid NOT NULL,open_item_id uuid NOT NULL,amount_minor bigint NOT NULL CHECK(amount_minor>0),application_type text NOT NULL CHECK(application_type IN('ISSUANCE','APPLICATION')),created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(tenant_id,credit_note_id,open_item_id,application_type),FOREIGN KEY(tenant_id,credit_note_id) REFERENCES procurement_vendor_credit_notes(tenant_id,id),FOREIGN KEY(tenant_id,open_item_id) REFERENCES procurement_ap_open_items(tenant_id,id));
 CREATE TABLE procurement_vendor_returns(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL,branch_id uuid NOT NULL,vendor_id uuid NOT NULL,purchase_order_id uuid,status text NOT NULL DEFAULT 'DRAFT' CHECK(status IN('DRAFT','PENDING_APPROVAL','APPROVED','DISPATCHED','RECEIVED_BY_VENDOR','CREDIT_PENDING','COMPLETED','REJECTED','CANCELLED')),reason text NOT NULL,requested_by_user_id uuid NOT NULL,approved_by_user_id uuid,version integer NOT NULL DEFAULT 1,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(tenant_id,id),FOREIGN KEY(tenant_id,branch_id) REFERENCES branches(tenant_id,id),FOREIGN KEY(tenant_id,vendor_id) REFERENCES procurement_vendors(tenant_id,id),FOREIGN KEY(tenant_id,purchase_order_id) REFERENCES procurement_purchase_orders(tenant_id,id),FOREIGN KEY(requested_by_user_id) REFERENCES users(id),FOREIGN KEY(approved_by_user_id) REFERENCES users(id),CHECK(approved_by_user_id IS NULL OR approved_by_user_id<>requested_by_user_id));
CREATE TABLE procurement_vendor_return_lines(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL,return_id uuid NOT NULL,receipt_line_id uuid NOT NULL,quantity numeric(30,6) NOT NULL CHECK(quantity>0),created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(tenant_id,return_id,receipt_line_id),FOREIGN KEY(tenant_id,return_id) REFERENCES procurement_vendor_returns(tenant_id,id),FOREIGN KEY(tenant_id,receipt_line_id) REFERENCES procurement_receipt_lines(tenant_id,id));

CREATE TABLE procurement_expense_categories(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL,name text NOT NULL,account_id uuid,allow_non_po boolean NOT NULL DEFAULT false,active boolean NOT NULL DEFAULT true,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(tenant_id,id),FOREIGN KEY(tenant_id) REFERENCES tenants(id));
CREATE TABLE procurement_recurring_expense_templates(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL,vendor_id uuid,category_id uuid NOT NULL,amount_minor bigint NOT NULL CHECK(amount_minor>=0),currency char(3) NOT NULL,frequency text NOT NULL CHECK(frequency IN('WEEKLY','MONTHLY','QUARTERLY','YEARLY')),next_due_on date NOT NULL,status text NOT NULL DEFAULT 'ACTIVE' CHECK(status IN('ACTIVE','PAUSED','ENDED')),created_by_user_id uuid REFERENCES users(id),created_at timestamptz NOT NULL DEFAULT now(),FOREIGN KEY(tenant_id,vendor_id) REFERENCES procurement_vendors(tenant_id,id),FOREIGN KEY(tenant_id,category_id) REFERENCES procurement_expense_categories(tenant_id,id));
 CREATE TABLE procurement_vendor_prepayments(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL,vendor_id uuid NOT NULL,branch_id uuid NOT NULL,currency char(3) NOT NULL,prepaid_minor bigint NOT NULL CHECK(prepaid_minor>0),applied_minor bigint NOT NULL DEFAULT 0 CHECK(applied_minor>=0),refunded_minor bigint NOT NULL DEFAULT 0 CHECK(refunded_minor>=0),status text NOT NULL DEFAULT 'DRAFT' CHECK(status IN('DRAFT','APPROVED','PAID','PARTIALLY_APPLIED','APPLIED','REFUNDED')),requested_by_user_id uuid NOT NULL,approved_by_user_id uuid,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(tenant_id,id),FOREIGN KEY(tenant_id,vendor_id) REFERENCES procurement_vendors(tenant_id,id),FOREIGN KEY(tenant_id,branch_id) REFERENCES branches(tenant_id,id),FOREIGN KEY(requested_by_user_id) REFERENCES users(id),FOREIGN KEY(approved_by_user_id) REFERENCES users(id),CHECK(applied_minor+refunded_minor<=prepaid_minor),CHECK(approved_by_user_id IS NULL OR approved_by_user_id<>requested_by_user_id));
CREATE TABLE procurement_vendor_prepayment_applications(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL,prepayment_id uuid NOT NULL,open_item_id uuid NOT NULL,amount_minor bigint NOT NULL CHECK(amount_minor>0),created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(tenant_id,prepayment_id,open_item_id),FOREIGN KEY(tenant_id,prepayment_id) REFERENCES procurement_vendor_prepayments(tenant_id,id),FOREIGN KEY(tenant_id,open_item_id) REFERENCES procurement_ap_open_items(tenant_id,id));
CREATE TABLE procurement_tolerance_policies(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL,name text NOT NULL,quantity_numerator bigint NOT NULL DEFAULT 0 CHECK(quantity_numerator>=0),quantity_denominator bigint NOT NULL DEFAULT 1 CHECK(quantity_denominator>0),price_tolerance_minor bigint NOT NULL DEFAULT 0 CHECK(price_tolerance_minor>=0),percentage_numerator bigint NOT NULL DEFAULT 0 CHECK(percentage_numerator>=0),percentage_denominator bigint NOT NULL DEFAULT 1 CHECK(percentage_denominator>0),tax_tolerance_minor bigint NOT NULL DEFAULT 0 CHECK(tax_tolerance_minor>=0),active boolean NOT NULL DEFAULT true,version integer NOT NULL DEFAULT 1,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(tenant_id,id));
CREATE TABLE procurement_approval_policies(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL,name text NOT NULL,threshold_minor bigint NOT NULL DEFAULT 0 CHECK(threshold_minor>=0),dual_control boolean NOT NULL DEFAULT true,active boolean NOT NULL DEFAULT true,version integer NOT NULL DEFAULT 1,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(tenant_id,id));
CREATE TABLE procurement_configuration_checklists(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL,item_code text NOT NULL,status text NOT NULL DEFAULT 'PENDING' CHECK(status IN('PENDING','READY','BLOCKED')),evidence_json jsonb NOT NULL DEFAULT '{}',updated_by_user_id uuid REFERENCES users(id),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(tenant_id,item_code));

CREATE OR REPLACE FUNCTION procurement_append_only_guard() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'PROCUREMENT_HISTORY_APPEND_ONLY' USING ERRCODE='55000'; END $$;
DO $$ DECLARE t text; BEGIN FOREACH t IN ARRAY ARRAY['procurement_vendor_status_history','procurement_purchase_request_history','procurement_purchase_order_history','procurement_receipt_history','procurement_vendor_bill_history'] LOOP EXECUTE format('CREATE TRIGGER %I_append_only BEFORE UPDATE OR DELETE ON %I FOR EACH ROW EXECUTE FUNCTION procurement_append_only_guard()',t,t); END LOOP; END $$;
ALTER TABLE procurement_purchase_requests ADD CONSTRAINT procurement_purchase_requests_converted_po_fk FOREIGN KEY(tenant_id,converted_po_id) REFERENCES procurement_purchase_orders(tenant_id,id);
CREATE OR REPLACE FUNCTION procurement_posted_immutable_guard() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF OLD.status IN('APPROVED','POSTED','PAID','COMPLETED') AND (NEW.total_minor IS DISTINCT FROM OLD.total_minor OR NEW.vendor_id IS DISTINCT FROM OLD.vendor_id OR NEW.currency IS DISTINCT FROM OLD.currency) THEN RAISE EXCEPTION 'PROCUREMENT_IMMUTABLE' USING ERRCODE='55000'; END IF; RETURN NEW; END $$;
CREATE TRIGGER procurement_po_immutable BEFORE UPDATE ON procurement_purchase_orders FOR EACH ROW EXECUTE FUNCTION procurement_posted_immutable_guard();
CREATE TRIGGER procurement_bill_immutable BEFORE UPDATE ON procurement_vendor_bills FOR EACH ROW EXECUTE FUNCTION procurement_posted_immutable_guard();
CREATE INDEX procurement_receipts_po_idx ON procurement_receipts(tenant_id,purchase_order_id,status);
CREATE INDEX procurement_bills_due_idx ON procurement_vendor_bills(tenant_id,status,due_date);
CREATE INDEX procurement_ap_aging_idx ON procurement_ap_open_items(tenant_id,vendor_id,due_date,status);
CREATE INDEX procurement_payment_reservation_idx ON procurement_payment_reservations(tenant_id,open_item_id,status);

INSERT INTO permissions(code,description) SELECT code,'Sprint 15 procurement and accounts payable permission' FROM unnest(ARRAY[
 'procurement.vendor.read','procurement.vendor.manage','procurement.vendor.payment_method.manage','procurement.request.read','procurement.request.create','procurement.request.submit','procurement.request.approve','procurement.request.cancel','procurement.po.read','procurement.po.create','procurement.po.submit','procurement.po.approve','procurement.po.send','procurement.po.amend','procurement.po.cancel','procurement.po.close','procurement.receipt.read','procurement.receipt.create','procurement.receipt.accept','procurement.receipt.reject','procurement.receipt.reverse','procurement.bill.read','procurement.bill.create','procurement.bill.submit','procurement.bill.match','procurement.bill.match_override','procurement.bill.approve','procurement.bill.post','procurement.bill.hold','procurement.bill.void','procurement.ap.read','procurement.ap.hold','procurement.ap.write_off','procurement.payment.read','procurement.payment.create','procurement.payment.submit','procurement.payment.approve','procurement.payment.process','procurement.payment.reconcile','procurement.payment.reverse','procurement.credit_note.read','procurement.credit_note.create','procurement.credit_note.approve','procurement.credit_note.post','procurement.credit_note.apply','procurement.return.read','procurement.return.create','procurement.return.approve','procurement.return.dispatch','procurement.return.complete','procurement.report.read','procurement.export'
 ]) code ON CONFLICT DO NOTHING;
INSERT INTO role_permissions(role,permission_code) SELECT r.role,p.code FROM unnest(ARRAY['SALON_OWNER','BRANCH_MANAGER','ACCOUNTANT']) r(role) CROSS JOIN permissions p WHERE p.code LIKE 'procurement.%' ON CONFLICT DO NOTHING;
INSERT INTO role_permissions(role,permission_code) SELECT 'RECEPTIONIST',code FROM permissions WHERE code IN('procurement.vendor.read','procurement.request.read','procurement.request.create','procurement.request.submit','procurement.po.read','procurement.receipt.read','procurement.bill.read','procurement.ap.read','procurement.payment.read') ON CONFLICT DO NOTHING;
INSERT INTO schema_migrations(version) VALUES('0031_procurement_vendor_bills_accounts_payable');
COMMIT;
