BEGIN;
DROP TRIGGER IF EXISTS procurement_partial_approval_po_guard ON procurement_purchase_order_lines;
DROP FUNCTION IF EXISTS procurement_partial_approval_po_guard();
DROP TRIGGER IF EXISTS procurement_receipt_transition_guard ON procurement_receipts;
DROP TRIGGER IF EXISTS procurement_payment_proposal_transition_guard ON procurement_payment_proposals;
DROP TRIGGER IF EXISTS procurement_vendor_payment_transition_guard ON procurement_vendor_payments;
DROP TRIGGER IF EXISTS procurement_credit_note_transition_guard ON procurement_vendor_credit_notes;
DROP TRIGGER IF EXISTS procurement_vendor_return_transition_guard ON procurement_vendor_returns;
DROP FUNCTION IF EXISTS procurement_status_transition_guard();
DROP TRIGGER IF EXISTS procurement_posted_bill_line_immutable ON procurement_vendor_bill_lines;
DROP FUNCTION IF EXISTS procurement_posted_bill_line_immutable();
DROP TRIGGER IF EXISTS procurement_posted_bill_immutable ON procurement_vendor_bills;
DROP FUNCTION IF EXISTS procurement_posted_bill_immutable();
DROP TABLE IF EXISTS procurement_po_email_deliveries,procurement_vendor_remittance_deliveries,procurement_ap_write_off_approvals,procurement_expense_bill_lines,procurement_expense_bills,procurement_inventory_source_events CASCADE;
ALTER TABLE procurement_vendor_credit_applications DROP COLUMN IF EXISTS created_by_user_id,DROP COLUMN IF EXISTS evidence_json;
ALTER TABLE procurement_vendor_credit_notes DROP CONSTRAINT IF EXISTS procurement_vendor_credit_notes_status_check;
ALTER TABLE procurement_vendor_credit_notes ADD CONSTRAINT procurement_vendor_credit_notes_status_check CHECK(status IN('DRAFT','SUBMITTED','PENDING_APPROVAL','APPROVED','POSTING','POSTED','APPLIED','VOID'));
ALTER TABLE procurement_vendor_payments DROP CONSTRAINT IF EXISTS procurement_vendor_payments_status_check;
ALTER TABLE procurement_vendor_payments ADD CONSTRAINT procurement_vendor_payments_status_check CHECK(status IN('DRAFT','PENDING_APPROVAL','APPROVED','PROCESSING','SUCCEEDED','FAILED','UNKNOWN','MANUAL_REVIEW','REVERSED','CANCELLED'));
ALTER TABLE procurement_vendor_payments DROP COLUMN IF EXISTS reversal_reason,DROP COLUMN IF EXISTS reversal_approved_by_user_id,DROP COLUMN IF EXISTS reversal_requested_by_user_id,DROP COLUMN IF EXISTS allocation_plan_fingerprint;
ALTER TABLE procurement_payment_reservations DROP COLUMN IF EXISTS released_at,DROP COLUMN IF EXISTS consumed_at,DROP COLUMN IF EXISTS expires_at;
ALTER TABLE procurement_payment_proposals DROP COLUMN IF EXISTS expires_at;
ALTER TABLE procurement_bill_match_overrides DROP COLUMN IF EXISTS approved_snapshot_json,DROP COLUMN IF EXISTS approval_fingerprint,DROP COLUMN IF EXISTS approved_at;
ALTER TABLE procurement_bill_match_results DROP COLUMN IF EXISTS bill_fingerprint,DROP COLUMN IF EXISTS receipt_fingerprint,DROP COLUMN IF EXISTS po_fingerprint,DROP COLUMN IF EXISTS policy_version,DROP COLUMN IF EXISTS currency_result,DROP COLUMN IF EXISTS fee_variance_minor,DROP COLUMN IF EXISTS tax_variance_minor;
ALTER TABLE procurement_receipts DROP COLUMN IF EXISTS reversal_reason,DROP COLUMN IF EXISTS reversal_approved_by_user_id,DROP COLUMN IF EXISTS reversal_requested_by_user_id;
ALTER TABLE procurement_purchase_order_lines DROP COLUMN IF EXISTS economics_fingerprint;
ALTER TABLE procurement_purchase_order_versions DROP COLUMN IF EXISTS approved_at,DROP COLUMN IF EXISTS approved_by_user_id;
ALTER TABLE procurement_purchase_request_approvals DROP COLUMN IF EXISTS allocation_fingerprint,DROP COLUMN IF EXISTS allocation_json;
DELETE FROM schema_migrations WHERE version='0032_sprint15_procurement_correctness_closure';
COMMIT;
