BEGIN;

-- Sprint 16 is opt-in. Existing tenants remain disabled until explicitly configured.
CREATE TABLE asset_module_configurations(
  tenant_id uuid PRIMARY KEY REFERENCES tenants(id),
  status text NOT NULL DEFAULT 'DISABLED' CHECK(status IN('DISABLED','INCOMPLETE','READY','ACTIVE')),
  cutover_date date,
  version integer NOT NULL DEFAULT 1,
  updated_by_user_id uuid REFERENCES users(id),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE asset_command_idempotency(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenants(id), operation text NOT NULL, idempotency_key text NOT NULL, request_fingerprint text NOT NULL, response_json jsonb, state text NOT NULL DEFAULT 'PROCESSING' CHECK(state IN('PROCESSING','COMPLETED')), created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(tenant_id,operation,idempotency_key));

CREATE TABLE asset_categories(
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL,
  parent_id uuid, code text NOT NULL, name text NOT NULL, description text,
  active boolean NOT NULL DEFAULT true, version integer NOT NULL DEFAULT 1,
  created_by_user_id uuid REFERENCES users(id), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(tenant_id,id), UNIQUE(tenant_id,code),
  FOREIGN KEY(tenant_id) REFERENCES tenants(id), FOREIGN KEY(tenant_id,parent_id) REFERENCES asset_categories(tenant_id,id)
);
CREATE TABLE asset_depreciation_policies(
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL,
  category_id uuid, version_no integer NOT NULL DEFAULT 1, state text NOT NULL DEFAULT 'DRAFT' CHECK(state IN('DRAFT','ACTIVE','SUPERSEDED','RETIRED')),
  method text NOT NULL CHECK(method IN('STRAIGHT_LINE','DECLINING_BALANCE','UNITS_OF_PRODUCTION')),
  convention text NOT NULL DEFAULT 'FULL_MONTH' CHECK(convention IN('DAILY_PRORATA','FULL_MONTH','HALF_MONTH','NEXT_MONTH','NO_PRORATA')),
  useful_life_periods integer NOT NULL CHECK(useful_life_periods>0), residual_value_minor bigint NOT NULL DEFAULT 0 CHECK(residual_value_minor>=0),
  rate_numerator bigint, rate_denominator bigint, expected_units bigint,
  effective_from date NOT NULL, effective_to date, fingerprint text NOT NULL,
  created_by_user_id uuid REFERENCES users(id), created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(tenant_id,id), UNIQUE(tenant_id,category_id,version_no), FOREIGN KEY(tenant_id) REFERENCES tenants(id), FOREIGN KEY(tenant_id,category_id) REFERENCES asset_categories(tenant_id,id),
  CHECK(rate_denominator IS NULL OR rate_denominator>0), CHECK(rate_numerator IS NULL OR rate_numerator>=0), CHECK(expected_units IS NULL OR expected_units>0)
);
CREATE TABLE asset_capitalization_policies(
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, category_id uuid,
  threshold_minor bigint NOT NULL DEFAULT 0 CHECK(threshold_minor>=0), currency char(3) NOT NULL,
  effective_from date NOT NULL, effective_to date, version_no integer NOT NULL DEFAULT 1, state text NOT NULL DEFAULT 'DRAFT' CHECK(state IN('DRAFT','ACTIVE','SUPERSEDED','RETIRED')), fingerprint text NOT NULL,
  UNIQUE(tenant_id,id), FOREIGN KEY(tenant_id) REFERENCES tenants(id), FOREIGN KEY(tenant_id,category_id) REFERENCES asset_categories(tenant_id,id)
);
CREATE TABLE asset_maintenance_policies(
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, category_id uuid,
  interval_days integer CHECK(interval_days IS NULL OR interval_days>0), interval_usage bigint, checklist_json jsonb NOT NULL DEFAULT '[]', version_no integer NOT NULL DEFAULT 1, state text NOT NULL DEFAULT 'DRAFT' CHECK(state IN('DRAFT','ACTIVE','SUPERSEDED','RETIRED')), fingerprint text NOT NULL,
  UNIQUE(tenant_id,id), FOREIGN KEY(tenant_id) REFERENCES tenants(id), FOREIGN KEY(tenant_id,category_id) REFERENCES asset_categories(tenant_id,id)
);
CREATE TABLE asset_gl_mappings(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, category_id uuid, mapping_json jsonb NOT NULL DEFAULT '{}', version_no integer NOT NULL DEFAULT 1, state text NOT NULL DEFAULT 'DRAFT' CHECK(state IN('DRAFT','ACTIVE','SUPERSEDED','RETIRED')), fingerprint text NOT NULL, UNIQUE(tenant_id,id), FOREIGN KEY(tenant_id) REFERENCES tenants(id), FOREIGN KEY(tenant_id,category_id) REFERENCES asset_categories(tenant_id,id));
CREATE TABLE asset_configuration_checklists(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, item_code text NOT NULL, status text NOT NULL DEFAULT 'PENDING' CHECK(status IN('PENDING','READY','BLOCKED')), evidence_json jsonb NOT NULL DEFAULT '{}', updated_by_user_id uuid REFERENCES users(id), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(tenant_id,item_code), FOREIGN KEY(tenant_id) REFERENCES tenants(id));

CREATE TABLE asset_candidates(
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, branch_id uuid NOT NULL, candidate_number text NOT NULL,
  status text NOT NULL DEFAULT 'DRAFT' CHECK(status IN('DRAFT','PENDING_REVIEW','CLASSIFIED_EXPENSE','CLASSIFIED_INVENTORY','PENDING_CAPITALIZATION','APPROVED_FOR_CAPITALIZATION','CAPITALIZED','REJECTED','CANCELLED')),
  classification text CHECK(classification IN('EXPENSE','INVENTORY','FIXED_ASSET')), name text, description text, currency char(3) NOT NULL, eligible_amount_minor bigint NOT NULL CHECK(eligible_amount_minor>=0), allocated_amount_minor bigint NOT NULL DEFAULT 0 CHECK(allocated_amount_minor>=0), quantity numeric(30,6) NOT NULL DEFAULT 1 CHECK(quantity>0), source_fingerprint text, source_version integer, version integer NOT NULL DEFAULT 1, requested_by_user_id uuid REFERENCES users(id), approved_by_user_id uuid REFERENCES users(id), approved_snapshot_json jsonb, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(tenant_id,id), UNIQUE(tenant_id,candidate_number), FOREIGN KEY(tenant_id,branch_id) REFERENCES branches(tenant_id,id), FOREIGN KEY(tenant_id) REFERENCES tenants(id), CHECK(allocated_amount_minor<=eligible_amount_minor), CHECK(approved_by_user_id IS NULL OR approved_by_user_id<>requested_by_user_id)
);
CREATE TABLE asset_candidate_source_allocations(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, candidate_id uuid NOT NULL, source_type text NOT NULL, source_id uuid NOT NULL, source_line_id uuid, generation integer NOT NULL DEFAULT 1, eligible_amount_minor bigint NOT NULL CHECK(eligible_amount_minor>=0), allocated_amount_minor bigint NOT NULL CHECK(allocated_amount_minor>=0), fingerprint text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(tenant_id,source_type,source_id,generation), FOREIGN KEY(tenant_id,candidate_id) REFERENCES asset_candidates(tenant_id,id));
CREATE TABLE asset_candidate_classification_history(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, candidate_id uuid NOT NULL, from_classification text, to_classification text NOT NULL, actor_user_id uuid REFERENCES users(id), reason text NOT NULL, version integer NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), FOREIGN KEY(tenant_id,candidate_id) REFERENCES asset_candidates(tenant_id,id));
CREATE TABLE asset_asset_code_sequences(tenant_id uuid PRIMARY KEY REFERENCES tenants(id), next_value bigint NOT NULL DEFAULT 1);
CREATE TABLE assets(
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, branch_id uuid NOT NULL, category_id uuid NOT NULL, policy_id uuid, asset_code text NOT NULL, name text NOT NULL, description text, brand text, model text, serial_number text, barcode_payload text, status text NOT NULL DEFAULT 'DRAFT' CHECK(status IN('DRAFT','PENDING_CAPITALIZATION','ACTIVE','IN_MAINTENANCE','IN_TRANSIT','IDLE','IMPAIRED','RETIRED','DISPOSED','LOST','STOLEN','DESTROYED','CANCELLED')),
  room_location text, custodian_user_id uuid REFERENCES users(id), vendor_id uuid, acquisition_date date, in_service_date date, capitalization_date date, disposal_date date, currency char(3) NOT NULL, gross_carrying_amount_minor bigint NOT NULL DEFAULT 0 CHECK(gross_carrying_amount_minor>=0), residual_value_minor bigint NOT NULL DEFAULT 0 CHECK(residual_value_minor>=0), accumulated_depreciation_minor bigint NOT NULL DEFAULT 0 CHECK(accumulated_depreciation_minor>=0), accumulated_impairment_minor bigint NOT NULL DEFAULT 0 CHECK(accumulated_impairment_minor>=0), useful_life_periods integer CHECK(useful_life_periods IS NULL OR useful_life_periods>0), depreciation_method text, depreciation_convention text, approved_snapshot_json jsonb, version integer NOT NULL DEFAULT 1, created_by_user_id uuid REFERENCES users(id), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(tenant_id,id), UNIQUE(tenant_id,asset_code), FOREIGN KEY(tenant_id,branch_id) REFERENCES branches(tenant_id,id), FOREIGN KEY(tenant_id,category_id) REFERENCES asset_categories(tenant_id,id), FOREIGN KEY(tenant_id,policy_id) REFERENCES asset_depreciation_policies(tenant_id,id), FOREIGN KEY(tenant_id) REFERENCES tenants(id), CHECK(residual_value_minor<=gross_carrying_amount_minor), CHECK(accumulated_depreciation_minor<=gross_carrying_amount_minor-residual_value_minor)
);
CREATE UNIQUE INDEX asset_serial_uq ON assets(tenant_id,serial_number) WHERE serial_number IS NOT NULL;
CREATE TABLE asset_components(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, parent_asset_id uuid NOT NULL, component_asset_id uuid NOT NULL, replacement_policy_json jsonb NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(tenant_id,parent_asset_id,component_asset_id), CHECK(parent_asset_id<>component_asset_id), FOREIGN KEY(tenant_id,parent_asset_id) REFERENCES assets(tenant_id,id), FOREIGN KEY(tenant_id,component_asset_id) REFERENCES assets(tenant_id,id));
CREATE TABLE asset_bundles(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, parent_asset_id uuid NOT NULL, source_fingerprint text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(tenant_id,parent_asset_id), FOREIGN KEY(tenant_id,parent_asset_id) REFERENCES assets(tenant_id,id));
CREATE TABLE asset_status_history(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, asset_id uuid NOT NULL, from_status text, to_status text NOT NULL, actor_user_id uuid REFERENCES users(id), reason text, request_id text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), FOREIGN KEY(tenant_id,asset_id) REFERENCES assets(tenant_id,id));
CREATE TABLE asset_documents(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, asset_id uuid NOT NULL, storage_key text NOT NULL, mime_type text, checksum text, status text NOT NULL DEFAULT 'PENDING_UPLOAD' CHECK(status IN('PENDING_UPLOAD','READY','DELETED')), uploaded_by_user_id uuid REFERENCES users(id), created_at timestamptz NOT NULL DEFAULT now(), FOREIGN KEY(tenant_id,asset_id) REFERENCES assets(tenant_id,id));
CREATE TABLE asset_photos(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, asset_id uuid NOT NULL, storage_key text NOT NULL, checksum text, status text NOT NULL DEFAULT 'PENDING_UPLOAD' CHECK(status IN('PENDING_UPLOAD','READY','DELETED')), uploaded_by_user_id uuid REFERENCES users(id), created_at timestamptz NOT NULL DEFAULT now(), FOREIGN KEY(tenant_id,asset_id) REFERENCES assets(tenant_id,id));
CREATE TABLE asset_tags(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, asset_id uuid NOT NULL, tag text NOT NULL, UNIQUE(tenant_id,asset_id,tag), FOREIGN KEY(tenant_id,asset_id) REFERENCES assets(tenant_id,id));

CREATE TABLE asset_capitalization_requests(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, branch_id uuid NOT NULL, status text NOT NULL DEFAULT 'DRAFT' CHECK(status IN('DRAFT','PENDING_APPROVAL','APPROVED','PROCESSING','CAPITALIZED','REJECTED','CANCELLED','FAILED')), currency char(3) NOT NULL, gross_amount_minor bigint NOT NULL CHECK(gross_amount_minor>0), in_service_date date NOT NULL, location text, custodian_user_id uuid REFERENCES users(id), policy_snapshot_json jsonb NOT NULL DEFAULT '{}', source_fingerprint text NOT NULL, version integer NOT NULL DEFAULT 1, requested_by_user_id uuid NOT NULL REFERENCES users(id), approved_by_user_id uuid REFERENCES users(id), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(tenant_id,id), FOREIGN KEY(tenant_id,branch_id) REFERENCES branches(tenant_id,id), CHECK(approved_by_user_id IS NULL OR approved_by_user_id<>requested_by_user_id));
CREATE TABLE asset_capitalization_request_lines(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, request_id uuid NOT NULL, candidate_id uuid NOT NULL, amount_minor bigint NOT NULL CHECK(amount_minor>0), version integer NOT NULL DEFAULT 1, UNIQUE(tenant_id,request_id,candidate_id), FOREIGN KEY(tenant_id,request_id) REFERENCES asset_capitalization_requests(tenant_id,id), FOREIGN KEY(tenant_id,candidate_id) REFERENCES asset_candidates(tenant_id,id));
CREATE TABLE asset_capitalization_approvals(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, request_id uuid NOT NULL, approver_user_id uuid NOT NULL REFERENCES users(id), snapshot_fingerprint text NOT NULL, reason text, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(tenant_id,request_id), FOREIGN KEY(tenant_id,request_id) REFERENCES asset_capitalization_requests(tenant_id,id));
CREATE TABLE asset_cost_components(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, request_id uuid NOT NULL, component_type text NOT NULL CHECK(component_type IN('PURCHASE_PRICE','FREIGHT','INSTALLATION','NON_RECOVERABLE_TAX','PROFESSIONAL_FEE','SITE_PREPARATION','OTHER_APPROVED_CAPITAL_COST')), amount_minor bigint NOT NULL CHECK(amount_minor>=0), currency char(3) NOT NULL, evidence_json jsonb NOT NULL DEFAULT '{}', UNIQUE(tenant_id,request_id,component_type), FOREIGN KEY(tenant_id,request_id) REFERENCES asset_capitalization_requests(tenant_id,id));
CREATE TABLE asset_capitalization_history(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, request_id uuid NOT NULL, asset_id uuid, from_status text, to_status text NOT NULL, actor_user_id uuid REFERENCES users(id), source_fingerprint text NOT NULL, request_id_text text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), FOREIGN KEY(tenant_id,request_id) REFERENCES asset_capitalization_requests(tenant_id,id), FOREIGN KEY(tenant_id,asset_id) REFERENCES assets(tenant_id,id));

CREATE TABLE asset_depreciation_runs(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, book_id uuid NOT NULL, period_id uuid NOT NULL, status text NOT NULL DEFAULT 'DRAFT' CHECK(status IN('DRAFT','CALCULATING','READY','PENDING_APPROVAL','APPROVED','POSTING','POSTED','PARTIALLY_FAILED','FAILED','REVERSED')), cutoff_date date NOT NULL, method_snapshot_json jsonb NOT NULL DEFAULT '{}', asset_scope_json jsonb NOT NULL DEFAULT '{}', candidate_count integer NOT NULL DEFAULT 0, total_amount_minor bigint NOT NULL DEFAULT 0 CHECK(total_amount_minor>=0), fingerprint text NOT NULL, requested_by_user_id uuid REFERENCES users(id), approved_by_user_id uuid REFERENCES users(id), posted_by_user_id uuid REFERENCES users(id), version integer NOT NULL DEFAULT 1, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(tenant_id,book_id,period_id), FOREIGN KEY(tenant_id,book_id) REFERENCES accounting_books(tenant_id,id), FOREIGN KEY(tenant_id,period_id) REFERENCES accounting_periods(tenant_id,id), CHECK(approved_by_user_id IS NULL OR approved_by_user_id<>requested_by_user_id));
ALTER TABLE asset_depreciation_runs ADD CONSTRAINT asset_depreciation_runs_tenant_id_uq UNIQUE(tenant_id,id);
CREATE TABLE asset_depreciation_run_lines(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, run_id uuid NOT NULL, asset_id uuid NOT NULL, opening_gross_minor bigint NOT NULL, opening_accumulated_minor bigint NOT NULL, period_amount_minor bigint NOT NULL CHECK(period_amount_minor>=0), closing_accumulated_minor bigint NOT NULL, closing_nbv_minor bigint NOT NULL, method text NOT NULL, policy_version integer, remainder_minor bigint NOT NULL DEFAULT 0, status text NOT NULL DEFAULT 'READY', source_fingerprint text NOT NULL, UNIQUE(tenant_id,run_id,asset_id), FOREIGN KEY(tenant_id,run_id) REFERENCES asset_depreciation_runs(tenant_id,id), FOREIGN KEY(tenant_id,asset_id) REFERENCES assets(tenant_id,id), CHECK(closing_accumulated_minor<=opening_gross_minor), CHECK(closing_nbv_minor>=0));
CREATE TABLE asset_depreciation_schedules(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, asset_id uuid NOT NULL, period_start date NOT NULL, period_end date NOT NULL, amount_minor bigint NOT NULL CHECK(amount_minor>=0), cumulative_minor bigint NOT NULL CHECK(cumulative_minor>=0), fingerprint text NOT NULL, posted_run_id uuid, UNIQUE(tenant_id,asset_id,period_start), FOREIGN KEY(tenant_id,asset_id) REFERENCES assets(tenant_id,id), FOREIGN KEY(tenant_id,posted_run_id) REFERENCES asset_depreciation_runs(tenant_id,id));
CREATE TABLE asset_depreciation_adjustments(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, asset_id uuid NOT NULL, amount_minor bigint NOT NULL, reason text NOT NULL, status text NOT NULL DEFAULT 'DRAFT' CHECK(status IN('DRAFT','PENDING_APPROVAL','APPROVED','POSTED','REJECTED')), requested_by_user_id uuid NOT NULL REFERENCES users(id), approved_by_user_id uuid REFERENCES users(id), version integer NOT NULL DEFAULT 1, created_at timestamptz NOT NULL DEFAULT now(), FOREIGN KEY(tenant_id,asset_id) REFERENCES assets(tenant_id,id), CHECK(approved_by_user_id IS NULL OR approved_by_user_id<>requested_by_user_id));
CREATE TABLE asset_depreciation_posting_history(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, run_id uuid NOT NULL, source_candidate_id uuid, state text NOT NULL, fingerprint text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(tenant_id,run_id,state), FOREIGN KEY(tenant_id,run_id) REFERENCES asset_depreciation_runs(tenant_id,id));

CREATE TABLE asset_maintenance_plans(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, branch_id uuid, asset_id uuid, category_id uuid, status text NOT NULL DEFAULT 'DRAFT' CHECK(status IN('DRAFT','ACTIVE','PAUSED','RETIRED')), maintenance_type text NOT NULL, trigger_basis text NOT NULL CHECK(trigger_basis IN('CALENDAR','USAGE_FOUNDATION','MANUAL')), interval_days integer, interval_usage bigint, checklist_json jsonb NOT NULL DEFAULT '[]', assigned_team text, vendor_id uuid, lead_time_days integer NOT NULL DEFAULT 0, estimated_downtime_minutes integer NOT NULL DEFAULT 0, estimated_cost_minor bigint NOT NULL DEFAULT 0, version integer NOT NULL DEFAULT 1, created_by_user_id uuid REFERENCES users(id), created_at timestamptz NOT NULL DEFAULT now(), FOREIGN KEY(tenant_id,branch_id) REFERENCES branches(tenant_id,id), FOREIGN KEY(tenant_id,asset_id) REFERENCES assets(tenant_id,id), FOREIGN KEY(tenant_id,category_id) REFERENCES asset_categories(tenant_id,id));
ALTER TABLE asset_maintenance_plans ADD CONSTRAINT asset_maintenance_plans_tenant_id_uq UNIQUE(tenant_id,id);
CREATE TABLE asset_maintenance_work_orders(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, branch_id uuid NOT NULL, asset_id uuid NOT NULL, plan_id uuid, status text NOT NULL DEFAULT 'DRAFT' CHECK(status IN('DRAFT','SCHEDULED','ASSIGNED','IN_PROGRESS','WAITING_PARTS','WAITING_VENDOR','COMPLETED','VERIFIED','CANCELLED','REOPENED')), work_type text NOT NULL, priority text NOT NULL DEFAULT 'NORMAL', problem text, scheduled_start_at timestamptz, scheduled_end_at timestamptz, assigned_user_id uuid REFERENCES users(id), vendor_id uuid, downtime_minutes integer NOT NULL DEFAULT 0, total_cost_minor bigint NOT NULL DEFAULT 0, completion_notes text, evidence_json jsonb NOT NULL DEFAULT '{}', verified_by_user_id uuid REFERENCES users(id), version integer NOT NULL DEFAULT 1, created_by_user_id uuid REFERENCES users(id), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(tenant_id,id), FOREIGN KEY(tenant_id,branch_id) REFERENCES branches(tenant_id,id), FOREIGN KEY(tenant_id,asset_id) REFERENCES assets(tenant_id,id), FOREIGN KEY(tenant_id,plan_id) REFERENCES asset_maintenance_plans(tenant_id,id), CHECK(verified_by_user_id IS NULL OR verified_by_user_id<>assigned_user_id));
CREATE TABLE asset_maintenance_work_order_tasks(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, work_order_id uuid NOT NULL, sequence_no integer NOT NULL, description text NOT NULL, status text NOT NULL DEFAULT 'PENDING' CHECK(status IN('PENDING','DONE','SKIPPED')), completed_by_user_id uuid REFERENCES users(id), completed_at timestamptz, UNIQUE(tenant_id,work_order_id,sequence_no), FOREIGN KEY(tenant_id,work_order_id) REFERENCES asset_maintenance_work_orders(tenant_id,id));
CREATE TABLE asset_maintenance_costs(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, work_order_id uuid NOT NULL, component_type text NOT NULL CHECK(component_type IN('LABOR','PART','VENDOR_SERVICE','TRAVEL','OTHER')), classification text NOT NULL CHECK(classification IN('EXPENSE','CAPITAL_IMPROVEMENT_CANDIDATE','WARRANTY_RECOVERABLE')), amount_minor bigint NOT NULL CHECK(amount_minor>=0), currency char(3) NOT NULL, source_id uuid, created_by_user_id uuid REFERENCES users(id), created_at timestamptz NOT NULL DEFAULT now(), FOREIGN KEY(tenant_id,work_order_id) REFERENCES asset_maintenance_work_orders(tenant_id,id));
CREATE TABLE asset_maintenance_history(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, work_order_id uuid NOT NULL, from_status text, to_status text NOT NULL, actor_user_id uuid REFERENCES users(id), reason text, created_at timestamptz NOT NULL DEFAULT now(), FOREIGN KEY(tenant_id,work_order_id) REFERENCES asset_maintenance_work_orders(tenant_id,id));
CREATE TABLE asset_warranties(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, asset_id uuid NOT NULL, vendor_id uuid, provider_name text, start_date date NOT NULL, end_date date NOT NULL, coverage_json jsonb NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(tenant_id,id), FOREIGN KEY(tenant_id,asset_id) REFERENCES assets(tenant_id,id), CHECK(end_date>=start_date));
CREATE TABLE asset_warranty_claims(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, asset_id uuid NOT NULL, warranty_id uuid, status text NOT NULL DEFAULT 'DRAFT' CHECK(status IN('DRAFT','SUBMITTED','UNDER_REVIEW','APPROVED','PARTIALLY_APPROVED','REJECTED','REPAIR_SCHEDULED','REPLACEMENT_SCHEDULED','SETTLED','CLOSED','CANCELLED')), issue text NOT NULL, requested_amount_minor bigint NOT NULL DEFAULT 0, approved_amount_minor bigint NOT NULL DEFAULT 0, evidence_json jsonb NOT NULL DEFAULT '{}', requested_by_user_id uuid REFERENCES users(id), approved_by_user_id uuid REFERENCES users(id), version integer NOT NULL DEFAULT 1, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(tenant_id,id), FOREIGN KEY(tenant_id,asset_id) REFERENCES assets(tenant_id,id), FOREIGN KEY(tenant_id,warranty_id) REFERENCES asset_warranties(tenant_id,id), CHECK(approved_by_user_id IS NULL OR approved_by_user_id<>requested_by_user_id));
CREATE TABLE asset_warranty_claim_history(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, claim_id uuid NOT NULL, from_status text, to_status text NOT NULL, actor_user_id uuid REFERENCES users(id), reason text, created_at timestamptz NOT NULL DEFAULT now(), FOREIGN KEY(tenant_id,claim_id) REFERENCES asset_warranty_claims(tenant_id,id));

CREATE TABLE asset_transfers(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, asset_id uuid NOT NULL, source_branch_id uuid NOT NULL, destination_branch_id uuid NOT NULL, source_location text, destination_location text, source_custodian_user_id uuid, destination_custodian_user_id uuid, status text NOT NULL DEFAULT 'DRAFT' CHECK(status IN('DRAFT','PENDING_APPROVAL','APPROVED','DISPATCHED','IN_TRANSIT','RECEIVED','REJECTED','CANCELLED')), requested_by_user_id uuid NOT NULL REFERENCES users(id), approved_by_user_id uuid REFERENCES users(id), dispatched_by_user_id uuid REFERENCES users(id), received_by_user_id uuid REFERENCES users(id), version integer NOT NULL DEFAULT 1, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(tenant_id,id), FOREIGN KEY(tenant_id,asset_id) REFERENCES assets(tenant_id,id), FOREIGN KEY(tenant_id,source_branch_id) REFERENCES branches(tenant_id,id), FOREIGN KEY(tenant_id,destination_branch_id) REFERENCES branches(tenant_id,id), CHECK(source_branch_id<>destination_branch_id), CHECK(approved_by_user_id IS NULL OR approved_by_user_id<>requested_by_user_id));
CREATE UNIQUE INDEX asset_transfer_active_uq ON asset_transfers(tenant_id,asset_id) WHERE status IN('PENDING_APPROVAL','APPROVED','DISPATCHED','IN_TRANSIT');
CREATE TABLE asset_transfer_history(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, transfer_id uuid NOT NULL, from_status text, to_status text NOT NULL, actor_user_id uuid REFERENCES users(id), reason text, created_at timestamptz NOT NULL DEFAULT now(), FOREIGN KEY(tenant_id,transfer_id) REFERENCES asset_transfers(tenant_id,id));
CREATE TABLE asset_count_sessions(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, branch_id uuid NOT NULL, status text NOT NULL DEFAULT 'DRAFT' CHECK(status IN('DRAFT','OPEN','COUNTING','REVIEW','APPROVED','CLOSED','CANCELLED')), expected_snapshot_json jsonb NOT NULL DEFAULT '[]', opened_at timestamptz, approved_by_user_id uuid REFERENCES users(id), created_by_user_id uuid REFERENCES users(id), version integer NOT NULL DEFAULT 1, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(tenant_id,id), FOREIGN KEY(tenant_id,branch_id) REFERENCES branches(tenant_id,id));
CREATE TABLE asset_count_lines(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, session_id uuid NOT NULL, asset_id uuid, line_status text NOT NULL DEFAULT 'EXPECTED' CHECK(line_status IN('EXPECTED','FOUND','MISSING','DAMAGED','MOVED','UNREGISTERED')), found_location text, condition text, evidence_json jsonb NOT NULL DEFAULT '{}', recorded_by_user_id uuid REFERENCES users(id), recorded_at timestamptz, UNIQUE(tenant_id,id), UNIQUE(tenant_id,session_id,asset_id), FOREIGN KEY(tenant_id,session_id) REFERENCES asset_count_sessions(tenant_id,id), FOREIGN KEY(tenant_id,asset_id) REFERENCES assets(tenant_id,id));
CREATE TABLE asset_count_discrepancy_actions(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, session_id uuid NOT NULL, line_id uuid NOT NULL, action text NOT NULL, reason text NOT NULL, approved_by_user_id uuid REFERENCES users(id), created_at timestamptz NOT NULL DEFAULT now(), FOREIGN KEY(tenant_id,session_id) REFERENCES asset_count_sessions(tenant_id,id), FOREIGN KEY(tenant_id,line_id) REFERENCES asset_count_lines(tenant_id,id));
CREATE TABLE asset_inspections(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, branch_id uuid NOT NULL, asset_id uuid NOT NULL, status text NOT NULL DEFAULT 'DRAFT' CHECK(status IN('DRAFT','SCHEDULED','IN_PROGRESS','PASSED','FAILED','REQUIRES_MAINTENANCE','CANCELLED')), scheduled_at timestamptz, completed_at timestamptz, condition text, next_due_at timestamptz, assigned_user_id uuid REFERENCES users(id), created_by_user_id uuid REFERENCES users(id), version integer NOT NULL DEFAULT 1, UNIQUE(tenant_id,id), FOREIGN KEY(tenant_id,branch_id) REFERENCES branches(tenant_id,id), FOREIGN KEY(tenant_id,asset_id) REFERENCES assets(tenant_id,id));
CREATE TABLE asset_inspection_results(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, inspection_id uuid NOT NULL, checklist_json jsonb NOT NULL DEFAULT '[]', evidence_json jsonb NOT NULL DEFAULT '{}', result text, maintenance_work_order_id uuid, created_at timestamptz NOT NULL DEFAULT now(), FOREIGN KEY(tenant_id,inspection_id) REFERENCES asset_inspections(tenant_id,id));

CREATE TABLE asset_impairment_requests(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, branch_id uuid NOT NULL, asset_id uuid NOT NULL, status text NOT NULL DEFAULT 'DRAFT' CHECK(status IN('DRAFT','PENDING_REVIEW','PENDING_APPROVAL','APPROVED','POSTING','POSTED','REJECTED','REVERSED')), amount_minor bigint NOT NULL CHECK(amount_minor>0), recoverable_amount_minor bigint NOT NULL CHECK(recoverable_amount_minor>=0), minimum_carrying_minor bigint NOT NULL DEFAULT 0, evidence_json jsonb NOT NULL DEFAULT '{}', requested_by_user_id uuid NOT NULL REFERENCES users(id), approved_by_user_id uuid REFERENCES users(id), version integer NOT NULL DEFAULT 1, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(tenant_id,id), FOREIGN KEY(tenant_id,branch_id) REFERENCES branches(tenant_id,id), FOREIGN KEY(tenant_id,asset_id) REFERENCES assets(tenant_id,id), CHECK(approved_by_user_id IS NULL OR approved_by_user_id<>requested_by_user_id));
CREATE TABLE asset_impairment_approvals(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, impairment_id uuid NOT NULL, approver_user_id uuid NOT NULL REFERENCES users(id), fingerprint text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(tenant_id,impairment_id), FOREIGN KEY(tenant_id,impairment_id) REFERENCES asset_impairment_requests(tenant_id,id));
CREATE TABLE asset_impairment_history(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, impairment_id uuid NOT NULL, from_status text, to_status text NOT NULL, actor_user_id uuid REFERENCES users(id), reason text, created_at timestamptz NOT NULL DEFAULT now(), FOREIGN KEY(tenant_id,impairment_id) REFERENCES asset_impairment_requests(tenant_id,id));
CREATE TABLE asset_capital_improvements(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, branch_id uuid NOT NULL, asset_id uuid NOT NULL, work_order_id uuid, status text NOT NULL DEFAULT 'DRAFT' CHECK(status IN('DRAFT','PENDING_APPROVAL','APPROVED','CAPITALIZED','REJECTED','CANCELLED')), amount_minor bigint NOT NULL CHECK(amount_minor>0), useful_life_change integer, residual_value_change_minor bigint, source_fingerprint text NOT NULL, requested_by_user_id uuid NOT NULL REFERENCES users(id), approved_by_user_id uuid REFERENCES users(id), version integer NOT NULL DEFAULT 1, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(tenant_id,id), FOREIGN KEY(tenant_id,branch_id) REFERENCES branches(tenant_id,id), FOREIGN KEY(tenant_id,asset_id) REFERENCES assets(tenant_id,id), FOREIGN KEY(tenant_id,work_order_id) REFERENCES asset_maintenance_work_orders(tenant_id,id), CHECK(approved_by_user_id IS NULL OR approved_by_user_id<>requested_by_user_id));
CREATE TABLE asset_capital_improvement_approvals(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, improvement_id uuid NOT NULL, approver_user_id uuid NOT NULL REFERENCES users(id), fingerprint text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(tenant_id,improvement_id), FOREIGN KEY(tenant_id,improvement_id) REFERENCES asset_capital_improvements(tenant_id,id));
CREATE TABLE asset_retirement_requests(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, asset_id uuid NOT NULL, method text NOT NULL CHECK(method IN('SALE','SCRAP','DONATION','LOST','STOLEN','DESTROYED','TRANSFER_OUT_FOUNDATION')), status text NOT NULL DEFAULT 'DRAFT' CHECK(status IN('DRAFT','PENDING_APPROVAL','APPROVED','COMPLETED','CANCELLED')), requested_by_user_id uuid NOT NULL REFERENCES users(id), approved_by_user_id uuid REFERENCES users(id), reason text NOT NULL, version integer NOT NULL DEFAULT 1, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(tenant_id,id), FOREIGN KEY(tenant_id,asset_id) REFERENCES assets(tenant_id,id), CHECK(approved_by_user_id IS NULL OR approved_by_user_id<>requested_by_user_id));
CREATE TABLE asset_disposals(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, retirement_request_id uuid NOT NULL, asset_id uuid NOT NULL, status text NOT NULL DEFAULT 'DRAFT' CHECK(status IN('DRAFT','PENDING_APPROVAL','APPROVED','PROCESSING','COMPLETED','CANCELLED')), proceeds_minor bigint NOT NULL DEFAULT 0, disposal_cost_minor bigint NOT NULL DEFAULT 0, gain_loss_minor bigint, evidence_json jsonb NOT NULL DEFAULT '{}', requested_by_user_id uuid NOT NULL REFERENCES users(id), approved_by_user_id uuid REFERENCES users(id), version integer NOT NULL DEFAULT 1, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(tenant_id,id), UNIQUE(tenant_id,asset_id), FOREIGN KEY(tenant_id,retirement_request_id) REFERENCES asset_retirement_requests(tenant_id,id), FOREIGN KEY(tenant_id,asset_id) REFERENCES assets(tenant_id,id), CHECK(approved_by_user_id IS NULL OR approved_by_user_id<>requested_by_user_id));
CREATE TABLE asset_disposal_approvals(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, disposal_id uuid NOT NULL, approver_user_id uuid NOT NULL REFERENCES users(id), fingerprint text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(tenant_id,disposal_id), FOREIGN KEY(tenant_id,disposal_id) REFERENCES asset_disposals(tenant_id,id));
CREATE TABLE asset_disposal_history(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, disposal_id uuid NOT NULL, from_status text, to_status text NOT NULL, actor_user_id uuid REFERENCES users(id), reason text, created_at timestamptz NOT NULL DEFAULT now(), FOREIGN KEY(tenant_id,disposal_id) REFERENCES asset_disposals(tenant_id,id));

CREATE TABLE asset_opening_imports(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, status text NOT NULL DEFAULT 'UPLOADED' CHECK(status IN('UPLOADED','VALIDATED','PENDING_APPROVAL','APPROVED','PROCESSING','PROCESSED','REJECTED','FAILED')), cutover_date date NOT NULL, checksum text NOT NULL, row_count integer NOT NULL DEFAULT 0, error_count integer NOT NULL DEFAULT 0, requested_by_user_id uuid NOT NULL REFERENCES users(id), approved_by_user_id uuid REFERENCES users(id), version integer NOT NULL DEFAULT 1, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(tenant_id,id), UNIQUE(tenant_id,checksum), CHECK(approved_by_user_id IS NULL OR approved_by_user_id<>requested_by_user_id));
CREATE TABLE asset_opening_import_rows(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, import_id uuid NOT NULL, row_no integer NOT NULL, asset_code text NOT NULL, branch_id uuid NOT NULL, category_id uuid NOT NULL, name text NOT NULL, currency char(3) NOT NULL, gross_amount_minor bigint NOT NULL, accumulated_depreciation_minor bigint NOT NULL DEFAULT 0, residual_value_minor bigint NOT NULL DEFAULT 0, useful_life_periods integer NOT NULL, in_service_date date, validated boolean NOT NULL DEFAULT false, created_asset_id uuid, UNIQUE(tenant_id,import_id,row_no), FOREIGN KEY(tenant_id,import_id) REFERENCES asset_opening_imports(tenant_id,id), FOREIGN KEY(tenant_id,branch_id) REFERENCES branches(tenant_id,id), FOREIGN KEY(tenant_id,category_id) REFERENCES asset_categories(tenant_id,id), FOREIGN KEY(tenant_id,created_asset_id) REFERENCES assets(tenant_id,id), CHECK(gross_amount_minor>=accumulated_depreciation_minor), CHECK(accumulated_depreciation_minor<=gross_amount_minor-residual_value_minor));
CREATE TABLE asset_import_errors(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, import_id uuid NOT NULL, row_no integer, code text NOT NULL, message text NOT NULL, details_json jsonb NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL DEFAULT now(), FOREIGN KEY(tenant_id,import_id) REFERENCES asset_opening_imports(tenant_id,id));
CREATE TABLE asset_reconciliation_snapshots(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, branch_id uuid, snapshot_date date NOT NULL, gross_minor bigint NOT NULL, accumulated_depreciation_minor bigint NOT NULL, nbv_minor bigint NOT NULL, procurement_difference_minor bigint NOT NULL DEFAULT 0, gl_difference_minor bigint NOT NULL DEFAULT 0, status text NOT NULL DEFAULT 'OPEN', created_at timestamptz NOT NULL DEFAULT now(), FOREIGN KEY(tenant_id,branch_id) REFERENCES branches(tenant_id,id));
CREATE TABLE asset_export_jobs(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, status text NOT NULL DEFAULT 'PENDING' CHECK(status IN('PENDING','PROCESSING','COMPLETED','FAILED')), filter_json jsonb NOT NULL DEFAULT '{}', storage_key text, checksum text, requested_by_user_id uuid REFERENCES users(id), created_at timestamptz NOT NULL DEFAULT now(), completed_at timestamptz, FOREIGN KEY(tenant_id) REFERENCES tenants(id));

CREATE INDEX asset_branch_status_idx ON assets(tenant_id,branch_id,status);
CREATE INDEX asset_candidate_branch_status_idx ON asset_candidates(tenant_id,branch_id,status);
CREATE INDEX asset_depreciation_schedule_period_idx ON asset_depreciation_schedules(tenant_id,period_start,period_end);
CREATE INDEX asset_maintenance_due_idx ON asset_maintenance_work_orders(tenant_id,branch_id,status,scheduled_start_at);
CREATE INDEX asset_warranty_expiry_idx ON asset_warranties(tenant_id,end_date);

CREATE OR REPLACE FUNCTION asset_append_only_guard() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'ASSET_HISTORY_IMMUTABLE' USING ERRCODE='55000'; END $$;
CREATE TRIGGER asset_status_history_append_only BEFORE UPDATE OR DELETE ON asset_status_history FOR EACH ROW EXECUTE FUNCTION asset_append_only_guard();
CREATE TRIGGER asset_transfer_history_append_only BEFORE UPDATE OR DELETE ON asset_transfer_history FOR EACH ROW EXECUTE FUNCTION asset_append_only_guard();
CREATE TRIGGER asset_maintenance_history_append_only BEFORE UPDATE OR DELETE ON asset_maintenance_history FOR EACH ROW EXECUTE FUNCTION asset_append_only_guard();
CREATE OR REPLACE FUNCTION asset_posted_economics_guard() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN
  IF OLD.status IN('ACTIVE','IN_MAINTENANCE','IN_TRANSIT','IDLE','IMPAIRED','RETIRED','DISPOSED','LOST','STOLEN','DESTROYED') AND (NEW.gross_carrying_amount_minor IS DISTINCT FROM OLD.gross_carrying_amount_minor OR NEW.residual_value_minor IS DISTINCT FROM OLD.residual_value_minor OR NEW.accumulated_depreciation_minor < OLD.accumulated_depreciation_minor OR NEW.accumulated_impairment_minor < OLD.accumulated_impairment_minor) THEN RAISE EXCEPTION 'ASSET_IMMUTABLE' USING ERRCODE='55000'; END IF; RETURN NEW; END $$;
CREATE TRIGGER asset_posted_economics_guard BEFORE UPDATE ON assets FOR EACH ROW EXECUTE FUNCTION asset_posted_economics_guard();
CREATE OR REPLACE FUNCTION asset_count_snapshot_guard() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF OLD.status IN('OPEN','COUNTING','REVIEW','APPROVED','CLOSED') AND NEW.expected_snapshot_json IS DISTINCT FROM OLD.expected_snapshot_json THEN RAISE EXCEPTION 'ASSET_COUNT_SNAPSHOT_IMMUTABLE' USING ERRCODE='55000'; END IF; RETURN NEW; END $$;
CREATE TRIGGER asset_count_snapshot_guard BEFORE UPDATE ON asset_count_sessions FOR EACH ROW EXECUTE FUNCTION asset_count_snapshot_guard();

INSERT INTO permissions(code,description) SELECT code,'Sprint 16 fixed asset and maintenance permission' FROM unnest(ARRAY[
 'asset.category.read','asset.category.manage','asset.policy.read','asset.policy.manage','asset.configuration.manage','asset.candidate.read','asset.candidate.create','asset.candidate.classify','asset.candidate.approve','asset.register.read','asset.register.create','asset.register.manage','asset.document.manage','asset.capitalization.read','asset.capitalization.create','asset.capitalization.approve','asset.capitalization.process','asset.depreciation.read','asset.depreciation.create','asset.depreciation.approve','asset.depreciation.post','asset.depreciation.reverse','asset.maintenance.read','asset.maintenance.create','asset.maintenance.assign','asset.maintenance.execute','asset.maintenance.verify','asset.maintenance.cancel','asset.warranty.read','asset.warranty.manage','asset.warranty_claim.manage','asset.transfer.read','asset.transfer.create','asset.transfer.approve','asset.transfer.dispatch','asset.transfer.receive','asset.count.read','asset.count.create','asset.count.record','asset.count.approve','asset.inspection.read','asset.inspection.create','asset.inspection.execute','asset.inspection.approve','asset.impairment.read','asset.impairment.create','asset.impairment.approve','asset.impairment.post','asset.improvement.read','asset.improvement.create','asset.improvement.approve','asset.improvement.capitalize','asset.disposal.read','asset.disposal.create','asset.disposal.approve','asset.disposal.complete','asset.report.read','asset.export'
 ]) code ON CONFLICT DO NOTHING;
INSERT INTO role_permissions(role,permission_code) SELECT r.role,p.code FROM (VALUES ('SALON_OWNER'),('ACCOUNTANT'),('BRANCH_MANAGER'),('INVENTORY_MANAGER'),('NAIL_TECHNICIAN')) r(role) CROSS JOIN (SELECT code FROM permissions WHERE code LIKE 'asset.%') p ON CONFLICT DO NOTHING;
INSERT INTO schema_migrations(version) VALUES('0033_fixed_assets_maintenance_depreciation');
COMMIT;
