BEGIN;
DROP TRIGGER IF EXISTS marketing_revenue_adjustment_append_only ON marketing_attribution_revenue_adjustments;
DROP TRIGGER IF EXISTS marketing_financial_evidence_append_only ON marketing_attributed_financial_evidence;
DROP TRIGGER IF EXISTS marketing_booking_attribution_append_only ON marketing_booking_attributions;
DROP TRIGGER IF EXISTS marketing_revenue_adjustment_consistency ON marketing_attribution_revenue_adjustments;
DROP TRIGGER IF EXISTS marketing_financial_evidence_consistency ON marketing_attributed_financial_evidence;
DROP TRIGGER IF EXISTS marketing_booking_attribution_consistency ON marketing_booking_attributions;
DROP TRIGGER IF EXISTS marketing_attribution_context_consistency ON marketing_attribution_contexts;
DROP FUNCTION IF EXISTS marketing_attribution_append_only();
DROP FUNCTION IF EXISTS marketing_revenue_adjustment_consistency();
DROP FUNCTION IF EXISTS marketing_financial_evidence_consistency();
DROP FUNCTION IF EXISTS marketing_booking_attribution_consistency();
DROP FUNCTION IF EXISTS marketing_attribution_context_consistency();
DROP TABLE IF EXISTS marketing_attribution_revenue_adjustments;
DROP TABLE IF EXISTS marketing_attributed_financial_evidence;
DROP TABLE IF EXISTS marketing_booking_attributions;
DROP TABLE IF EXISTS marketing_attribution_contexts;
ALTER TABLE marketing_campaign_audience DROP CONSTRAINT IF EXISTS marketing_campaign_audience_tenant_id_id_key;
DELETE FROM role_permissions WHERE permission_code IN ('marketing.attribution.read','marketing.attribution.issue');
DELETE FROM permissions WHERE code IN ('marketing.attribution.read','marketing.attribution.issue');
DELETE FROM schema_migrations WHERE version='0041_marketing_attribution';
COMMIT;
