/* eslint-disable @typescript-eslint/no-explicit-any */
"use client";
import { useEffect, useState } from "react";
import { ActionButton, Field, Page, StatePanel, Table, api, useMutation, useResource, wave4Text } from "./shared";
import { getActiveBranchId } from "../auth";

export default function SchedulingWorkspace({ pathname }: { pathname: string }) {
  const shiftDetail = pathname.match(/^\/admin\/scheduling\/shifts\/([^/]+)$/)?.[1];
  const leaveDetail = pathname.match(/^\/admin\/scheduling\/leave-requests\/([^/]+)$/)?.[1];
  if (shiftDetail) return <ShiftDetail id={shiftDetail} />;
  if (leaveDetail) return <LeaveDetail id={leaveDetail} />;
  if (pathname.startsWith("/admin/scheduling/leave-requests")) return <LeaveReview />;
  return <ShiftPlanner />;
}
function ShiftPlanner() {
  const branch = getActiveBranchId(); const resource = useResource(`/v1/shifts${branch ? `?branchId=${encodeURIComponent(branch)}` : ""}`); const [showForm, setShowForm] = useState(false);
  return <Page eyebrow="Scheduling" title="Shift planner" description="Lập ca theo chi nhánh, chỉ công bố sau khi kiểm tra và luôn hiển thị lỗi trùng lịch." actions={<button className="s19-button s19-button-primary" onClick={() => setShowForm((value) => !value)}>{showForm ? wave4Text("Close form") : wave4Text("Create shift")}</button>}><div className="s19-card">{showForm && <ShiftForm onCreated={() => { setShowForm(false); void resource.reload(); }} />}<StatePanel state={resource.state} error={resource.error} retry={resource.reload} empty="No shifts are scheduled for the current branch." />{resource.state === "ready" && <Table rows={resource.rows.map((row) => ({ ...row, staffId: row.staffId ? "Đã phân công" : null, branchId: row.branchId ? "Đã gán chi nhánh" : null }))} columns={[["startAt", "Starts"], ["endAt", "Ends"], ["staffId", "Staff"], ["branchId", "Branch"], ["status", "Status"], ["version", "Version"]]} />}</div></Page>;
}
function ShiftForm({ onCreated }: { onCreated: () => void }) {
  const [values, setValues] = useState({ branchId: "", staffId: "", startAt: "", endAt: "", breakMinutes: "0" }); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const [references, setReferences] = useState<{ branches: any[]; staff: any[] }>({ branches: [], staff: [] }); const [loadingReferences, setLoadingReferences] = useState(true); const set = (key: string) => (value: string) => setValues((v) => ({ ...v, [key]: value }));
  useEffect(() => { let active = true; void Promise.all([api("/v1/branches"), api("/v1/staff")]).then(([branches, staff]) => { if (!active) return; const list = (value: any) => Array.isArray(value) ? value : value?.items ?? []; setReferences({ branches: list(branches), staff: list(staff) }); }).catch(() => { if (active) setReferences({ branches: [], staff: [] }); }).finally(() => { if (active) setLoadingReferences(false); }); return () => { active = false; }; }, []);
  async function submit(event: React.FormEvent) { event.preventDefault(); setBusy(true); setError(""); try { await (await import("./shared")).command("/v1/shifts", { branchId: values.branchId, staffId: values.staffId, startAt: new Date(values.startAt).toISOString(), endAt: new Date(values.endAt).toISOString(), breakMinutes: Number(values.breakMinutes), source: "MANUAL", recurrenceRuleId: null }); onCreated(); } catch (cause: any) { setError(cause?.message ?? "Không thể tạo ca làm."); } finally { setBusy(false); } }
  const display = (row: any) => String(row.displayName ?? row.name ?? row.code ?? row.employeeCode ?? "Bản ghi");
  return <form className="s19-form-grid s19-w4-subform" onSubmit={submit}>{loadingReferences ? <p className="s19-field-wide">Đang tải danh sách chi nhánh và nhân sự…</p> : <><label className="s19-field"><span>Chi nhánh *</span><select required value={values.branchId} onChange={(event) => set("branchId")(event.target.value)}><option value="">Chọn chi nhánh…</option>{references.branches.map((row) => <option key={row.id} value={row.id}>{display(row)}</option>)}</select></label><label className="s19-field"><span>Nhân sự *</span><select required value={values.staffId} onChange={(event) => set("staffId")(event.target.value)}><option value="">Chọn nhân sự…</option>{references.staff.map((row) => <option key={row.id} value={row.id}>{display(row)}</option>)}</select></label></>}<Field name="startAt" label="Start" type="datetime-local" required value={values.startAt} onChange={set("startAt")} /><Field name="endAt" label="End" type="datetime-local" required value={values.endAt} onChange={set("endAt")} /><Field name="breakMinutes" label="Break minutes" type="number" value={values.breakMinutes} onChange={set("breakMinutes")} /><button className="s19-button s19-button-primary" disabled={busy || loadingReferences}>{busy ? "Đang lưu…" : wave4Text("Save shift")}</button>{error && <p className="s19-notice s19-notice-danger s19-field-wide">{error}</p>}</form>;
}
function LeaveReview() {
  const branch = getActiveBranchId(); const resource = useResource(`/v1/leave-requests${branch ? `?branchId=${encodeURIComponent(branch)}` : ""}`); const mutation = useMutation(resource.reload);
  return <Page eyebrow="Scheduling" title="Leave review" description="Rà soát đơn nghỉ theo chi nhánh với chuyển trạng thái, lý do và kiểm soát phiên bản."><section className="s19-card"><StatePanel state={resource.state} error={resource.error} retry={resource.reload} empty="No leave requests are waiting for review." />{resource.state === "ready" && <Table rows={resource.rows.map((row) => ({ ...row, staffId: row.staffId ? "Đã xác định nhân sự" : null }))} columns={[["staffId", "Staff"], ["leaveType", "Type"], ["startAt", "From"], ["endAt", "To"], ["status", "Status"], ["version", "Version"]]} />}{resource.state === "ready" && <div className="s19-inline-actions">{resource.rows.filter((row) => ["PENDING", "SUBMITTED"].includes(String(row.status ?? "").toUpperCase())).slice(0, 3).map((row) => <span key={row.id} className="s19-w4-action-set"><ActionButton label="Approve" onClick={() => mutation.run(`/v1/leave-requests/${row.id}/approve`, { version: row.version, reviewNote: "Reviewed in workforce workspace" })} /><ActionButton label="Reject" danger onClick={() => mutation.run(`/v1/leave-requests/${row.id}/reject`, { version: row.version, reviewNote: "Needs follow-up" })} /></span>)}</div>}{mutation.notice && <p className="s19-notice s19-notice-success">{mutation.notice}</p>}{mutation.error && <p className="s19-notice s19-notice-danger">{mutation.error}</p>}</section></Page>;
}

function ShiftDetail({ id }: { id: string }) {
  const resource = useResource(`/v1/shifts/${id}`);
  const mutation = useMutation(resource.reload);
  if (resource.state !== "ready") return <Page eyebrow="Scheduling" title="Chi tiết ca làm" description="Ca làm được đọc theo phạm vi chi nhánh và dữ liệu máy chủ."><StatePanel state={resource.state} error={resource.error} retry={resource.reload} /></Page>;
  const row = resource.rows[0] ?? {};
  const status = String(row.status ?? "").toUpperCase();
  return <Page eyebrow="Scheduling" title="Chi tiết ca làm" description="Kiểm tra thời gian, phân công và trạng thái công bố của ca làm." actions={<a className="s19-button s19-button-secondary" href="/admin/scheduling/shifts">Quay lại lịch ca</a>}><div className="s19-w4-grid"><section className="s19-card"><h2>Thông tin ca</h2><dl className="s19-w4-dl">{[["Bắt đầu", row.startAt], ["Kết thúc", row.endAt], ["Nghỉ giữa ca", row.breakMinutes != null ? `${row.breakMinutes} phút` : null], ["Nhân sự", row.staffId ? "Đã phân công" : null], ["Chi nhánh", row.branchId ? "Đã gán chi nhánh" : null], ["Trạng thái", row.status], ["Phiên bản", row.version]].map(([label, value]) => <div key={label as string}><dt>{label}</dt><dd>{value == null || value === "" ? "—" : ["Bắt đầu", "Kết thúc"].includes(label as string) ? new Intl.DateTimeFormat("vi-VN", { dateStyle: "medium", timeStyle: "short" }).format(new Date(String(value))) : wave4Text(String(value))}</dd></div>)}</dl><div className="s19-inline-actions">{status === "DRAFT" ? <ActionButton label="Publish" onClick={() => mutation.run(`/v1/shifts/${id}/publish`, {})} /> : null}{status === "PUBLISHED" ? <ActionButton label="Cancel" danger onClick={() => mutation.run(`/v1/shifts/${id}/cancel`, {})} /> : null}{mutation.notice && <span className="s19-notice-success">{mutation.notice}</span>}{mutation.error && <span className="s19-notice-danger">{mutation.error}</span>}</div></section><section className="s19-card"><h2>Kiểm soát lịch</h2><p className="s19-notice">Chỉ ca ở trạng thái Bản nháp mới có thể công bố. Máy chủ kiểm tra trùng lịch trước khi chuyển sang Đã công bố.</p><a className="s19-button s19-button-secondary" href="/admin/calendar">Mở lịch vận hành</a></section></div></Page>;
}

function LeaveDetail({ id }: { id: string }) {
  const resource = useResource(`/v1/leave-requests/${id}`);
  const mutation = useMutation(resource.reload);
  if (resource.state !== "ready") return <Page eyebrow="Scheduling" title="Chi tiết đơn nghỉ" description="Đơn nghỉ được đọc theo phạm vi chi nhánh và dữ liệu máy chủ."><StatePanel state={resource.state} error={resource.error} retry={resource.reload} /></Page>;
  const row = resource.rows[0] ?? {};
  const status = String(row.status ?? "").toUpperCase();
  return <Page eyebrow="Scheduling" title="Chi tiết đơn nghỉ" description="Kiểm tra thời gian nghỉ, nhân sự và trạng thái phê duyệt." actions={<a className="s19-button s19-button-secondary" href="/admin/scheduling/leave-requests">Quay lại duyệt đơn</a>}><div className="s19-w4-grid"><section className="s19-card"><h2>Thông tin đơn nghỉ</h2><dl className="s19-w4-dl">{[["Loại nghỉ", row.leaveType], ["Bắt đầu", row.startAt], ["Kết thúc", row.endAt], ["Nhân sự", row.staffId ? "Đã xác định nhân sự" : null], ["Chi nhánh", row.branchId ? "Đã gán chi nhánh" : null], ["Trạng thái", row.status], ["Phiên bản", row.version]].map(([label, value]) => <div key={label as string}><dt>{label}</dt><dd>{value == null || value === "" ? "—" : ["Bắt đầu", "Kết thúc"].includes(label as string) ? new Intl.DateTimeFormat("vi-VN", { dateStyle: "medium", timeStyle: "short" }).format(new Date(String(value))) : wave4Text(String(value))}</dd></div>)}</dl><div className="s19-inline-actions">{status === "PENDING" ? <><ActionButton label="Approve" onClick={() => mutation.run(`/v1/leave-requests/${id}/approve`, { version: row.version, reviewNote: "Reviewed in workforce workspace" })} /><ActionButton label="Reject" danger onClick={() => mutation.run(`/v1/leave-requests/${id}/reject`, { version: row.version, reviewNote: "Needs follow-up" })} /></> : null}{mutation.notice && <span className="s19-notice-success">{mutation.notice}</span>}{mutation.error && <span className="s19-notice-danger">{mutation.error}</span>}</div></section><section className="s19-card"><h2>Kiểm soát phê duyệt</h2><p className="s19-notice">Lịch sử phê duyệt được máy chủ ghi nhận theo phiên bản và người thực hiện. Không có chỉnh sửa trực tiếp trong trình duyệt.</p><a className="s19-button s19-button-secondary" href="/admin/time-clock">Mở chấm công</a></section></div></Page>;
}
