/* eslint-disable @typescript-eslint/no-explicit-any */
"use client";
import { useState } from "react";
import { api, ActionButton, Field, Page, StatePanel, Table, useMutation, useResource } from "./shared";

export default function StaffWorkspace({ pathname }: { pathname: string }) {
  const id = pathname.match(/^\/admin\/staff\/([^/]+)$/)?.[1];
  if (pathname === "/admin/staff/new") return <StaffForm />;
  if (id && id !== "list") return <StaffDetail id={id} />;
  return <StaffDirectory />;
}
function StaffDirectory() {
  const resource = useResource("/v1/staff");
  const [q, setQ] = useState("");
  const rows = resource.rows.filter((row) => !q || `${row.displayName} ${row.employeeCode}`.toLowerCase().includes(q.toLowerCase()));
  return <Page eyebrow="People" title="Staff directory" description="Find staff by operational profile, employment status and branch assignment." actions={<a className="s19-button s19-button-primary" href="/admin/staff/new">Add staff</a>}><section className="s19-card"><div className="s19-w4-toolbar"><label className="s19-field"><span>Search staff</span><input value={q} onChange={(e) => setQ(e.target.value)} placeholder="Name or employee code" /></label><button className="s19-button s19-button-secondary" onClick={resource.reload}>Refresh</button></div><StatePanel state={resource.state} error={resource.error} retry={resource.reload} empty="No staff profiles match this workspace." />{resource.state === "ready" && <Table rows={rows} columns={[["displayName", "Name"], ["employeeCode", "Employee code"], ["employmentType", "Employment"], ["status", "Status"], ["preferredLocale", "Locale"], ["version", "Version"]]} onSelect={(row) => { window.location.href = `/admin/staff/${row.id}`; }} />}</section></Page>;
}
function StaffForm() {
  const [values, setValues] = useState({ membershipId: "", employeeCode: "", displayName: "", legalName: "", preferredName: "", levelCode: "", employmentType: "FULL_TIME", preferredLocale: "vi-VN", hireDate: "", notes: "" });
  const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  const set = (key: string) => (value: string) => setValues((current) => ({ ...current, [key]: value }));
  async function submit(event: React.FormEvent) { event.preventDefault(); setBusy(true); setError(""); setNotice(""); try { await api("/v1/staff", { method: "POST", headers: { "content-type": "application/json", "idempotency-key": crypto.randomUUID() }, body: JSON.stringify({ ...values, membershipId: values.membershipId || null, hireDate: values.hireDate || null, notes: values.notes || null }) }); setNotice("Staff profile created"); } catch (cause: any) { setError(cause?.message ?? "Unable to create staff"); } finally { setBusy(false); } }
  return <Page eyebrow="People" title="Create staff profile" description="Add an operational profile without exposing payroll or private identity data."><form className="s19-card s19-form-grid" onSubmit={submit}>{[["employeeCode", "Employee code", "text", true], ["displayName", "Display name", "text", true], ["legalName", "Legal name", "text", false], ["preferredName", "Preferred name", "text", false], ["membershipId", "Membership ID", "text", false], ["levelCode", "Level code", "text", false], ["hireDate", "Hire date", "date", false], ["notes", "Notes", "text", false]].map(([key, label, type, required]) => <Field key={key as string} name={key as string} label={label as string} type={type as string} required={required as boolean} value={values[key as keyof typeof values]} onChange={set(key as string)} />)}<label className="s19-field"><span>Employment type</span><select value={values.employmentType} onChange={(e) => set("employmentType")(e.target.value)}><option>FULL_TIME</option><option>PART_TIME</option><option>CONTRACTOR</option><option>TEMPORARY</option></select></label><label className="s19-field"><span>Preferred locale</span><select value={values.preferredLocale} onChange={(e) => set("preferredLocale")(e.target.value)}><option>vi-VN</option><option>en-US</option></select></label><div className="s19-inline-actions s19-field-wide"><button className="s19-button s19-button-primary" disabled={busy}>{busy ? "Creating…" : "Create profile"}</button><a className="s19-button s19-button-secondary" href="/admin/staff/list">Cancel</a></div>{error && <p className="s19-notice s19-notice-danger s19-field-wide">{error}</p>}{notice && <p className="s19-notice s19-notice-success s19-field-wide">{notice}</p>}</form></Page>;
}
function StaffDetail({ id }: { id: string }) {
  const profile = useResource(`/v1/staff/${id}`); const branches = useResource(`/v1/staff/${id}/branches`); const skills = useResource(`/v1/staff/${id}/skills`); const mutation = useMutation(profile.reload);
  if (profile.state !== "ready") return <Page eyebrow="People" title="Staff profile" description="Assignments and skills are scoped to the current tenant and branch."><StatePanel state={profile.state} error={profile.error} retry={profile.reload} /></Page>;
  const row = profile.rows[0] ?? {};
  return <Page eyebrow="People" title={row.displayName ?? "Staff profile"} description="Operational profile, branch assignments and service skills." actions={<a className="s19-button s19-button-secondary" href="/admin/staff/list">Back to directory</a>}><div className="s19-w4-grid"><section className="s19-card"><h2>Profile</h2><dl className="s19-w4-dl">{[["Employee code", row.employeeCode], ["Employment", row.employmentType], ["Status", row.status], ["Locale", row.preferredLocale], ["Version", row.version]].map(([label, value]) => <div key={label as string}><dt>{label}</dt><dd>{String(value ?? "—")}</dd></div>)}</dl><div className="s19-inline-actions"><ActionButton label="Suspend" onClick={() => mutation.run(`/v1/staff/${id}/suspend`, {})} danger /><ActionButton label="Activate" onClick={() => mutation.run(`/v1/staff/${id}/activate`, {})} />{mutation.notice && <span className="s19-notice-success">{mutation.notice}</span>}{mutation.error && <span className="s19-notice-danger">{mutation.error}</span>}</div></section><section className="s19-card"><h2>Branch assignments</h2><StatePanel state={branches.state} error={branches.error} retry={branches.reload} empty="No branch assignments." />{branches.state === "ready" && <Table rows={branches.rows} columns={[["branchId", "Branch"], ["isPrimary", "Primary"], ["canBeBooked", "Bookable"], ["status", "Status"]]} />}</section><section className="s19-card"><h2>Skills</h2><StatePanel state={skills.state} error={skills.error} retry={skills.reload} empty="No skills assigned." />{skills.state === "ready" && <Table rows={skills.rows} columns={[["skillId", "Skill"], ["level", "Level"], ["status", "Status"]]} />}</section></div></Page>;
}
