/* eslint-disable @typescript-eslint/no-explicit-any */
import { Body, Controller, Get, Headers, Param, Post, Req, UseGuards } from "@nestjs/common";
import { ApiBearerAuth, ApiTags } from "@nestjs/swagger";
import type { AuthenticatedRequest } from "../identity/auth.types.js";
import { AuthGuard } from "../identity/auth.guard.js";
import { PermissionGuard } from "../identity/permission.guard.js";
import { RequirePermission } from "../identity/permission.decorator.js";
import { ProcurementService } from "./procurement.service.js";
const rid=(r:AuthenticatedRequest)=>r.raw.requestId??"unknown", key=(k?:string)=>k??"", ok=(data:unknown,r:AuthenticatedRequest)=>({success:true,data,meta:{requestId:rid(r),timestamp:new Date().toISOString()}});
@ApiBearerAuth() @UseGuards(AuthGuard,PermissionGuard) @ApiTags("procurement") @Controller("procurement")
export class ProcurementController {
  constructor(private readonly s:ProcurementService){}
  @Get("vendors") @RequirePermission("procurement.vendor.read") vendors(@Req() r:AuthenticatedRequest){return this.s.listVendors(r.auth).then(x=>ok(x,r));}
  @Post("vendors") @RequirePermission("procurement.vendor.manage") createVendor(@Body() b:any,@Headers("idempotency-key") k:string,@Req() r:AuthenticatedRequest){return this.s.createVendor(r.auth,b,key(k),rid(r)).then(x=>ok(x,r));}
  @Get("vendors/:id") @RequirePermission("procurement.vendor.read") vendor(@Param("id") id:string,@Req() r:AuthenticatedRequest){return this.s.getVendor(r.auth,id).then(x=>ok(x,r));}
  @Post("vendors/:id/:action") @RequirePermission("procurement.vendor.manage") vendorAction(@Param("id") id:string,@Param("action") action:string,@Body() b:any,@Headers("idempotency-key") k:string,@Req() r:AuthenticatedRequest){const to:any={activate:"ACTIVE",hold:"ON_HOLD",release_hold:"ACTIVE",deactivate:"INACTIVE"}[action];return this.s.vendorStatus(r.auth,id,to,b,key(k),rid(r)).then(x=>ok(x,r));}
  @Get("purchase-requests") @RequirePermission("procurement.request.read") requests(@Req() r:AuthenticatedRequest){return this.s.listRequests(r.auth).then(x=>ok(x,r));}
  @Post("purchase-requests") @RequirePermission("procurement.request.create") createRequest(@Body() b:any,@Headers("idempotency-key") k:string,@Req() r:AuthenticatedRequest){return this.s.createRequest(r.auth,b,key(k),rid(r)).then(x=>ok(x,r));}
  @Get("purchase-requests/:id") @RequirePermission("procurement.request.read") request(@Param("id") id:string,@Req() r:AuthenticatedRequest){return this.s.getRequest(r.auth,id).then(x=>ok(x,r));}
  @Post("purchase-requests/:id/submit") @RequirePermission("procurement.request.submit") submitRequest(@Param("id") id:string,@Body() b:any,@Headers("idempotency-key") k:string,@Req() r:AuthenticatedRequest){return this.s.requestStatus(r.auth,id,"SUBMITTED",b,key(k),rid(r)).then(x=>ok(x,r));}
  @Post("purchase-requests/:id/approve") @RequirePermission("procurement.request.approve") approveRequest(@Param("id") id:string,@Body() b:any,@Headers("idempotency-key") k:string,@Req() r:AuthenticatedRequest){return this.s.requestStatus(r.auth,id,"APPROVED",b,key(k),rid(r)).then(x=>ok(x,r));}
  @Post("purchase-requests/:id/convert-to-po") @RequirePermission("procurement.po.create") convertRequest(@Param("id") id:string,@Body() b:any,@Headers("idempotency-key") k:string,@Req() r:AuthenticatedRequest){return this.s.convertRequest(r.auth,id,b,key(k),rid(r)).then(x=>ok(x,r));}
  @Post("purchase-requests/:id/:action") @RequirePermission("procurement.request.approve") requestAction(@Param("id") id:string,@Param("action") action:string,@Body() b:any,@Headers("idempotency-key") k:string,@Req() r:AuthenticatedRequest){if(action==="convert-to-po")return this.s.convertRequest(r.auth,id,b,key(k),rid(r)).then(x=>ok(x,r));const to:any={submit:"SUBMITTED",approve:"APPROVED",partially_approve:"PARTIALLY_APPROVED",reject:"REJECTED",cancel:"CANCELLED",close:"CLOSED"}[action];return this.s.requestStatus(r.auth,id,to,b,key(k),rid(r)).then(x=>ok(x,r));}
  @Get("purchase-orders") @RequirePermission("procurement.po.read") pos(@Req() r:AuthenticatedRequest){return this.s.listPos(r.auth).then(x=>ok(x,r));}
  @Post("purchase-orders") @RequirePermission("procurement.po.create") createPo(@Body() b:any,@Headers("idempotency-key") k:string,@Req() r:AuthenticatedRequest){return this.s.createPo(r.auth,b,key(k),rid(r)).then(x=>ok(x,r));}
  @Get("purchase-orders/:id") @RequirePermission("procurement.po.read") po(@Param("id") id:string,@Req() r:AuthenticatedRequest){return this.s.getPo(r.auth,id).then(x=>ok(x,r));}
  @Post("purchase-orders/:id/submit") @RequirePermission("procurement.po.submit") submitPo(@Param("id") id:string,@Body() b:any,@Headers("idempotency-key") k:string,@Req() r:AuthenticatedRequest){return this.s.poStatus(r.auth,id,"PENDING_APPROVAL",b,key(k),rid(r)).then(x=>ok(x,r));}
  @Post("purchase-orders/:id/approve") @RequirePermission("procurement.po.approve") approvePo(@Param("id") id:string,@Body() b:any,@Headers("idempotency-key") k:string,@Req() r:AuthenticatedRequest){return this.s.poStatus(r.auth,id,"APPROVED",b,key(k),rid(r)).then(x=>ok(x,r));}
  @Post("purchase-orders/:id/amend") @RequirePermission("procurement.po.amend") amendPo(@Param("id") id:string,@Body() b:any,@Headers("idempotency-key") k:string,@Req() r:AuthenticatedRequest){return this.s.amendPo(r.auth,id,b,key(k),rid(r)).then(x=>ok(x,r));}
  @Post("purchase-orders/:id/:action") @RequirePermission("procurement.po.approve") poAction(@Param("id") id:string,@Param("action") action:string,@Body() b:any,@Headers("idempotency-key") k:string,@Req() r:AuthenticatedRequest){if(action==="amend")return this.s.amendPo(r.auth,id,b,key(k),rid(r)).then(x=>ok(x,r));const to:any={submit:"PENDING_APPROVAL",approve:"APPROVED",send:"SENT",acknowledge:"ACKNOWLEDGED",cancel:"CANCELLED",close:"CLOSED"}[action];return this.s.poStatus(r.auth,id,to,b,key(k),rid(r)).then(x=>ok(x,r));}
  @Get("receipts") @RequirePermission("procurement.receipt.read") receipts(@Req() r:AuthenticatedRequest){return this.s.listReceipts(r.auth).then(x=>ok(x,r));}
  @Post("receipts") @RequirePermission("procurement.receipt.create") receipt(@Body() b:any,@Headers("idempotency-key") k:string,@Req() r:AuthenticatedRequest){return this.s.createReceipt(r.auth,b,key(k),rid(r)).then(x=>ok(x,r));}
  @Post("receipts/:id/accept") @RequirePermission("procurement.receipt.accept") acceptReceipt(@Param("id") id:string,@Body() b:any,@Headers("idempotency-key") k:string,@Req() r:AuthenticatedRequest){return this.s.receiptStatus(r.auth,id,"ACCEPTED",b,key(k),rid(r)).then(x=>ok(x,r));}
  @Post("receipts/:id/reverse") @RequirePermission("procurement.receipt.reverse") reverseReceipt(@Param("id") id:string,@Body() b:any,@Headers("idempotency-key") k:string,@Req() r:AuthenticatedRequest){return this.s.receiptStatus(r.auth,id,"REVERSED",b,key(k),rid(r)).then(x=>ok(x,r));}
  @Post("receipts/:id/:action") @RequirePermission("procurement.receipt.accept") receiptAction(@Param("id") id:string,@Param("action") action:string,@Body() b:any,@Headers("idempotency-key") k:string,@Req() r:AuthenticatedRequest){const to:any={receive:"RECEIVED",accept:"ACCEPTED",reject:"REJECTED",reverse:"REVERSED"}[action];return this.s.receiptStatus(r.auth,id,to,b,key(k),rid(r)).then(x=>ok(x,r));}
  @Get("vendor-bills") @RequirePermission("procurement.bill.read") bills(@Req() r:AuthenticatedRequest){return this.s.listBills(r.auth).then(x=>ok(x,r));}
  @Post("vendor-bills") @RequirePermission("procurement.bill.create") createBill(@Body() b:any,@Headers("idempotency-key") k:string,@Req() r:AuthenticatedRequest){return this.s.createBill(r.auth,b,key(k),rid(r)).then(x=>ok(x,r));}
  @Get("vendor-bills/:id") @RequirePermission("procurement.bill.read") bill(@Param("id") id:string,@Req() r:AuthenticatedRequest){return this.s.getBill(r.auth,id).then(x=>ok(x,r));}
  @Post("vendor-bills/:id/match") @RequirePermission("procurement.bill.match") matchBill(@Param("id") id:string,@Body() b:any,@Headers("idempotency-key") k:string,@Req() r:AuthenticatedRequest){return this.s.runMatch(r.auth,id,b,key(k),rid(r)).then(x=>ok(x,r));}
  @Post("vendor-bills/:id/approve") @RequirePermission("procurement.bill.approve") approveBill(@Param("id") id:string,@Body() b:any,@Headers("idempotency-key") k:string,@Req() r:AuthenticatedRequest){return this.s.billStatus(r.auth,id,"APPROVED",b,key(k),rid(r)).then(x=>ok(x,r));}
  @Post("vendor-bills/:id/post") @RequirePermission("procurement.bill.post") postBill(@Param("id") id:string,@Body() b:any,@Headers("idempotency-key") k:string,@Req() r:AuthenticatedRequest){return this.s.billStatus(r.auth,id,"POSTED",b,key(k),rid(r)).then(x=>ok(x,r));}
  @Post("vendor-bills/:id/:action") @RequirePermission("procurement.bill.approve") billAction(@Param("id") id:string,@Param("action") action:string,@Body() b:any,@Headers("idempotency-key") k:string,@Req() r:AuthenticatedRequest){if(action==="run-match")return this.s.runMatch(r.auth,id,b,key(k),rid(r)).then(x=>ok(x,r));if(action==="override-match")return this.s.overrideMatch(r.auth,id,b,key(k),rid(r)).then(x=>ok(x,r));const to:any={submit:"SUBMITTED",matching:"MATCHING",approve_pending:"PENDING_APPROVAL",approve:"APPROVED",posting:"POSTING",post:"POSTED",hold:"ON_HOLD",request_void:"VOID_PENDING",approve_void:"VOIDED"}[action];return this.s.billStatus(r.auth,id,to,b,key(k),rid(r)).then(x=>ok(x,r));}
  @Get("ap/open-items") @RequirePermission("procurement.ap.read") ap(@Req() r:AuthenticatedRequest){return this.s.listAp(r.auth).then(x=>ok(x,r));}
  @Post("ap/open-items/:id/:action") @RequirePermission("procurement.ap.hold") apAction(@Param("id") id:string,@Param("action") action:string,@Body() b:any,@Headers("idempotency-key") k:string,@Req() r:AuthenticatedRequest){return this.s.apStatus(r.auth,id,action==="place-hold"?"HOLD":"RELEASE_HOLD",b,key(k),rid(r)).then(x=>ok(x,r));}
  @Post("payment-proposals") @RequirePermission("procurement.payment.create") createProposal(@Body() b:any,@Headers("idempotency-key") k:string,@Req() r:AuthenticatedRequest){return this.s.createPaymentProposal(r.auth,b,key(k),rid(r)).then(x=>ok(x,r));}
  @Post("payment-proposals/:id/:action") @RequirePermission("procurement.payment.approve") proposalAction(@Param("id") id:string,@Param("action") action:string,@Body() b:any,@Headers("idempotency-key") k:string,@Req() r:AuthenticatedRequest){const to:any={submit:"PENDING_APPROVAL",approve:"APPROVED",process:"PROCESSING",cancel:"CANCELLED"}[action];return this.s.proposalStatus(r.auth,id,to,b,key(k),rid(r)).then(x=>ok(x,r));}
  @Get("vendor-payments") @RequirePermission("procurement.payment.read") payments(@Req() r:AuthenticatedRequest){return this.s.listPayments(r.auth).then(x=>ok(x,r));}
  @Post("vendor-payments") @RequirePermission("procurement.payment.create") createPayment(@Body() b:any,@Headers("idempotency-key") k:string,@Req() r:AuthenticatedRequest){return this.s.createPayment(r.auth,b,key(k),rid(r)).then(x=>ok(x,r));}
  @Post("vendor-payments/:id/approve") @RequirePermission("procurement.payment.approve") approvePayment(@Param("id") id:string,@Body() b:any,@Headers("idempotency-key") k:string,@Req() r:AuthenticatedRequest){return this.s.paymentStatus(r.auth,id,"APPROVED",b,key(k),rid(r)).then(x=>ok(x,r));}
  @Post("vendor-payments/:id/process") @RequirePermission("procurement.payment.process") processPayment(@Param("id") id:string,@Body() b:any,@Headers("idempotency-key") k:string,@Req() r:AuthenticatedRequest){return this.s.paymentStatus(r.auth,id,"PROCESSING",b,key(k),rid(r)).then(x=>ok(x,r));}
  @Post("vendor-payments/:id/reconcile") @RequirePermission("procurement.payment.reconcile") reconcilePayment(@Param("id") id:string,@Body() b:any,@Headers("idempotency-key") k:string,@Req() r:AuthenticatedRequest){return this.s.reconcilePayment(r.auth,id,b,key(k),rid(r)).then(x=>ok(x,r));}
  @Post("vendor-payments/:id/:action") @RequirePermission("procurement.payment.approve") paymentAction(@Param("id") id:string,@Param("action") action:string,@Body() b:any,@Headers("idempotency-key") k:string,@Req() r:AuthenticatedRequest){if(action==="reconcile")return this.s.reconcilePayment(r.auth,id,b,key(k),rid(r)).then(x=>ok(x,r));const to:any={submit:"PENDING_APPROVAL",approve:"APPROVED",process:"PROCESSING",fail:"FAILED",unknown:"UNKNOWN",cancel:"CANCELLED"}[action];return this.s.paymentStatus(r.auth,id,to,b,key(k),rid(r)).then(x=>ok(x,r));}
  @Post("vendor-credit-notes") @RequirePermission("procurement.credit_note.create") createCredit(@Body() b:any,@Headers("idempotency-key") k:string,@Req() r:AuthenticatedRequest){return this.s.createCredit(r.auth,b,key(k),rid(r)).then(x=>ok(x,r));}
  @Post("vendor-credit-notes/:id/approve") @RequirePermission("procurement.credit_note.approve") approveCredit(@Param("id") id:string,@Body() b:any,@Headers("idempotency-key") k:string,@Req() r:AuthenticatedRequest){return this.s.creditStatus(r.auth,id,"APPROVED",b,key(k),rid(r)).then(x=>ok(x,r));}
  @Post("vendor-credit-notes/:id/apply") @RequirePermission("procurement.credit_note.apply") applyCredit(@Param("id") id:string,@Body() b:any,@Headers("idempotency-key") k:string,@Req() r:AuthenticatedRequest){return this.s.creditStatus(r.auth,id,"APPLIED",b,key(k),rid(r)).then(x=>ok(x,r));}
  @Post("vendor-credit-notes/:id/:action") @RequirePermission("procurement.credit_note.approve") creditAction(@Param("id") id:string,@Param("action") action:string,@Body() b:any,@Headers("idempotency-key") k:string,@Req() r:AuthenticatedRequest){const to:any={submit:"SUBMITTED",approve:"APPROVED",post:"POSTED",apply:"APPLIED",void:"VOID"}[action];return this.s.creditStatus(r.auth,id,to,b,key(k),rid(r)).then(x=>ok(x,r));}
  @Post("vendor-returns") @RequirePermission("procurement.return.create") createReturn(@Body() b:any,@Headers("idempotency-key") k:string,@Req() r:AuthenticatedRequest){return this.s.createReturn(r.auth,b,key(k),rid(r)).then(x=>ok(x,r));}
  @Post("vendor-returns/:id/:action") @RequirePermission("procurement.return.approve") returnAction(@Param("id") id:string,@Param("action") action:string,@Body() b:any,@Headers("idempotency-key") k:string,@Req() r:AuthenticatedRequest){const to:any={submit:"PENDING_APPROVAL",approve:"APPROVED",dispatch:"DISPATCHED",complete:"COMPLETED",cancel:"CANCELLED"}[action];return this.s.returnStatus(r.auth,id,to,b,key(k),rid(r)).then(x=>ok(x,r));}
}
